import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { AppShell, EmptyState } from "@/components/AppShell";
import { useCurrentRole } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { availabilityQuery,debriefsQuery,evaluationsQuery,formatDate,isProgramFinished,programsQuery,solicitationsQuery,tasksQuery } from "@/lib/icc";
import { Badge } from "@/components/ui/badge";import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
export const Route=createFileRoute("/_authenticated/a-faire")({head:()=>({meta:[{title:"À faire — COM ICC Le Mans"},{name:"description",content:"Centre d'actions : réponses, validations, tâches, formations et post-service."}]}),component:ActionCenter});
type Action={id:string;label:string;detail:string;to:string;params?:Record<string,string>;scope:string};const db=()=>supabase as any;
function ActionCenter(){const{member,isStaff,isAdmin,userId}=useCurrentRole();const programs=useQuery(programsQuery),solicitations=useQuery(solicitationsQuery),availability=useQuery(availabilityQuery),tasks=useQuery(tasksQuery),debriefs=useQuery(debriefsQuery),evaluations=useQuery(evaluationsQuery);
const trainingPaths=useQuery({queryKey:["member-training-paths"],queryFn:async()=>{const{data,error}=await db().from("member_training_paths").select("*");if(error)throw error;return data??[]}});const trainingSteps=useQuery({queryKey:["member-training-steps"],queryFn:async()=>{const{data,error}=await db().from("member_training_steps").select("*");if(error)throw error;return data??[]}});const stepDefs=useQuery({queryKey:["training-steps"],queryFn:async()=>{const{data,error}=await db().from("training_steps").select("*");if(error)throw error;return data??[]}});
const memberId=member?.id??null,today=new Date().toISOString().slice(0,10),actions:Action[]=[];
for(const p of programs.data??[]){if(!memberId||p.archived||p.status==="cancelled"||(p.start_date??"9999")<today)continue;const assigned=p.assignments.some(a=>a.memberIds.includes(memberId)),answered=p.responses.some(r=>r.member_id===memberId&&r.status!=="pending");if(assigned&&!answered)actions.push({id:`prog-${p.id}`,label:"Répondre à une affectation",detail:`${p.title} — ${formatDate(p.start_date)}`,to:"/programme/$id",params:{id:p.id},scope:"Personnel"})}
if(isStaff){for(const s of solicitations.data??[]){if(s.archived||s.deleted)continue;if(!s.decision&&s.status!=="accepted"&&s.status!=="refused")actions.push({id:`sol-${s.id}`,label:"Traiter une sollicitation ponctuelle",detail:`${s.event_name??"Sollicitation"} — ${s.requester??"demandeur inconnu"}`,to:"/sollicitations",scope:"COM"})}for(const a of availability.data??[]){if(a.status==="pending")actions.push({id:`av-${a.id}`,label:"Valider une indisponibilité",detail:`${new Date(a.starts_at).toLocaleDateString("fr-FR")} → ${new Date(a.ends_at).toLocaleDateString("fr-FR")}`,to:"/disponibilites",scope:"Pôle"})}for(const p of programs.data??[]){if(p.archived||p.status==="cancelled"||!isProgramFinished(p))continue;const done=(debriefs.data??[]).some(d=>d.program_id===p.id&&d.status==="done");if(!done)actions.push({id:`ps-${p.id}`,label:"Compléter le post-service",detail:`${p.title} — ${formatDate(p.start_date)}`,to:"/post-service",scope:"Pôle"})}}
for(const e of evaluations.data??[]){if(e.status==="draft"&&e.evaluator_user_id===userId)actions.push({id:`ev-${e.id}`,label:"Terminer une évaluation",detail:e.period_label??"Évaluation en brouillon",to:"/evaluations",scope:"Personnel"});if(e.status==="submitted"&&isAdmin)actions.push({id:`evv-${e.id}`,label:"Valider une évaluation",detail:e.period_label??"Évaluation soumise",to:"/evaluations",scope:"COM"})}
for(const t of tasks.data??[]){if(t.status!=="done"&&memberId&&t.assignee_member_id===memberId)actions.push({id:`task-${t.id}`,label:"Tâche à traiter",detail:`${t.title}${t.due_date?` — échéance ${formatDate(t.due_date)}`:""}`,to:"/taches",scope:"Personnel"})}
const defs=new Map((stepDefs.data??[]).map((x:any)=>[x.id,x]));for(const mp of trainingPaths.data??[]){if(mp.status==="completed")continue;const mine=mp.member_id===memberId;for(const ms of (trainingSteps.data??[]).filter((x:any)=>x.member_training_path_id===mp.id)){const def:any=defs.get(ms.step_id);if(!def||ms.status==="done")continue;if(mine&&["content","document","session"].includes(def.step_type))actions.push({id:`train-${ms.id}`,label:"Avancer dans ma formation",detail:def.title,to:"/formations",scope:"Formation"});if(isStaff&&def.step_type==="validation")actions.push({id:`trainval-${ms.id}`,label:"Valider une étape de formation",detail:def.title,to:"/formations",scope:"Référent"})}}
const loading=programs.isLoading||solicitations.isLoading||availability.isLoading||tasks.isLoading||trainingPaths.isLoading||trainingSteps.isLoading||stepDefs.isLoading;return <AppShell title="À faire" subtitle="Uniquement ce qui attend réellement une action de votre part.">{loading?<p className="text-sm text-muted-foreground">Chargement…</p>:actions.length===0?<EmptyState title="Rien à traiter" description="Tout est à jour : aucune action n'attend votre intervention."/>:<div className="space-y-3">{actions.map(a=><Card key={a.id}><CardHeader className="pb-2"><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="text-base">{a.label}</CardTitle><Badge variant="outline">{a.scope}</Badge></div></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-muted-foreground">{a.detail}</p>{a.params?<Link to="/programme/$id" params={a.params as{id:string}} className="text-xs font-bold text-icc-violet">Ouvrir →</Link>:<Link to={a.to as any} className="text-xs font-bold text-icc-violet">Ouvrir →</Link>}</CardContent></Card>)}</div>}</AppShell>}
