import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArchiveRestore, Trash2, Undo2 } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { useCurrentRole } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { formatDate, logAction, polesQuery, programModelsQuery } from "@/lib/icc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

export const Route=createFileRoute("/_authenticated/archives")({head:()=>({meta:[{title:"Archives & corbeille — COM ICC Le Mans"}]}),component:Archives});
type Entry={key:string;id:string;table:"programs"|"solicitations"|"poles"|"program_models"|"members";label:string;detail:string;state:"archived"|"deleted"};
const TABLE_LABEL:Record<Entry["table"],string>={programs:"Programme",solicitations:"Sollicitation",poles:"Pôle",program_models:"Modèle",members:"Membre"};
function Archives(){
 const programs=useQuery({queryKey:["archives-programs"],queryFn:async()=>{const {data,error}=await supabase.from("programs").select("*").or("archived.eq.true,deleted.eq.true").order("start_date");if(error)throw new Error(error.message);return data??[]}});
 const solicitations=useQuery({queryKey:["archives-solicitations"],queryFn:async()=>{const {data,error}=await supabase.from("solicitations").select("*").or("archived.eq.true,deleted.eq.true").order("event_date");if(error)throw new Error(error.message);return data??[]}});
 const archivedMembers=useQuery({queryKey:["archives-members"],queryFn:async()=>{const {data,error}=await supabase.from("members").select("id,full_name,status,arrival_month,arrival_year").eq("status","archived").order("full_name");if(error)throw new Error(error.message);return data??[]}});
 const poles=useQuery(polesQuery),models=useQuery(programModelsQuery),qc=useQueryClient(); const {member,isStaff,isAdmin}=useCurrentRole();
 const entries:Entry[]=[...(programs.data??[]).map(p=>({key:`programs-${p.id}`,id:p.id,table:"programs" as const,label:p.title,detail:formatDate(p.start_date),state:p.deleted?"deleted" as const:"archived" as const})),...(solicitations.data??[]).map(s=>({key:`solicitations-${s.id}`,id:s.id,table:"solicitations" as const,label:s.event_name??"Sollicitation",detail:`${s.requester??"Demandeur inconnu"} · ${formatDate(s.event_date)}`,state:s.deleted?"deleted" as const:"archived" as const})),...(archivedMembers.data??[]).map(m=>({key:`members-${m.id}`,id:m.id,table:"members" as const,label:m.full_name,detail:m.arrival_year?`Intégration ${m.arrival_month?`${m.arrival_month}/`:""}${m.arrival_year}`:"Membre archivé",state:"archived" as const})),...(poles.data??[]).filter(p=>p.archived).map(p=>({key:`poles-${p.id}`,id:p.id,table:"poles" as const,label:p.name,detail:p.pole_group??"Pôle archivé",state:"archived" as const})),...(models.data??[]).filter(m=>m.archived).map(m=>({key:`program_models-${m.id}`,id:m.id,table:"program_models" as const,label:m.name,detail:m.program_type??"Modèle archivé",state:"archived" as const}))];
 function refresh(){for(const k of ["programs","solicitations","members","poles","program-models","archives-programs","archives-solicitations","archives-members"])qc.invalidateQueries({queryKey:[k]})}
 const restore=useMutation({mutationFn:async(e:Entry)=>{let error:any=null;if(e.table==="programs")({error}=await supabase.from("programs").update({archived:false,deleted:false}).eq("id",e.id));else if(e.table==="solicitations")({error}=await supabase.from("solicitations").update({archived:false,deleted:false}).eq("id",e.id));else if(e.table==="members")({error}=await supabase.from("members").update({status:"active"} as any).eq("id",e.id));else if(e.table==="poles")({error}=await supabase.from("poles").update({archived:false}).eq("id",e.id));else({error}=await supabase.from("program_models").update({archived:false}).eq("id",e.id));if(error)throw new Error(error.message);await logAction({action:"element_restaure",entity:e.table,entityId:e.id,detail:e.label,actorName:member?.full_name})},onSuccess:()=>{toast.success("Élément restauré");refresh()},onError:(e:Error)=>toast.error(e.message)});
 const trash=useMutation({mutationFn:async(e:Entry)=>{if(e.table==="members")return; if(e.table!=="programs"&&e.table!=="solicitations")throw new Error("Cet élément ne possède pas de corbeille intermédiaire.");const {error}=await supabase.from(e.table).update({archived:true,deleted:true}).eq("id",e.id);if(error)throw new Error(error.message);await logAction({action:"element_corbeille",entity:e.table,entityId:e.id,detail:e.label,actorName:member?.full_name})},onSuccess:()=>{toast.success("Élément placé dans la corbeille");refresh()},onError:(e:Error)=>toast.error(e.message)});
 const purge=useMutation({mutationFn:async(e:Entry)=>{if(e.table==="members"){const {error}=await supabase.from("members").delete().eq("id",e.id);if(error)throw new Error(error.message)}else{const {error}=await supabase.from(e.table).delete().eq("id",e.id);if(error)throw new Error(error.message)}await logAction({action:"element_supprime_definitivement",entity:e.table,entityId:e.id,detail:e.label,actorName:member?.full_name})},onSuccess:()=>{toast.success("Suppression définitive effectuée");refresh()},onError:(e:Error)=>toast.error(e.message)});
 const loading=programs.isLoading||solicitations.isLoading||archivedMembers.isLoading||poles.isLoading||models.isLoading;
 return <AppShell title="Archives & corbeille" subtitle="Les éléments retirés restent restaurables avant suppression définitive">{loading?<div className="space-y-2">{[0,1,2].map(i=><Skeleton key={i} className="h-16 rounded-xl"/>)}</div>:entries.length===0?<EmptyState title="Aucun élément archivé" description="Les éléments archivés apparaîtront ici."/>:<Card><CardHeader><CardTitle className="text-base">{entries.length} élément(s) conservé(s)</CardTitle></CardHeader><CardContent className="space-y-2">{entries.map(e=><div key={e.key} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3"><div><p className="font-bold">{e.label}</p><p className="text-xs text-muted-foreground">{e.detail}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{TABLE_LABEL[e.table]}</Badge><Badge variant={e.state==="deleted"?"destructive":"outline"}>{e.state==="deleted"?"Corbeille":"Archivé"}</Badge>{isStaff?<Button size="sm" variant="outline" className="gap-1" onClick={()=>restore.mutate(e)}><ArchiveRestore className="size-4"/> Restaurer</Button>:null}{isStaff&&e.state==="archived"&&(e.table==="programs"||e.table==="solicitations")?<Button size="sm" variant="ghost" className="gap-1 text-destructive" onClick={()=>{if(window.confirm(`Placer « ${e.label} » dans la corbeille ?`))trash.mutate(e)}}><Trash2 className="size-4"/> Corbeille</Button>:null}{isAdmin&&(e.state==="deleted"||e.table==="members")?<Button size="sm" variant="ghost" className="gap-1 text-destructive" onClick={()=>{if(window.confirm(`Supprimer définitivement « ${e.label} » ? Cette action est irréversible.`))purge.mutate(e)}}><Undo2 className="size-4"/> Supprimer définitivement</Button>:null}</div></div>)}</CardContent></Card>}</AppShell>
}