import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { CheckCircle2, FileText, HandCoins, Plus, Receipt, ShieldCheck, Wallet } from "lucide-react";
import { toast } from "sonner";

import { AppShell, EmptyState } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useCurrentRole } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { logAction, membersQuery } from "@/lib/icc";

export const Route=createFileRoute("/_authenticated/caisse-fraternelle")({head:()=>({meta:[{title:"Caisse fraternelle — COM ICC Le Mans"},{name:"description",content:"Cotisations, dépenses, justificatifs et journal transparent de la caisse fraternelle."}]}),component:CaisseFraternelle});
const db=()=>supabase as any;
const euro=(v:number|string|null|undefined)=>Number(v??0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
const CATEGORY:Record<string,string>={soutien_fraternel:"🤝 Aide / soutien fraternel",communion_fraternelle:"💜 Communion fraternelle",materiel_com:"🎥 Matériel COM",fonctionnement:"🛠 Fonctionnement",autre:"Autre"};
const STATUS:Record<string,string>={declared:"Déclarée · à confirmer",confirmed:"Confirmée",rejected:"Refusée",cancelled:"Annulée",proposed:"À valider",approved:"Validée"};
function monthLabel(v:string){return new Date(`${v.slice(0,7)}-01T12:00:00`).toLocaleDateString("fr-FR",{month:"long",year:"numeric"})}
function periodsFrom(start:string,count:number){if(!start)return[];const d=new Date(`${start}-01T12:00:00`);return Array.from({length:Math.max(1,count)},(_,i)=>{const x=new Date(d);x.setMonth(x.getMonth()+i);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-01`})}

function usePermission(userId:string|undefined,action:string){return useQuery({queryKey:["finance-permission",userId,action],enabled:!!userId,queryFn:async()=>{const{data,error}=await db().rpc("access_scope_for_user",{p_user:userId,p_module:"finances_equipe",p_action:action});if(error)throw error;return data as string}})}

function CaisseFraternelle(){
 const{member,userId,isTechAdmin}=useCurrentRole();const qc=useQueryClient();const members=useQuery(membersQuery);
 const summary=useQuery({queryKey:["team-finance-summary"],queryFn:async()=>{const{data,error}=await db().rpc("team_finance_public_summary");if(error)throw error;return data as any}});
 const myContrib=useQuery({queryKey:["team-finance-my-contrib",member?.id],enabled:!!member?.id,queryFn:async()=>{const{data,error}=await db().from("team_finance_contributions").select("*").eq("member_id",member!.id).order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const pDetail=usePermission(userId,"voir_detail_cotisations"),pConfirm=usePermission(userId,"confirmer_cotisations"),pExpense=usePermission(userId,"enregistrer_depense"),pApprove=usePermission(userId,"valider_depense"),pReceipt=usePermission(userId,"voir_justificatifs"),pAdmin=usePermission(userId,"administrer");
 const canDetail=isTechAdmin||pDetail.data!=="interdit",canConfirm=isTechAdmin||pConfirm.data!=="interdit",canExpense=isTechAdmin||pExpense.data!=="interdit",canApprove=isTechAdmin||pApprove.data!=="interdit",canReceipt=isTechAdmin||pReceipt.data!=="interdit",canAdmin=isTechAdmin||pAdmin.data!=="interdit";
 const contributions=useQuery({queryKey:["team-finance-contributions-detail",canDetail],enabled:canDetail,queryFn:async()=>{const{data,error}=await db().from("team_finance_contributions").select("*").order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const expenses=useQuery({queryKey:["team-finance-expenses",canExpense||canApprove||canReceipt],enabled:canExpense||canApprove||canReceipt,queryFn:async()=>{const{data,error}=await db().from("team_finance_expenses").select("*").order("expense_date",{ascending:false});if(error)throw error;return data??[]}});
 const adjustments=useQuery({queryKey:["team-finance-adjustments",canAdmin],enabled:canAdmin,queryFn:async()=>{const{data,error}=await db().from("team_finance_adjustments").select("*").order("adjustment_date",{ascending:false});if(error)throw error;return data??[]}});
 const memberName=useMemo(()=>new Map((members.data?.members??[]).map((m:any)=>[m.id,m.full_name])),[members.data]);
 const refresh=()=>Promise.all([qc.invalidateQueries({queryKey:["team-finance-summary"]}),qc.invalidateQueries({queryKey:["team-finance-my-contrib"]}),qc.invalidateQueries({queryKey:["team-finance-contributions-detail"]}),qc.invalidateQueries({queryKey:["team-finance-expenses"]}),qc.invalidateQueries({queryKey:["team-finance-adjustments"]})]);
 const[contribOpen,setContribOpen]=useState(false),[amount,setAmount]=useState(""),[startMonth,setStartMonth]=useState(new Date().toISOString().slice(0,7)),[monthCount,setMonthCount]=useState(1),[paidOn,setPaidOn]=useState(new Date().toISOString().slice(0,10)),[contribNote,setContribNote]=useState("");
 const declareContribution=useMutation({mutationFn:async()=>{if(!member?.id)throw Error("Compte non relié à un membre.");const n=Number(amount.replace(",","."));if(!n||n<=0)throw Error("Montant invalide.");const periods=periodsFrom(startMonth,monthCount);const{data:{user}}=await supabase.auth.getUser();const{error}=await db().from("team_finance_contributions").insert({member_id:member.id,declared_by:user!.id,amount:n,periods,paid_on:paidOn,note:contribNote.trim()||null,status:"declared"});if(error)throw error;await logAction({action:"cotisation_declaree",entity:"team_finance",detail:`${euro(n)} · ${periods.map(monthLabel).join(", ")}`,actorName:member.full_name})},onSuccess:async()=>{toast.success("Cotisation déclarée — en attente de confirmation");setContribOpen(false);setAmount("");setContribNote("");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const confirmContribution=useMutation({mutationFn:async({id,status}:{id:string;status:"confirmed"|"rejected"})=>{const{data:{user}}=await supabase.auth.getUser();const{error}=await db().from("team_finance_contributions").update({status,confirmed_by:user!.id,confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;await logAction({action:status==="confirmed"?"cotisation_confirmee":"cotisation_refusee",entity:"team_finance",entityId:id,actorName:member?.full_name})},onSuccess:refresh,onError:(e:any)=>toast.error(e.message)});
 const[expenseOpen,setExpenseOpen]=useState(false),[expenseAmount,setExpenseAmount]=useState(""),[expenseDate,setExpenseDate]=useState(new Date().toISOString().slice(0,10)),[category,setCategory]=useState("communion_fraternelle"),[publicLabel,setPublicLabel]=useState(""),[privateDetail,setPrivateDetail]=useState(""),[beneficiary,setBeneficiary]=useState(""),[receipt,setReceipt]=useState<File|null>(null);
 const createExpense=useMutation({mutationFn:async()=>{const n=Number(expenseAmount.replace(",","."));if(!n||n<=0||!publicLabel.trim())throw Error("Montant et libellé public obligatoires.");const id=crypto.randomUUID();let receipt_path:string|null=null;if(receipt){const safe=receipt.name.replace(/[^a-zA-Z0-9._-]/g,"-");receipt_path=`${id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from("team-finance-receipts").upload(receipt_path,receipt,{contentType:receipt.type,upsert:false});if(up.error)throw up.error}const{data:{user}}=await supabase.auth.getUser();const{error}=await db().from("team_finance_expenses").insert({id,expense_date:expenseDate,amount:n,category,public_label:publicLabel.trim(),private_detail:privateDetail.trim()||null,beneficiary_private:beneficiary.trim()||null,receipt_path,created_by:user!.id,status:"proposed"});if(error)throw error;await logAction({action:"depense_caisse_proposee",entity:"team_finance",entityId:id,detail:`${publicLabel.trim()} · ${euro(n)}`,actorName:member?.full_name})},onSuccess:async()=>{toast.success("Dépense enregistrée — en attente de validation");setExpenseOpen(false);setExpenseAmount("");setPublicLabel("");setPrivateDetail("");setBeneficiary("");setReceipt(null);await refresh()},onError:(e:any)=>toast.error(e.message)});
 const approveExpense=useMutation({mutationFn:async({id,status}:{id:string;status:"approved"|"rejected"})=>{const{data:{user}}=await supabase.auth.getUser();const{error}=await db().from("team_finance_expenses").update({status,approved_by:user!.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;await logAction({action:status==="approved"?"depense_caisse_validee":"depense_caisse_refusee",entity:"team_finance",entityId:id,actorName:member?.full_name})},onSuccess:refresh,onError:(e:any)=>toast.error(e.message)});
 async function openReceipt(path:string){const{data,error}=await supabase.storage.from("team-finance-receipts").createSignedUrl(path,60);if(error){toast.error(error.message);return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 const[adjustOpen,setAdjustOpen]=useState(false),[adjustAmount,setAdjustAmount]=useState(""),[adjustLabel,setAdjustLabel]=useState(""),[adjustDetail,setAdjustDetail]=useState("");
 const createAdjustment=useMutation({mutationFn:async()=>{const n=Number(adjustAmount.replace(",","."));if(!n||!adjustLabel.trim())throw Error("Montant non nul et libellé obligatoires.");const{data:{user}}=await supabase.auth.getUser();const{error}=await db().from("team_finance_adjustments").insert({amount:n,public_label:adjustLabel.trim(),private_detail:adjustDetail.trim()||null,created_by:user!.id,status:"approved"});if(error)throw error;await logAction({action:"ajustement_caisse",entity:"team_finance",detail:`${adjustLabel.trim()} · ${euro(n)}`,actorName:member?.full_name})},onSuccess:async()=>{setAdjustOpen(false);setAdjustAmount("");setAdjustLabel("");setAdjustDetail("");toast.success("Ajustement enregistré");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const s=summary.data??{};
 return <AppShell title="Caisse fraternelle" subtitle="Une caisse commune transparente, traçable et respectueuse de la confidentialité individuelle." actions={<div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>setContribOpen(true)}><HandCoins className="size-4"/>Déclarer ma cotisation</Button>{canExpense?<Button size="sm" variant="outline" onClick={()=>setExpenseOpen(true)}><Receipt className="size-4"/>Nouvelle dépense</Button>:null}{canAdmin?<Button size="sm" variant="outline" onClick={()=>setAdjustOpen(true)}><Plus className="size-4"/>Ajustement</Button>:null}</div>}>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary icon={<Wallet/>} n={euro(s.balance)} label="Solde réel actuel"/><Summary n={euro(s.monthIncome)} label="Entrées confirmées ce mois"/><Summary n={euro(s.monthExpenses)} label="Dépenses validées ce mois"/><Summary n={euro(s.declaredPendingAmount)} label={`${s.declaredPendingCount??0} cotisation(s) déclarée(s) à confirmer`}/></div>
  <Card className="mt-4"><CardHeader><CardTitle>Journal collectif de caisse</CardTitle><p className="text-sm text-muted-foreground">Visible par l’équipe. Les cotisations sont regroupées : aucun nom ni montant individuel n’est exposé ici.</p></CardHeader><CardContent className="space-y-2">{(s.recent??[]).length?(s.recent??[]).slice(0,30).map((r:any)=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>{r.label}</b><p className="text-xs text-muted-foreground">{new Date(`${r.date}T12:00:00`).toLocaleDateString("fr-FR")} · {r.kind==="expense"?(CATEGORY[r.category]??"Dépense"):r.kind==="contribution"?"Cotisations confirmées":"Ajustement"}</p></div><b className={Number(r.amount)>=0?"text-emerald-700":"text-rose-700"}>{Number(r.amount)>=0?"+":""}{euro(r.amount)}</b></div>):<EmptyState title="Aucun mouvement confirmé" description="Le journal collectif se remplira avec les cotisations confirmées et les dépenses validées."/>}</CardContent></Card>
  <div className="mt-4 grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Mes cotisations</CardTitle></CardHeader><CardContent className="space-y-2">{(myContrib.data??[]).length?(myContrib.data??[]).map((c:any)=><div key={c.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><b>{euro(c.amount)}</b><Badge variant="outline">{STATUS[c.status]??c.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{(c.periods??[]).map(monthLabel).join(" · ")||"Période non précisée"} · déclaré le {new Date(`${c.paid_on}T12:00:00`).toLocaleDateString("fr-FR")}</p></div>):<p className="text-sm text-muted-foreground">Aucune cotisation déclarée.</p>}</CardContent></Card>
  <Card><CardHeader><CardTitle>Transparence de la caisse</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p><b>Total des entrées confirmées :</b> {euro(s.totalIncome)}</p><p><b>Total des sorties validées :</b> {euro(s.totalExpenses)}</p><p className="text-muted-foreground">Le solde n’est jamais saisi manuellement : il est recalculé à partir des écritures validées. Une déclaration en attente n’augmente pas le solde.</p></CardContent></Card></div>
  {canDetail?<Card className="mt-4"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5"/>Registre détaillé des cotisations</CardTitle><p className="text-sm text-muted-foreground">Réservé aux personnes autorisées. Ici seulement apparaissent le membre et son montant individuel.</p></CardHeader><CardContent className="space-y-2">{(contributions.data??[]).map((c:any)=><div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>{memberName.get(c.member_id)??"Membre"} · {euro(c.amount)}</b><p className="text-xs text-muted-foreground">{(c.periods??[]).map(monthLabel).join(" · ")} · {STATUS[c.status]??c.status}</p></div>{canConfirm&&c.status==="declared"?<div className="flex gap-2"><Button size="sm" onClick={()=>confirmContribution.mutate({id:c.id,status:"confirmed"})}><CheckCircle2 className="size-4"/>Confirmer</Button><Button size="sm" variant="outline" onClick={()=>confirmContribution.mutate({id:c.id,status:"rejected"})}>Refuser</Button></div>:null}</div>)}</CardContent></Card>:null}
  {(canExpense||canApprove||canReceipt)?<Card className="mt-4"><CardHeader><CardTitle>Dépenses & justificatifs</CardTitle><p className="text-sm text-muted-foreground">Le public voit le libellé et le montant une fois validés. Les détails personnels et justificatifs restent protégés.</p></CardHeader><CardContent className="space-y-2">{(expenses.data??[]).map((e:any)=><div key={e.id} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-3"><div><b>{e.public_label} · {euro(e.amount)}</b><p className="text-xs text-muted-foreground">{CATEGORY[e.category]??e.category} · {new Date(`${e.expense_date}T12:00:00`).toLocaleDateString("fr-FR")} · {STATUS[e.status]??e.status}</p>{e.private_detail?<p className="mt-1 text-xs">Détail privé : {e.private_detail}</p>:null}{e.beneficiary_private?<p className="text-xs">Bénéficiaire privé : {e.beneficiary_private}</p>:null}</div><div className="flex flex-wrap gap-2">{canReceipt&&e.receipt_path?<Button size="sm" variant="outline" onClick={()=>openReceipt(e.receipt_path)}><FileText className="size-4"/>Justificatif</Button>:null}{canApprove&&e.status==="proposed"?<><Button size="sm" onClick={()=>approveExpense.mutate({id:e.id,status:"approved"})}>Valider</Button><Button size="sm" variant="outline" onClick={()=>approveExpense.mutate({id:e.id,status:"rejected"})}>Refuser</Button></>:null}</div></div></div>)}{!(expenses.data??[]).length?<p className="text-sm text-muted-foreground">Aucune dépense enregistrée.</p>:null}</CardContent></Card>:null}
  <Dialog open={contribOpen} onOpenChange={setContribOpen}><DialogContent><DialogHeader><DialogTitle>Déclarer ma cotisation</DialogTitle></DialogHeader><div className="space-y-4"><Field label="Montant payé (€)"><Input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="20"/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Premier mois couvert"><Input type="month" value={startMonth} onChange={e=>setStartMonth(e.target.value)}/></Field><Field label="Nombre de mois couverts"><Input type="number" min={1} max={24} value={monthCount} onChange={e=>setMonthCount(Math.max(1,Number(e.target.value)||1))}/></Field></div><Field label="Date du paiement"><Input type="date" value={paidOn} onChange={e=>setPaidOn(e.target.value)}/></Field><Field label="Note facultative"><Textarea value={contribNote} onChange={e=>setContribNote(e.target.value)} placeholder="Ex. virement effectué"/></Field><p className="rounded-xl bg-muted p-3 text-xs text-muted-foreground">Périodes : {periodsFrom(startMonth,monthCount).map(monthLabel).join(" · ")}. La déclaration sera visible dans ton espace mais n’augmentera le solde qu’après confirmation.</p></div><DialogFooter><Button variant="outline" onClick={()=>setContribOpen(false)}>Annuler</Button><Button onClick={()=>declareContribution.mutate()} disabled={declareContribution.isPending}>Déclarer</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={expenseOpen} onOpenChange={setExpenseOpen}><DialogContent><DialogHeader><DialogTitle>Enregistrer une dépense</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Montant (€)"><Input inputMode="decimal" value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)}/></Field><Field label="Date"><Input type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)}/></Field></div><Field label="Catégorie"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(CATEGORY).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></Field><Field label="Libellé visible par toute l’équipe"><Input value={publicLabel} onChange={e=>setPublicLabel(e.target.value)} placeholder="Ex. Achat de câbles pour la régie"/></Field><Field label="Détail privé"><Textarea value={privateDetail} onChange={e=>setPrivateDetail(e.target.value)} placeholder="Informations réservées aux personnes autorisées"/></Field><Field label="Bénéficiaire / personne concernée — privé"><Input value={beneficiary} onChange={e=>setBeneficiary(e.target.value)} placeholder="Facultatif — jamais affiché dans le journal collectif"/></Field><Field label="Justificatif (photo ou PDF)"><Input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setReceipt(e.target.files?.[0]??null)}/></Field></div><DialogFooter><Button variant="outline" onClick={()=>setExpenseOpen(false)}>Annuler</Button><Button onClick={()=>createExpense.mutate()} disabled={createExpense.isPending}>Enregistrer</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={adjustOpen} onOpenChange={setAdjustOpen}><DialogContent><DialogHeader><DialogTitle>Ajustement / autre entrée</DialogTitle></DialogHeader><div className="space-y-4"><Field label="Montant (€) — positif ou négatif"><Input inputMode="decimal" value={adjustAmount} onChange={e=>setAdjustAmount(e.target.value)} placeholder="50 ou -20"/></Field><Field label="Libellé collectif"><Input value={adjustLabel} onChange={e=>setAdjustLabel(e.target.value)} placeholder="Ex. Don reçu / correction de caisse"/></Field><Field label="Détail privé"><Textarea value={adjustDetail} onChange={e=>setAdjustDetail(e.target.value)}/></Field><p className="text-xs text-muted-foreground">À utiliser pour les autres entrées ou corrections justifiées. Cette écriture apparaît dans le journal collectif et reste tracée.</p></div><DialogFooter><Button variant="outline" onClick={()=>setAdjustOpen(false)}>Annuler</Button><Button onClick={()=>createAdjustment.mutate()}>Enregistrer</Button></DialogFooter></DialogContent></Dialog>
 </AppShell>
}
function Summary({n,label,icon}:{n:string;label:string;icon?:React.ReactNode}){return <Card><CardContent className="p-4">{icon?<span className="text-icc-violet">{icon}</span>:null}<b className="mt-1 block text-2xl text-icc-violet">{n}</b><small className="text-muted-foreground">{label}</small></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
