import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell } from "@/components/AppShell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const Route=createFileRoute("/_authenticated/decouvrir-module")({component:Page});
const INFO:Record<string,{title:string;icon:string;why:string;contains:string;reserved:string}>={
 pilotage:{title:"Pilotage",icon:"📊",why:"Donner aux responsables une vue synthétique de l’activité et des points qui demandent une décision.",contains:"Besoins non couverts, confirmations attendues, conflits, suivi post-service, formation et indicateurs par périmètre.",reserved:"Les décisions et actions de pilotage sont réservées aux référents et à la direction."},
 modeles:{title:"Modèles de programme",icon:"🧩",why:"Gagner du temps en préparant des structures de programme réutilisables.",contains:"Pôles, besoins, tâches et check-lists préconfigurés pour les programmes récurrents.",reserved:"La création et la modification des modèles sont réservées aux personnes chargées de l’organisation."},
 historique:{title:"Historique",icon:"🕰️",why:"Conserver une trace fiable des actions importantes réalisées dans l’application.",contains:"Créations, modifications, validations, corrections et autres événements de traçabilité.",reserved:"Le détail du journal est limité afin de protéger les informations de gestion et les données personnelles."},
 archives:{title:"Archives & corbeille",icon:"🗄️",why:"Retrouver les éléments sortis des listes actives et, si nécessaire, les restaurer.",contains:"Programmes, sollicitations et autres éléments archivés ou placés en corbeille.",reserved:"Restaurer ou supprimer définitivement un élément est une action de gestion réservée."},
 exports:{title:"Exports",icon:"📤",why:"Produire des fichiers utiles pour le suivi administratif ou opérationnel.",contains:"Exports de données autorisées : membres, programmes, sollicitations et autres synthèses.",reserved:"L’export de données peut contenir des informations sensibles ; il est donc réservé aux rôles habilités."},
 nouveau_programme:{title:"Administration / Nouveau programme",icon:"＋",why:"Créer un programme et préparer son organisation opérationnelle.",contains:"Dates, horaires, format, pôles, besoins, membres mobilisés, documents, notes et échéances de réponse.",reserved:"La création ou la modification d’un programme est réservée aux personnes habilitées. Tout membre peut néanmoins consulter les programmes publiés."},
 parametres:{title:"Paramètres",icon:"⚙️",why:"Configurer le fonctionnement général de l’application.",contains:"Structure des pôles, droits, modules, règles de confidentialité, réglages Vie d’équipe, finances et administration technique.",reserved:"Les réglages ne sont pas modifiables par un équipier. Certains détails techniques ou confidentiels ne sont volontairement pas affichés."}
};
function Page(){const key=new URLSearchParams(window.location.search).get("module")||"parametres",i=INFO[key]??INFO.parametres;return <AppShell title={`${i.icon} ${i.title}`} subtitle="Présentation du module — consultation"><div className="rounded-2xl border border-violet-200 bg-violet-50/60 p-4"><b className="text-icc-violet">Pourquoi tu vois cette page ?</b><p className="mt-1 text-sm text-muted-foreground">Tous les membres peuvent connaître les modules disponibles dans COM ICC Le Mans. Les droits déterminent ce que chacun peut faire, pas la connaissance de l’existence des fonctionnalités.</p></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="text-base">À quoi sert ce module ?</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{i.why}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Ce qu’il contient</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{i.contains}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Pourquoi certaines actions sont réservées</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{i.reserved}</CardContent></Card></div><p className="mt-5 text-sm"><Link to="/tableau-de-bord" className="font-bold text-icc-violet">← Retour au tableau de bord</Link></p></AppShell>}
