import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Check, Plus, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { Field, newId } from "@/components/admin/form-kit";
import { useCurrentRole } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { AVAILABILITY_STATUS_LABEL,availabilityQuery,formatDate,formatDateTime,logAction,membersQuery,polesQuery,programsQuery } from "@/lib/icc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

export const Route=createFileRoute("/_authenticated/disponibilites")({head:()=>({meta:[{title:"Disponibilités — COM ICC Le Mans"},{name:"description",content:"Indisponibilités, affectations, réponses et conflits."}]}),component:Disponibilites});
type Draft={starts_at:string;ends_at:string;note:string;member_id:string};type ResponseStatus="available"|"partial"|"unavailable";const RESP_LABEL:Record<string,string>={pending:"En attente",available:"Disponible",partial:"Partiellement disponible",unavailable:"Indisponible"};
const overlap=(a1:string,a2:string,b1:string,b2:string)=>new Date(a1)<new Date(b2)&&new Date(b1)<new Date(a2);
function Disponibilites(){const availability=useQuery(availabilityQuery),members=useQuery(membersQuery),poles=useQuery(polesQuery),programs=useQuery(programsQuery),qc=useQueryClient();const{member,isStaff,isAdmin,userId}=useCurrentRole();const[draft,setDraft]=useState<Draft|null>(null),[responseNote,setResponseNote]=useState<Record<string,string>>({});const responses=useQuery({queryKey:["program-responses-all"],queryFn:async()=>{const{data,error}=await supabase.from("program_member_responses").select("*");if(error)throw error;return data??[]}});
const memberName=new Map((members.data?.members??[]).map(m=>[m.id,m.full_name]));const poleName=new Map((poles.data??[]).map(p=>[p.id,p.name]));const rows=availability.data??[];const mine=rows.filter(r=>r.member_id===member?.id);const assignments=useMemo(()=>member?.id?(programs.data??[]).filter(p=>!p.archived&&p.assignments.some(a=>a.memberIds.includes(member.id))):[],[member?.id,programs.data]);const responseOf=(pid:string,mid:string)=>(responses.data??[]).find((r:any)=>r.program_id===pid&&r.member_id===mid);const deadlineOf=(p:any)=>p.response_deadline?new Date(p.response_deadline):null;const locked=(p:any)=>{const d=deadlineOf(p);return !!d&&new Date()>d};const programWindow=(p:any)=>{const day=p.start_date;return{start:`${day}T${p.start_time||"00:00"}:00`,end:`${day}T${p.end_time||"23:59"}:00`}};const conflicts=useMemo(()=>{const out:any[]=[];for(const p of programs.data??[]){if(p.archived||p.status==="cancelled")continue;const w=programWindow(p);for(const a of p.assignments){for(const mid of a.memberIds){for(const av of rows.filter(r=>r.member_id===mid&&r.status!=="refused")){if(overlap(w.start,w.end,av.starts_at,av.ends_at))out.push({program:p,memberId:mid,availability:av,poleId:a.pole_id});}}}}return out},[programs.data,rows]);
const refresh=()=>{qc.invalidateQueries({queryKey:["member-availability"]});qc.invalidateQueries({queryKey:["program-responses-all"]});qc.invalidateQueries({queryKey:["programs"]})};
const save=useMutation({mutationFn:async(v:Draft)=>{const mid=v.member_id||member?.id;if(!mid)throw new Error("Aucun membre associé à ce compte.");if(!v.starts_at||!v.ends_at)throw new Error("Début et fin obligatoires.");if(new Date(v.ends_at)<=new Date(v.starts_at))throw new Error("La fin doit être après le début.");const{error}=await supabase.from("member_availability").insert({id:newId("ind"),member_id:mid,starts_at:new Date(v.starts_at).toISOString(),ends_at:new Date(v.ends_at).toISOString(),note:v.note.trim()||null,status:isStaff?"validated":"pending"});if(error)throw error;await logAction({action:"indisponibilite_declaree",entity:"member_availability",entityId:mid,detail:`${v.starts_at} → ${v.ends_at}`,actorName:member?.full_name})},onSuccess:()=>{toast.success("Indisponibilité enregistrée");setDraft(null);refresh()},onError:(e:any)=>toast.error(e.message)});
const decide=useMutation({mutationFn:async({id,status}:{id:string;status:"validated"|"refused"})=>{const{error}=await supabase.from("member_availability").update({status,decided_by:userId??null,decided_at:new Date().toISOString()}).eq("id",id);if(error)throw error;await logAction({action:status==="validated"?"indisponibilite_validee":"indisponibilite_refusee",entity:"member_availability",entityId:id,actorName:member?.full_name})},onSuccess:refresh});
const remove=useMutation({mutationFn:async(id:string)=>{const{error}=await supabase.from("member_availability").delete().eq("id",id);if(error)throw error;await logAction({action:"indisponibilite_supprimee",entity:"member_availability",entityId:id,actorName:member?.full_name})},onSuccess:refresh});
const respond=useMutation({mutationFn:async({p,status}:{p:any;status:ResponseStatus})=>{if(!member?.id)throw new Error("Compte non lié à un membre.");if(locked(p)&&!isStaff)throw new Error("La date limite de réponse est dépassée.");const old=responseOf(p.id,member.id);const note=responseNote[p.id]?.trim()||null;const{error}=await supabase.from("program_member_responses").upsert({id:`${p.id}__${member.id}`,program_id:p.id,member_id:member.id,status,reserve:status==="partial"?note:null,reason:status==="unavailable"?note:null},{onConflict:"program_id,member_id"});if(error)throw error;await logAction({action:old?"reponse_affectation_modifiee":"reponse_affectation",entity:"program",entityId:p.id,detail:`${RESP_LABEL[old?.status??"pending"]} → ${RESP_LABEL[status]}${locked(p)?" · après échéance":""}`,actorName:member.full_name})},onSuccess:()=>{toast.success("Réponse enregistrée");refresh()},onError:(e:any)=>toast.error(e.message)});
function AvailabilityRow({r}:{r:any}){const canDecide=isStaff&&r.status==="pending";const canDelete=isAdmin||r.member_id===member?.id;return <div className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><div><b>{memberName.get(r.member_id)??r.member_id}</b><p className="text-xs text-muted-foreground">{formatDateTime(r.starts_at)} → {formatDateTime(r.ends_at)}</p>{r.note?<p className="mt-1 text-sm">{r.note}</p>:null}</div><Badge variant="secondary">{AVAILABILITY_STATUS_LABEL[r.status]??r.status}</Badge></div>{canDecide||canDelete?<div className="mt-2 flex gap-2">{canDecide?<><Button size="sm" onClick={()=>decide.mutate({id:r.id,status:"validated"})}><Check className="size-4"/>Valider</Button><Button size="sm" variant="outline" onClick={()=>decide.mutate({id:r.id,status:"refused"})}><X className="size-4"/>Refuser</Button></>:null}{canDelete?<Button size="sm" variant="ghost" className="text-destructive" onClick={()=>remove.mutate(r.id)}><Trash2 className="size-4"/>Supprimer</Button>:null}</div>:null}</div>}
return <AppShell title="Disponibilités" subtitle="Indisponibilités, affectations, réponses et conflits au même endroit" actions={<Button size="sm" onClick={()=>setDraft({starts_at:"",ends_at:"",note:"",member_id:member?.id??""})}><Plus className="size-4"/>Déclarer une indisponibilité</Button>}><Tabs defaultValue="mine"><TabsList className="mb-5 flex-wrap"><TabsTrigger value="mine">Mes indisponibilités</TabsTrigger><TabsTrigger value="assignments">Mes affectations</TabsTrigger>{isStaff?<><TabsTrigger value="team">Équipe</TabsTrigger><TabsTrigger value="conflicts">Conflits {conflicts.length?`(${conflicts.length})`:""}</TabsTrigger></>:null}</TabsList>
<TabsContent value="mine"><Card><CardHeader><CardTitle>Mes indisponibilités</CardTitle></CardHeader><CardContent className="space-y-3">{mine.length?mine.map(r=><AvailabilityRow key={r.id} r={r}/>):<EmptyState title="Aucune indisponibilité déclarée" description="Vous pouvez déclarer une journée entière, une période ou seulement quelques heures."/>}</CardContent></Card></TabsContent>
<TabsContent value="assignments" className="space-y-3">{assignments.length?assignments.map((p:any)=>{const res=responseOf(p.id,member!.id);const d=deadlineOf(p);const isLocked=locked(p);return <Card key={p.id}><CardContent className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link to="/programme/$id" params={{id:p.id}} className="font-bold hover:text-icc-violet">{p.title}</Link><p className="text-sm text-muted-foreground">{formatDate(p.start_date)} · {p.start_time??"—"} → {p.end_time??"—"}</p><p className="text-xs text-muted-foreground">{p.assignments.filter((a:any)=>a.memberIds.includes(member!.id)).map((a:any)=>poleName.get(a.pole_id)??"Pôle").join(" · ")}</p>{d?<p className="mt-1 text-xs">Réponse possible jusqu’au {formatDateTime(d.toISOString())}</p>:<p className="mt-1 text-xs text-muted-foreground">Aucune date limite définie</p>}</div><Badge variant={isLocked?"secondary":"outline"}>{res?RESP_LABEL[res.status]??res.status:"En attente"}</Badge></div>{!isLocked||isStaff?<div className="mt-3 space-y-2"><div className="flex flex-wrap gap-2"><Button size="sm" variant={res?.status==="available"?"default":"outline"} onClick={()=>respond.mutate({p,status:"available"})}>Disponible</Button><Button size="sm" variant={res?.status==="partial"?"default":"outline"} onClick={()=>respond.mutate({p,status:"partial"})}>Partiellement</Button><Button size="sm" variant={res?.status==="unavailable"?"default":"outline"} onClick={()=>respond.mutate({p,status:"unavailable"})}>Indisponible</Button></div><Textarea rows={2} placeholder="Précision utile pour une disponibilité partielle ou un refus…" value={responseNote[p.id]??res?.reserve??res?.reason??""} onChange={e=>setResponseNote({...responseNote,[p.id]:e.target.value})}/><p className="text-xs text-muted-foreground">Votre réponse peut être modifiée tant que la date limite n’est pas dépassée. Chaque changement est tracé.</p></div>:<p className="mt-3 rounded-lg bg-muted p-3 text-sm">Date limite dépassée : la réponse est verrouillée. Contactez votre référent ou le responsable du programme si votre situation a changé.</p>}</CardContent></Card>}):<EmptyState title="Aucune affectation à venir"/>}</TabsContent>
{isStaff?<><TabsContent value="team"><Card><CardHeader><CardTitle>Indisponibilités de l’équipe</CardTitle></CardHeader><CardContent className="space-y-3">{rows.length?rows.map(r=><AvailabilityRow key={r.id} r={r}/>):<EmptyState title="Aucune indisponibilité"/>}</CardContent></Card></TabsContent><TabsContent value="conflicts" className="space-y-3">{conflicts.length?conflicts.map((c:any,i)=><Card key={`${c.program.id}-${c.memberId}-${i}`}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><b>{memberName.get(c.memberId)??c.memberId}</b><p className="text-sm">{c.program.title} · {poleName.get(c.poleId)??"Pôle"}</p><p className="text-xs text-muted-foreground">Indisponible {formatDateTime(c.availability.starts_at)} → {formatDateTime(c.availability.ends_at)}</p></div><Button asChild size="sm" variant="outline"><Link to="/programme/$id" params={{id:c.program.id}}>Voir le programme</Link></Button></CardContent></Card>):<EmptyState title="Aucun conflit détecté"/>}</TabsContent></>:null}</Tabs>
<Dialog open={!!draft} onOpenChange={o=>{if(!o)setDraft(null)}}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Déclarer une indisponibilité</DialogTitle></DialogHeader>{draft?<div className="space-y-3">{isStaff?<Field label="Membre concerné"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={draft.member_id} onChange={e=>setDraft({...draft,member_id:e.target.value})}><option value={member?.id??""}>Moi-même</option>{(members.data?.members??[]).filter(m=>m.status==="active"&&m.id!==member?.id).map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></Field>:null}<div className="rounded-lg bg-muted p-3 text-xs text-muted-foreground">Vous pouvez saisir quelques heures seulement, une journée complète ou plusieurs jours. Les conflits sont calculés sur les horaires réels.</div><div className="grid gap-3 sm:grid-cols-2"><Field label="Début"><Input type="datetime-local" value={draft.starts_at} onChange={e=>setDraft({...draft,starts_at:e.target.value})}/></Field><Field label="Fin"><Input type="datetime-local" value={draft.ends_at} onChange={e=>setDraft({...draft,ends_at:e.target.value})}/></Field></div><Field label="Motif / précision (optionnel)"><Textarea rows={2} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></Field></div>:null}<DialogFooter><Button variant="ghost" onClick={()=>setDraft(null)}>Annuler</Button><Button disabled={save.isPending} onClick={()=>draft&&save.mutate(draft)}>Enregistrer</Button></DialogFooter></DialogContent></Dialog></AppShell>}
