import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Download } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { useCurrentRole } from "@/hooks/useAuth";
import { downloadCsv, exportStamp, toCsv, type Column } from "@/lib/exports";
import { auditQuery, formatDateTime, logAction, membersQuery, polesQuery, programsQuery, RESPONSE_LABEL, solicitationsQuery, STATUS_LABEL, TASK_PRIORITY_LABEL, TASK_STATUS_LABEL, tasksQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
export const Route=createFileRoute("/_authenticated/exports")({head:()=>({meta:[{title:"Exports — COM ICC Le Mans"}]}),component:Exports});
function Exports(){
 const{member}=useCurrentRole();const poles=useQuery(polesQuery),members=useQuery(membersQuery),programs=useQuery(programsQuery),solicitations=useQuery(solicitationsQuery),tasks=useQuery(tasksQuery),audit=useQuery(auditQuery);
 const material=useQuery({queryKey:["exports-material"],queryFn:async()=>{const db=supabase as any;const[items,needs,requests,itemPoles,requestNeeds]=await Promise.all([db.from("material_items").select("*").eq("archived",false),db.from("material_needs").select("*"),db.from("material_requests").select("*"),db.from("material_item_poles").select("*"),db.from("material_request_needs").select("*")]);for(const r of[items,needs,requests,itemPoles,requestNeeds])if(r.error)throw new Error(r.error.message);return{items:items.data??[],needs:needs.data??[],requests:requests.data??[],itemPoles:itemPoles.data??[],requestNeeds:requestNeeds.data??[]}}});
 const poleName=new Map((poles.data??[]).map(p=>[p.id,p.name])),memberName=new Map((members.data?.members??[]).map(m=>[m.id,m.full_name])),links=members.data?.links??[];
 async function run<T>(name:string,label:string,rows:T[],columns:Column<T>[]){if(!rows.length){toast.info("Rien à exporter",{description:`Aucune donnée pour « ${label} ».`});return}downloadCsv(`icc-${name}-${exportStamp()}.csv`,toCsv(rows,columns));toast.success(`${label} exporté`,{description:`${rows.length} ligne(s)`});await logAction({action:"export_csv",entity:name,detail:`${label} — ${rows.length} ligne(s)`,actorName:member?.full_name})}
 const blocks:Array<{name:string;label:string;description:string;count:number;go:()=>void}>=[
 {name:"equipiers",label:"Équipiers",description:"Identité, statut, rôle de base, arrivée, pôles rattachés.",count:(members.data?.members??[]).length,go:()=>run("equipiers","Équipiers",members.data?.members??[],[{key:"full_name",label:"Nom complet",value:m=>m.full_name},{key:"base_role",label:"Rôle de base",value:m=>m.base_role},{key:"status",label:"Statut",value:m=>m.status},{key:"login_email",label:"E-mail",value:m=>m.login_email},{key:"arrivee",label:"Arrivée",value:m=>[m.arrival_month,m.arrival_year].filter(Boolean).join("/")},{key:"ejp",label:"EJP",value:m=>m.is_ejp},{key:"icc",label:"ICC",value:m=>m.is_icc},{key:"formation",label:"Formation faite",value:m=>m.training_done},{key:"poles",label:"Pôles",value:m=>links.filter(l=>l.member_id===m.id).map(l=>`${poleName.get(l.pole_id)??l.pole_id}${l.is_referent?" (référent)":""}`).join(" · ")}])},
 {name:"poles",label:"Pôles",description:"Nom, groupe, description, ordre d’affichage, archivage.",count:(poles.data??[]).length,go:()=>run("poles","Pôles",poles.data??[],[{key:"name",label:"Nom",value:p=>p.name},{key:"pole_group",label:"Groupe",value:p=>p.pole_group},{key:"description",label:"Description",value:p=>p.description},{key:"sort_order",label:"Ordre",value:p=>p.sort_order},{key:"archived",label:"Archivé",value:p=>p.archived},{key:"members",label:"Équipiers",value:p=>links.filter(l=>l.pole_id===p.id).map(l=>memberName.get(l.member_id)??l.member_id).join(" · ")}])},
 {name:"programmes",label:"Programmes",description:"Dates, lieu, statut, pôles affectés, équipiers et réponses.",count:(programs.data??[]).length,go:()=>run("programmes","Programmes",programs.data??[],[{key:"title",label:"Titre",value:p=>p.title},{key:"start_date",label:"Date début",value:p=>p.start_date},{key:"start_time",label:"Heure début",value:p=>p.start_time},{key:"end_date",label:"Date fin",value:p=>p.end_date},{key:"end_time",label:"Heure fin",value:p=>p.end_time},{key:"location",label:"Lieu",value:p=>p.location},{key:"status",label:"Statut",value:p=>STATUS_LABEL[p.status]??p.status},{key:"importance",label:"Importance",value:p=>p.importance},{key:"poles",label:"Pôles affectés",value:p=>p.assignments.map(a=>poleName.get(a.pole_id)??a.pole_id).join(" · ")},{key:"membres",label:"Équipiers affectés",value:p=>[...new Set(p.assignments.flatMap(a=>a.memberIds))].map(id=>memberName.get(id)??id).join(" · ")},{key:"reponses",label:"Réponses",value:p=>p.responses.map(r=>`${memberName.get(r.member_id)??r.member_id}: ${RESPONSE_LABEL[r.status]}`).join(" · ")}])},
 {name:"sollicitations",label:"Sollicitations",description:"Demandeur, événement, cible, statut et décision.",count:(solicitations.data??[]).length,go:()=>run("sollicitations","Sollicitations",solicitations.data??[],[{key:"event_name",label:"Événement",value:s=>s.event_name},{key:"event_date",label:"Date",value:s=>s.event_date},{key:"requester",label:"Demandeur",value:s=>s.requester},{key:"mode",label:"Mode",value:s=>s.mode},{key:"status",label:"Statut",value:s=>STATUS_LABEL[s.status]??s.status},{key:"target",label:"Cible",value:s=>s.target_name??poleName.get(s.target_pole_id??"")},{key:"decision",label:"Décision",value:s=>s.decision},{key:"decision_note",label:"Note de décision",value:s=>s.decision_note},{key:"message",label:"Message",value:s=>s.message}])},
 {name:"taches",label:"Tâches",description:"To-do central : échéances, priorités, assignations.",count:(tasks.data??[]).length,go:()=>run("taches","Tâches",tasks.data??[],[{key:"title",label:"Tâche",value:t=>t.title},{key:"status",label:"Statut",value:t=>TASK_STATUS_LABEL[t.status]??t.status},{key:"priority",label:"Priorité",value:t=>TASK_PRIORITY_LABEL[t.priority]??t.priority},{key:"due_date",label:"Échéance",value:t=>t.due_date},{key:"assignee",label:"Assignée à",value:t=>t.assignee_member_id?memberName.get(t.assignee_member_id)??t.assignee_member_id:""},{key:"pole",label:"Pôle",value:t=>t.pole_id?poleName.get(t.pole_id)??t.pole_id:""},{key:"detail",label:"Détail",value:t=>t.detail}])},
 {name:"materiel-inventaire",label:"Matériel COM — Inventaire",description:"Équipements, état, quantité, rangement, pôles utilisateurs, responsable et valeur.",count:(material.data?.items??[]).length,go:()=>run("materiel-inventaire","Inventaire Matériel COM",material.data?.items??[],[{key:"name",label:"Matériel",value:(x:any)=>x.name},{key:"category",label:"Catégorie",value:(x:any)=>x.category},{key:"brand",label:"Marque",value:(x:any)=>x.brand},{key:"model",label:"Modèle",value:(x:any)=>x.model},{key:"serial_number",label:"N° série",value:(x:any)=>x.serial_number},{key:"quantity",label:"Quantité",value:(x:any)=>x.quantity},{key:"state",label:"État",value:(x:any)=>x.state},{key:"location",label:"Rangement",value:(x:any)=>x.location},{key:"poles",label:"Pôles utilisateurs",value:(x:any)=>(material.data?.itemPoles??[]).filter((p:any)=>p.item_id===x.id).map((p:any)=>poleName.get(p.pole_id)??p.pole_id).join(" · ")},{key:"responsible",label:"Responsable",value:(x:any)=>memberName.get(x.responsible_member_id)??""},{key:"purchase_date",label:"Date acquisition",value:(x:any)=>x.purchase_date},{key:"purchase_price",label:"Valeur / prix",value:(x:any)=>x.purchase_price},{key:"notes",label:"Notes",value:(x:any)=>x.notes}])},
 {name:"materiel-besoins",label:"Matériel COM — Besoins",description:"Besoins, priorités, horizon, budget estimatif, justification et avancement.",count:(material.data?.needs??[]).length,go:()=>run("materiel-besoins","Besoins Matériel COM",material.data?.needs??[],[{key:"title",label:"Besoin",value:(x:any)=>x.title},{key:"pole",label:"Pôle",value:(x:any)=>poleName.get(x.pole_id)??""},{key:"priority",label:"Priorité",value:(x:any)=>x.priority},{key:"horizon",label:"Horizon",value:(x:any)=>x.horizon},{key:"quantity",label:"Quantité",value:(x:any)=>x.quantity},{key:"estimated_budget",label:"Budget estimatif",value:(x:any)=>x.estimated_budget},{key:"status",label:"Statut",value:(x:any)=>x.status},{key:"desired_by",label:"Date souhaitée",value:(x:any)=>x.desired_by},{key:"description",label:"Description",value:(x:any)=>x.description},{key:"justification",label:"Justification",value:(x:any)=>x.justification},{key:"alternative",label:"Alternative",value:(x:any)=>x.alternative}])},
 {name:"materiel-demandes",label:"Matériel COM — Demandes",description:"Dossiers transmis aux finances de l’Église et besoins regroupés.",count:(material.data?.requests??[]).length,go:()=>run("materiel-demandes","Demandes Matériel COM",material.data?.requests??[],[{key:"title",label:"Dossier",value:(x:any)=>x.title},{key:"status",label:"Statut",value:(x:any)=>x.status},{key:"church_reference",label:"Référence Église",value:(x:any)=>x.church_reference},{key:"sent_at",label:"Transmise le",value:(x:any)=>x.sent_at},{key:"decided_at",label:"Décision le",value:(x:any)=>x.decided_at},{key:"needs",label:"Besoins inclus",value:(x:any)=>(material.data?.requestNeeds??[]).filter((r:any)=>r.request_id===x.id).map((r:any)=>material.data?.needs.find((n:any)=>n.id===r.need_id)?.title??r.need_id).join(" · ")},{key:"notes",label:"Notes",value:(x:any)=>x.notes},{key:"decision_note",label:"Décision / commentaire",value:(x:any)=>x.decision_note}])},
 {name:"journal",label:"Journal d’activité",description:"100 dernières actions tracées dans le pilotage.",count:(audit.data??[]).length,go:()=>run("journal","Journal d’activité",audit.data??[],[{key:"occurred_at",label:"Date",value:a=>formatDateTime(a.occurred_at)},{key:"action",label:"Action",value:a=>a.action},{key:"actor_name",label:"Auteur",value:a=>a.actor_name},{key:"entity",label:"Entité",value:a=>a.entity},{key:"detail",label:"Détail",value:a=>a.detail}])}
 ];
 return <AppShell title="Exports" subtitle="Point d’entrée unique — CSV compatible Excel (UTF-8)"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{blocks.map(block=><Card key={block.name}><CardHeader><CardTitle className="text-base">{block.label}</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{block.description}</p><p className="text-xs text-muted-foreground">{block.count} ligne(s) disponibles</p><Button className="w-full gap-2" onClick={block.go} disabled={block.count===0}><Download className="size-4"/>Exporter en CSV</Button></CardContent></Card>)}</div></AppShell>
}
