import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Archive, CheckCircle2, GraduationCap, Plus, UserPlus } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { useCurrentRole } from "@/hooks/useAuth";
import { logAction, membersQuery, polesQuery, programsQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

export const Route=createFileRoute("/_authenticated/formations")({head:()=>({meta:[{title:"Formations — COM ICC Le Mans"},{name:"description",content:"Parcours de formation par pôle, pratique sur programmes et validations."}]}),component:Formations});

type TrainingPath={id:string;pole_id:string;name:string;description:string|null;archived:boolean;created_at:string};
type TrainingStep={id:string;path_id:string;title:string;description:string|null;step_type:string;position:number;required_count:number;resource_url:string|null;required:boolean};
type MemberPath={id:string;member_id:string;path_id:string;status:string;started_at:string;completed_at:string|null;note:string|null};
type MemberStep={id:string;member_training_path_id:string;step_id:string;status:string;progress_count:number;validated_by_member_id:string|null;validated_at:string|null;note:string|null};
const db=()=>supabase as any;const uid=()=>crypto.randomUUID();
const TYPE_LABEL:Record<string,string>={content:"Contenu",document:"Document / ressource",practical:"Pratique sur programme",validation:"Validation référent",session:"Session de formation"};

function Formations(){
 const {member,isStaff}=useCurrentRole();const qc=useQueryClient();const members=useQuery(membersQuery),poles=useQuery(polesQuery),programs=useQuery(programsQuery);
 const paths=useQuery({queryKey:["training-paths"],queryFn:async()=>{const{data,error}=await db().from("training_paths").select("*").order("created_at");if(error)throw error;return(data??[]) as TrainingPath[]}});
 const steps=useQuery({queryKey:["training-steps"],queryFn:async()=>{const{data,error}=await db().from("training_steps").select("*").order("position");if(error)throw error;return(data??[]) as TrainingStep[]}});
 const memberPaths=useQuery({queryKey:["member-training-paths"],queryFn:async()=>{const{data,error}=await db().from("member_training_paths").select("*").order("started_at",{ascending:false});if(error)throw error;return(data??[]) as MemberPath[]}});
 const memberSteps=useQuery({queryKey:["member-training-steps"],queryFn:async()=>{const{data,error}=await db().from("member_training_steps").select("*");if(error)throw error;return(data??[]) as MemberStep[]}});
 const allMembers=members.data?.members??[],activePoles=(poles.data??[]).filter(p=>!p.archived),poleName=new Map((poles.data??[]).map(p=>[p.id,p.name])),memberName=new Map(allMembers.map(m=>[m.id,m.full_name]));
 const pathById=new Map((paths.data??[]).map(p=>[p.id,p]));const stepById=new Map((steps.data??[]).map(s=>[s.id,s]));
 const participations=(mid:string,pid:string)=>(programs.data??[]).filter(p=>!p.archived&&p.status!=="cancelled"&&p.assignments.some(a=>a.pole_id===pid&&a.memberIds.includes(mid))).length;
 const progressFor=(mp:MemberPath)=>{const list=(memberSteps.data??[]).filter(x=>x.member_training_path_id===mp.id);const path=pathById.get(mp.path_id);const defs=(steps.data??[]).filter(s=>s.path_id===mp.path_id&&s.required);if(!defs.length)return 0;let done=0;for(const def of defs){const ms=list.find(x=>x.step_id===def.id);if(def.step_type==="practical"&&path){if(participations(mp.member_id,path.pole_id)>=def.required_count)done++;}else if(ms?.status==="done")done++;}return Math.round(done/defs.length*100)};
 const readyForValidation=(mp:MemberPath,def:TrainingStep)=>{if(def.step_type!=="practical")return false;const path=pathById.get(mp.path_id);return !!path&&participations(mp.member_id,path.pole_id)>=def.required_count};
 const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:["training-paths"]}),qc.invalidateQueries({queryKey:["training-steps"]}),qc.invalidateQueries({queryKey:["member-training-paths"]}),qc.invalidateQueries({queryKey:["member-training-steps"]}),qc.invalidateQueries({queryKey:["members"]})])};
 const [pathOpen,setPathOpen]=useState(false),[pathName,setPathName]=useState(""),[pathPole,setPathPole]=useState(""),[pathDesc,setPathDesc]=useState(""),[rawSteps,setRawSteps]=useState("Accueil & fonctionnement\nBases du pôle\npractical | Pratique accompagnée | 2\nvalidation | Validation finale par le référent");
 const createPath=useMutation({mutationFn:async()=>{if(!pathName.trim()||!pathPole)throw new Error("Nom et pôle obligatoires.");const pid=uid();let{error}=await db().from("training_paths").insert({id:pid,pole_id:pathPole,name:pathName.trim(),description:pathDesc.trim()||null});if(error)throw error;const parsed=rawSteps.split("\n").map(x=>x.trim()).filter(Boolean).map((line,index)=>{const parts=line.split("|").map(x=>x.trim());const known=["content","document","practical","validation","session"].includes(parts[0]);const type=known?parts[0]:"content";const title=known?(parts[1]||"Étape"):line;const required=type==="practical"?Math.max(1,Number(parts[2])||1):1;const resource=type==="document"?(parts[2]||null):null;return{id:uid(),path_id:pid,title,step_type:type,position:index,required_count:required,resource_url:resource,required:true}});if(parsed.length){const r=await db().from("training_steps").insert(parsed);if(r.error)throw r.error}await logAction({action:"parcours_formation_cree",entity:"training_path",entityId:pid,detail:pathName.trim(),actorName:member?.full_name})},onSuccess:async()=>{setPathOpen(false);setPathName("");setPathDesc("");toast.success("Parcours créé");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const archivePath=useMutation({mutationFn:async(p:TrainingPath)=>{const{error}=await db().from("training_paths").update({archived:!p.archived,updated_at:new Date().toISOString()}).eq("id",p.id);if(error)throw error},onSuccess:refresh});
 const [assignPath,setAssignPath]=useState<TrainingPath|null>(null),[assignMember,setAssignMember]=useState("");
 const assign=useMutation({mutationFn:async()=>{if(!assignPath||!assignMember)throw new Error("Choisissez une personne.");const mpid=uid();let{error}=await db().from("member_training_paths").insert({id:mpid,member_id:assignMember,path_id:assignPath.id,status:"in_progress",assigned_by_member_id:member?.id??null});if(error)throw error;const defs=(steps.data??[]).filter(s=>s.path_id===assignPath.id);if(defs.length){const r=await db().from("member_training_steps").insert(defs.map(s=>({id:uid(),member_training_path_id:mpid,step_id:s.id,status:"todo",progress_count:0})));if(r.error)throw r.error}await db().from("members").update({training_done:false,training_start:new Date().toISOString().slice(0,10)}).eq("id",assignMember);await logAction({action:"parcours_formation_attribue",entity:"member",entityId:assignMember,detail:assignPath.name,actorName:member?.full_name})},onSuccess:async()=>{setAssignPath(null);setAssignMember("");toast.success("Parcours attribué");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const markStep=useMutation({mutationFn:async({ms,status}:{ms:MemberStep;status:string})=>{const{error}=await db().from("member_training_steps").update({status,validated_at:status==="done"?new Date().toISOString():null,validated_by_member_id:status==="done"&&isStaff?member?.id??null:null}).eq("id",ms.id);if(error)throw error;const def=stepById.get(ms.step_id);await logAction({action:"etape_formation_statut",entity:"training_step",entityId:ms.id,detail:`${def?.title??"Étape"} → ${status}`,actorName:member?.full_name})},onSuccess:refresh});
 const completePath=useMutation({mutationFn:async(mp:MemberPath)=>{const pct=progressFor(mp);if(pct<100)throw new Error("Toutes les étapes obligatoires doivent être validées.");let{error}=await db().from("member_training_paths").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",mp.id);if(error)throw error;await db().from("members").update({training_done:true}).eq("id",mp.member_id);await logAction({action:"formation_terminee",entity:"member",entityId:mp.member_id,detail:pathById.get(mp.path_id)?.name??"Parcours terminé",actorName:member?.full_name})},onSuccess:async()=>{toast.success("Parcours validé · la personne est désormais formée");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const mine=(memberPaths.data??[]).filter(x=>x.member_id===member?.id&&x.status!=="completed");const pendingValidations=(memberPaths.data??[]).flatMap(mp=>(memberSteps.data??[]).filter(ms=>ms.member_training_path_id===mp.id).map(ms=>({mp,ms,def:stepById.get(ms.step_id)}))).filter(x=>x.def&&(x.def.step_type==="validation"&&x.ms.status!=="done"||x.def.step_type==="practical"&&x.ms.status!=="done"&&readyForValidation(x.mp,x.def)));
 const loading=paths.isLoading||steps.isLoading||memberPaths.isLoading||memberSteps.isLoading;
 if(loading)return <AppShell title="Formations"><p className="text-sm text-muted-foreground">Chargement des parcours…</p></AppShell>;
 return <AppShell title="Formations" subtitle="Parcours par pôle → pratique réelle → validation référent → montée en compétence" actions={isStaff?<Button size="sm" onClick={()=>setPathOpen(true)}><Plus className="size-4"/>Nouveau parcours</Button>:undefined}>
 <Tabs defaultValue="mine"><TabsList className="mb-5 flex-wrap"><TabsTrigger value="mine">Mes formations</TabsTrigger>{isStaff?<><TabsTrigger value="validate">À valider {pendingValidations.length?`(${pendingValidations.length})`:""}</TabsTrigger><TabsTrigger value="paths">Parcours</TabsTrigger><TabsTrigger value="tracking">Suivi</TabsTrigger></>:null}</TabsList>
 <TabsContent value="mine" className="space-y-4">{mine.length===0?<EmptyState title="Aucun parcours en cours" description="Vos parcours de formation apparaîtront ici lorsqu'ils seront attribués."/>:mine.map(mp=><TrainingCard key={mp.id} mp={mp} path={pathById.get(mp.path_id)} defs={(steps.data??[]).filter(s=>s.path_id===mp.path_id)} rows={(memberSteps.data??[]).filter(s=>s.member_training_path_id===mp.id)} progress={progressFor(mp)} participantCount={(pid)=>participations(mp.member_id,pid)} canValidate={false} memberLabel={member?.full_name??""} onToggle={(ms,status)=>markStep.mutate({ms,status})}/>)}</TabsContent>
 {isStaff?<><TabsContent value="validate" className="space-y-3">{pendingValidations.length===0?<EmptyState title="Aucune validation en attente"/>:pendingValidations.map(({mp,ms,def})=><Card key={ms.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><Badge variant="outline">{TYPE_LABEL[def!.step_type]??def!.step_type}</Badge><p className="mt-1 font-semibold">{def!.title}</p><p className="text-sm text-muted-foreground">{memberName.get(mp.member_id)??mp.member_id} · {pathById.get(mp.path_id)?.name}</p>{def!.step_type==="practical"?<p className="text-xs text-muted-foreground">{participations(mp.member_id,pathById.get(mp.path_id)?.pole_id??"")} participation(s) / {def!.required_count} requise(s)</p>:null}</div><Button onClick={()=>markStep.mutate({ms,status:"done"})}><CheckCircle2 className="size-4"/>Valider l’étape</Button></CardContent></Card>)}</TabsContent>
 <TabsContent value="paths"><div className="grid gap-4 md:grid-cols-2">{(paths.data??[]).filter(p=>!p.archived).map(p=><Card key={p.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{p.name}</CardTitle><p className="text-sm text-muted-foreground">{poleName.get(p.pole_id)??"Pôle"}</p></div><Badge variant="secondary">{(steps.data??[]).filter(s=>s.path_id===p.id).length} étapes</Badge></div></CardHeader><CardContent className="space-y-3">{p.description?<p className="text-sm text-muted-foreground">{p.description}</p>:null}<ol className="space-y-2">{(steps.data??[]).filter(s=>s.path_id===p.id).map((s,i)=><li key={s.id} className="rounded-lg border p-2 text-sm"><b>{i+1}. {s.title}</b><span className="ml-2 text-xs text-muted-foreground">{TYPE_LABEL[s.step_type]??s.step_type}{s.step_type==="practical"?` · ${s.required_count} programme(s)`:""}</span>{s.resource_url?<a className="mt-1 block text-xs font-semibold text-icc-violet underline" href={s.resource_url} target="_blank" rel="noreferrer">Ouvrir la ressource</a>:null}</li>)}</ol><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>setAssignPath(p)}><UserPlus className="size-4"/>Attribuer</Button><Button asChild size="sm" variant="outline"><Link to="/pole/$id" params={{id:p.pole_id}}>Voir le pôle</Link></Button><Button size="sm" variant="ghost" onClick={()=>archivePath.mutate(p)}><Archive className="size-4"/>Archiver</Button></div></CardContent></Card>)}</div></TabsContent>
 <TabsContent value="tracking" className="space-y-3">{(memberPaths.data??[]).length===0?<EmptyState title="Aucun parcours attribué"/>:(memberPaths.data??[]).map(mp=>{const pct=progressFor(mp),path=pathById.get(mp.path_id);return <Card key={mp.id}><CardContent className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link to="/membre/$id" params={{id:mp.member_id}} className="font-bold hover:text-icc-violet">{memberName.get(mp.member_id)??mp.member_id}</Link><p className="text-xs text-muted-foreground">{path?.name??"Parcours"} · {path?poleName.get(path.pole_id):""}</p></div><Badge variant={mp.status==="completed"?"secondary":"outline"}>{mp.status==="completed"?"Terminé":mp.status==="paused"?"En pause":"En formation"}</Badge></div><Progress value={pct} className="mt-3"/><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-muted-foreground">{pct}% · début {new Date(mp.started_at).toLocaleDateString("fr-FR")}</p>{mp.status!=="completed"&&pct===100?<Button size="sm" onClick={()=>completePath.mutate(mp)}><GraduationCap className="size-4"/>Valider le parcours et passer formé</Button>:null}</div></CardContent></Card>})}</TabsContent></>:null}
 </Tabs>
 <Dialog open={pathOpen} onOpenChange={setPathOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Nouveau parcours de formation</DialogTitle></DialogHeader><div className="space-y-3"><Input placeholder="Nom du parcours" value={pathName} onChange={e=>setPathName(e.target.value)}/><Select value={pathPole} onValueChange={setPathPole}><SelectTrigger><SelectValue placeholder="Pôle concerné"/></SelectTrigger><SelectContent>{activePoles.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><Textarea placeholder="Description" value={pathDesc} onChange={e=>setPathDesc(e.target.value)}/><div><p className="mb-1 text-sm font-semibold">Étapes · une ligne par étape</p><Textarea rows={8} value={rawSteps} onChange={e=>setRawSteps(e.target.value)}/><p className="mt-1 text-xs text-muted-foreground">Simple : « Bases du pôle ». Pratique : « practical | Pratique accompagnée | 2 ». Validation : « validation | Validation finale ». Document : « document | Guide | https://… ».</p></div></div><DialogFooter><Button variant="ghost" onClick={()=>setPathOpen(false)}>Annuler</Button><Button disabled={createPath.isPending} onClick={()=>createPath.mutate()}>Créer le parcours</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!assignPath} onOpenChange={o=>{if(!o)setAssignPath(null)}}><DialogContent><DialogHeader><DialogTitle>Attribuer · {assignPath?.name}</DialogTitle></DialogHeader><Select value={assignMember} onValueChange={setAssignMember}><SelectTrigger><SelectValue placeholder="Choisir une personne"/></SelectTrigger><SelectContent>{allMembers.filter(m=>m.status==="active").map(m=><SelectItem key={m.id} value={m.id}>{m.full_name}</SelectItem>)}</SelectContent></Select><DialogFooter><Button variant="ghost" onClick={()=>setAssignPath(null)}>Annuler</Button><Button disabled={assign.isPending||!assignMember} onClick={()=>assign.mutate()}>Attribuer le parcours</Button></DialogFooter></DialogContent></Dialog>
 </AppShell>
}

function TrainingCard({mp,path,defs,rows,progress,participantCount,canValidate,memberLabel,onToggle}:{mp:MemberPath;path?:TrainingPath;defs:TrainingStep[];rows:MemberStep[];progress:number;participantCount:(poleId:string)=>number;canValidate:boolean;memberLabel:string;onToggle:(ms:MemberStep,status:string)=>void}){return <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-2"><div><CardTitle>{path?.name??"Parcours"}</CardTitle><p className="text-sm text-muted-foreground">{memberLabel}</p></div><Badge variant="secondary">{progress}%</Badge></div><Progress value={progress}/></CardHeader><CardContent className="space-y-2">{defs.map(def=>{const ms=rows.find(x=>x.step_id===def.id);const practical=def.step_type==="practical"&&path?participantCount(path.pole_id):0;const automaticallyReady=def.step_type==="practical"&&practical>=def.required_count;const done=ms?.status==="done";return <div key={def.id} className="flex items-start justify-between gap-3 rounded-lg border p-3"><div><p className={done?"font-semibold line-through":"font-semibold"}>{done?"☑":"☐"} {def.title}</p><p className="text-xs text-muted-foreground">{TYPE_LABEL[def.step_type]??def.step_type}{def.step_type==="practical"?` · ${practical}/${def.required_count} participation(s)`:""}</p>{def.resource_url?<a href={def.resource_url} target="_blank" rel="noreferrer" className="text-xs font-semibold text-icc-violet underline">Ouvrir la ressource</a>:null}{automaticallyReady&&!done?<p className="text-xs font-semibold text-amber-700">Objectif pratique atteint · en attente de validation</p>:null}</div>{ms&&def.step_type!=="validation"&&def.step_type!=="practical"?<Button size="sm" variant={done?"outline":"default"} onClick={()=>onToggle(ms,done?"todo":"done")}>{done?"Rouvrir":"Terminer"}</Button>:null}</div>})}</CardContent></Card>}
