import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Archive, CheckCircle2, Plus, UserPlus } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { useCurrentRole } from "@/hooks/useAuth";
import { logAction, membersQuery, polesQuery, programsQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

export const Route=createFileRoute("/_authenticated/formations")({head:()=>({meta:[{title:"Formations — COM ICC Le Mans"},{name:"description",content:"Parcours d’intégration et montée en compétences interne par pôle."}]}),component:Formations});

type PathKind="integration"|"internal";
type TrainingPath={id:string;pole_id:string;name:string;description:string|null;archived:boolean;created_at:string;path_kind:PathKind};
type TrainingStep={id:string;path_id:string;title:string;description:string|null;step_type:string;position:number;required_count:number;resource_url:string|null;required:boolean};
type MemberPath={id:string;member_id:string;path_id:string;status:string;started_at:string;completed_at:string|null;note:string|null};
type MemberStep={id:string;member_training_path_id:string;step_id:string;status:string;progress_count:number;validated_by_member_id:string|null;validated_at:string|null;note:string|null};
const db=()=>supabase as any;const uid=()=>crypto.randomUUID();
const TYPE_LABEL:Record<string,string>={content:"Contenu",document:"Document / ressource",practical:"Pratique sur programme",validation:"Validation référent",session:"Session de formation"};
const KIND_LABEL:Record<PathKind,string>={integration:"Intégration",internal:"Formation interne"};

function Formations(){
 const{member,isStaff}=useCurrentRole();const qc=useQueryClient();const members=useQuery(membersQuery),poles=useQuery(polesQuery),programs=useQuery(programsQuery);
 const paths=useQuery({queryKey:["training-paths"],queryFn:async()=>{const{data,error}=await db().from("training_paths").select("*").order("created_at");if(error)throw error;return(data??[]) as TrainingPath[]}});
 const steps=useQuery({queryKey:["training-steps"],queryFn:async()=>{const{data,error}=await db().from("training_steps").select("*").order("position");if(error)throw error;return(data??[]) as TrainingStep[]}});
 const memberPaths=useQuery({queryKey:["member-training-paths"],queryFn:async()=>{const{data,error}=await db().from("member_training_paths").select("*").order("started_at",{ascending:false});if(error)throw error;return(data??[]) as MemberPath[]}});
 const memberSteps=useQuery({queryKey:["member-training-steps"],queryFn:async()=>{const{data,error}=await db().from("member_training_steps").select("*");if(error)throw error;return(data??[]) as MemberStep[]}});
 const allMembers=members.data?.members??[],activePoles=(poles.data??[]).filter(p=>!p.archived),poleName=new Map((poles.data??[]).map(p=>[p.id,p.name])),memberName=new Map(allMembers.map(m=>[m.id,m.full_name]));
 const pathById=new Map((paths.data??[]).map(p=>[p.id,p])),stepById=new Map((steps.data??[]).map(s=>[s.id,s]));
 const participations=(mid:string,pid:string)=>(programs.data??[]).filter(p=>!p.archived&&p.status!=="cancelled"&&p.assignments.some(a=>a.pole_id===pid&&a.memberIds.includes(mid))).length;
 const progressFor=(mp:MemberPath)=>{const defs=(steps.data??[]).filter(s=>s.path_id===mp.path_id&&s.required),rows=(memberSteps.data??[]).filter(x=>x.member_training_path_id===mp.id),path=pathById.get(mp.path_id);if(!defs.length)return 0;let done=0;for(const def of defs){const ms=rows.find(x=>x.step_id===def.id);if(def.step_type==="practical"&&path&&participations(mp.member_id,path.pole_id)>=def.required_count)done++;else if(ms?.status==="done")done++;}return Math.round(done/defs.length*100)};
 const readyForValidation=(mp:MemberPath,def:TrainingStep)=>{const path=pathById.get(mp.path_id);return def.step_type==="practical"&&!!path&&participations(mp.member_id,path.pole_id)>=def.required_count};
 const refresh=()=>Promise.all([qc.invalidateQueries({queryKey:["training-paths"]}),qc.invalidateQueries({queryKey:["training-steps"]}),qc.invalidateQueries({queryKey:["member-training-paths"]}),qc.invalidateQueries({queryKey:["member-training-steps"]}),qc.invalidateQueries({queryKey:["members"]})]);
 const[pathOpen,setPathOpen]=useState(false),[pathName,setPathName]=useState(""),[pathPole,setPathPole]=useState(""),[pathDesc,setPathDesc]=useState(""),[pathKind,setPathKind]=useState<PathKind>("integration"),[rawSteps,setRawSteps]=useState("Accueil & fonctionnement\nBases du pôle\npractical | Pratique accompagnée | 2\nvalidation | Validation finale par le référent");
 const createPath=useMutation({mutationFn:async()=>{if(!pathName.trim()||!pathPole)throw new Error("Nom et pôle obligatoires.");const pid=uid();const{error}=await db().from("training_paths").insert({id:pid,pole_id:pathPole,name:pathName.trim(),description:pathDesc.trim()||null,path_kind:pathKind});if(error)throw error;const parsed=rawSteps.split("\n").map(x=>x.trim()).filter(Boolean).map((line,index)=>{const p=line.split("|").map(x=>x.trim()),known=["content","document","practical","validation","session"].includes(p[0]),type=known?p[0]:"content",title=known?(p[1]||"Étape"):line;return{id:uid(),path_id:pid,title,step_type:type,position:index,required_count:type==="practical"?Math.max(1,Number(p[2])||1):1,resource_url:type==="document"?(p[2]||null):null,required:true}});if(parsed.length){const r=await db().from("training_steps").insert(parsed);if(r.error)throw r.error}await logAction({action:"parcours_formation_cree",entity:"training_path",entityId:pid,detail:`${KIND_LABEL[pathKind]} · ${pathName.trim()}`,actorName:member?.full_name})},onSuccess:async()=>{setPathOpen(false);setPathName("");setPathDesc("");toast.success("Parcours créé");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const archivePath=useMutation({mutationFn:async(p:TrainingPath)=>{const{error}=await db().from("training_paths").update({archived:!p.archived,updated_at:new Date().toISOString()}).eq("id",p.id);if(error)throw error},onSuccess:refresh});
 const[assignPath,setAssignPath]=useState<TrainingPath|null>(null),[assignMember,setAssignMember]=useState("");
 const assign=useMutation({mutationFn:async()=>{if(!assignPath||!assignMember)throw new Error("Choisissez une personne.");const mpid=uid();const{error}=await db().from("member_training_paths").insert({id:mpid,member_id:assignMember,path_id:assignPath.id,status:"in_progress",assigned_by_member_id:member?.id??null});if(error)throw error;const defs=(steps.data??[]).filter(s=>s.path_id===assignPath.id);if(defs.length){const r=await db().from("member_training_steps").insert(defs.map(s=>({id:uid(),member_training_path_id:mpid,step_id:s.id,status:"todo",progress_count:0})));if(r.error)throw r.error}if(assignPath.path_kind==="integration"){await db().from("members").update({training_done:false,training_start:new Date().toISOString().slice(0,10)}).eq("id",assignMember)}await logAction({action:assignPath.path_kind==="internal"?"formation_interne_attribuee":"parcours_integration_attribue",entity:"member",entityId:assignMember,detail:`${assignPath.name} · ${poleName.get(assignPath.pole_id)??"Pôle"}`,actorName:member?.full_name})},onSuccess:async()=>{setAssignPath(null);setAssignMember("");toast.success("Parcours attribué");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const markStep=useMutation({mutationFn:async({ms,status}:{ms:MemberStep;status:string})=>{const{error}=await db().from("member_training_steps").update({status,validated_at:status==="done"?new Date().toISOString():null,validated_by_member_id:status==="done"&&isStaff?member?.id??null:null}).eq("id",ms.id);if(error)throw error;await logAction({action:"etape_formation_statut",entity:"training_step",entityId:ms.id,detail:`${stepById.get(ms.step_id)?.title??"Étape"} → ${status}`,actorName:member?.full_name})},onSuccess:refresh});
 const completePath=useMutation({mutationFn:async(mp:MemberPath)=>{if(progressFor(mp)<100)throw new Error("Toutes les étapes obligatoires doivent être validées.");const path=pathById.get(mp.path_id);const{error}=await db().from("member_training_paths").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",mp.id);if(error)throw error;if(path?.path_kind==="integration")await db().from("members").update({training_done:true}).eq("id",mp.member_id);await logAction({action:path?.path_kind==="internal"?"formation_interne_terminee":"formation_integration_terminee",entity:"member",entityId:mp.member_id,detail:`${path?.name??"Parcours"} · ${path?poleName.get(path.pole_id)??"Pôle":""}`,actorName:member?.full_name})},onSuccess:async()=>{toast.success("Parcours validé");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const mine=(memberPaths.data??[]).filter(x=>x.member_id===member?.id&&x.status!=="completed"),pendingValidations=(memberPaths.data??[]).flatMap(mp=>(memberSteps.data??[]).filter(ms=>ms.member_training_path_id===mp.id).map(ms=>({mp,ms,def:stepById.get(ms.step_id)}))).filter(x=>x.def&&((x.def.step_type==="validation"&&x.ms.status!=="done")||(x.def.step_type==="practical"&&x.ms.status!=="done"&&readyForValidation(x.mp,x.def))));
 const activeMP=(memberPaths.data??[]).filter(x=>x.status!=="completed"),integrationCount=activeMP.filter(x=>pathById.get(x.path_id)?.path_kind==="integration").length,internalCount=activeMP.filter(x=>pathById.get(x.path_id)?.path_kind==="internal").length;
 if(paths.isLoading||steps.isLoading||memberPaths.isLoading||memberSteps.isLoading)return <AppShell title="Formations"><p className="text-sm text-muted-foreground">Chargement…</p></AppShell>;
 return <AppShell title="Formations" subtitle="Intégration des nouveaux membres et montée en compétences interne" actions={isStaff?<Button size="sm" onClick={()=>setPathOpen(true)}><Plus className="size-4"/>Nouveau parcours</Button>:undefined}><div className="mb-5 grid gap-3 sm:grid-cols-3"><Summary n={integrationCount} label="Intégrations en cours"/><Summary n={internalCount} label="Formations internes en cours"/><Summary n={pendingValidations.length} label="Validations à traiter"/></div><Tabs defaultValue="mine"><TabsList className="mb-5 flex-wrap"><TabsTrigger value="mine">Mes formations</TabsTrigger>{isStaff?<><TabsTrigger value="validate">À valider</TabsTrigger><TabsTrigger value="paths">Parcours</TabsTrigger><TabsTrigger value="tracking">Suivi</TabsTrigger></>:null}</TabsList>
 <TabsContent value="mine" className="space-y-4">{mine.length===0?<EmptyState title="Aucun parcours en cours"/>:mine.map(mp=><TrainingCard key={mp.id} mp={mp} path={pathById.get(mp.path_id)} defs={(steps.data??[]).filter(s=>s.path_id===mp.path_id)} rows={(memberSteps.data??[]).filter(s=>s.member_training_path_id===mp.id)} progress={progressFor(mp)} participations={participations}/>)}</TabsContent>
 {isStaff?<><TabsContent value="validate" className="space-y-3">{pendingValidations.length===0?<EmptyState title="Aucune validation en attente"/>:pendingValidations.map(({mp,ms,def})=>{const p=pathById.get(mp.path_id);return <Card key={ms.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><div className="flex gap-2"><Badge variant="outline">{p?KIND_LABEL[p.path_kind]:"Formation"}</Badge><Badge variant="secondary">{TYPE_LABEL[def!.step_type]??def!.step_type}</Badge></div><p className="mt-2 font-semibold">{def!.title}</p><p className="text-sm text-muted-foreground">{memberName.get(mp.member_id)??mp.member_id} · {p?.name}</p></div><Button onClick={()=>markStep.mutate({ms,status:"done"})}><CheckCircle2 className="size-4"/>Valider</Button></CardContent></Card>})}</TabsContent>
 <TabsContent value="paths"><div className="grid gap-4 md:grid-cols-2">{(paths.data??[]).filter(p=>!p.archived).map(p=><Card key={p.id}><CardHeader><div className="flex items-start justify-between gap-3"><div className="space-y-1"><Badge variant={p.path_kind==="internal"?"secondary":"outline"}>{KIND_LABEL[p.path_kind]}</Badge><CardTitle>{p.name}</CardTitle><p className="text-sm text-muted-foreground">{poleName.get(p.pole_id)??"Pôle"}</p></div><Badge variant="outline">{(steps.data??[]).filter(s=>s.path_id===p.id).length} étapes</Badge></div></CardHeader><CardContent className="space-y-3">{p.description?<p className="text-sm text-muted-foreground">{p.description}</p>:null}<ol className="space-y-2">{(steps.data??[]).filter(s=>s.path_id===p.id).map((s,i)=><li key={s.id} className="rounded-lg border p-2 text-sm"><b>{i+1}. {s.title}</b><span className="ml-2 text-xs text-muted-foreground">{TYPE_LABEL[s.step_type]??s.step_type}{s.step_type==="practical"?` · ${s.required_count} programme(s)`:""}</span></li>)}</ol><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>setAssignPath(p)}><UserPlus className="size-4"/>Attribuer</Button><Button asChild size="sm" variant="outline"><Link to="/pole/$id" params={{id:p.pole_id}}>Voir le pôle</Link></Button><Button size="sm" variant="ghost" onClick={()=>archivePath.mutate(p)}><Archive className="size-4"/>Archiver</Button></div></CardContent></Card>)}</div></TabsContent>
 <TabsContent value="tracking" className="space-y-3">{(memberPaths.data??[]).length===0?<EmptyState title="Aucun parcours attribué"/>:(memberPaths.data??[]).map(mp=>{const p=pathById.get(mp.path_id),pct=progressFor(mp);return <Card key={mp.id}><CardContent className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link to="/membre/$id" params={{id:mp.member_id}} className="font-bold hover:text-icc-violet">{memberName.get(mp.member_id)??mp.member_id}</Link><p className="text-xs text-muted-foreground">{p?.name} · {p?poleName.get(p.pole_id):""}</p></div><div className="flex gap-2"><Badge variant={p?.path_kind==="internal"?"secondary":"outline"}>{p?KIND_LABEL[p.path_kind]:"Formation"}</Badge><Badge>{mp.status==="completed"?"Terminé":"En cours"}</Badge></div></div><Progress value={pct} className="mt-3"/><p className="mt-1 text-xs text-muted-foreground">{pct}%</p>{mp.status!=="completed"&&pct===100?<Button className="mt-3" size="sm" onClick={()=>completePath.mutate(mp)}>Clôturer le parcours</Button>:null}</CardContent></Card>})}</TabsContent></>:null}</Tabs>
 <Dialog open={pathOpen} onOpenChange={setPathOpen}><DialogContent><DialogHeader><DialogTitle>Nouveau parcours</DialogTitle></DialogHeader><div className="space-y-3"><Select value={pathKind} onValueChange={v=>setPathKind(v as PathKind)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="integration">Intégration — nouveau membre COM</SelectItem><SelectItem value="internal">Formation interne — nouvelle compétence</SelectItem></SelectContent></Select><Input placeholder="Nom du parcours" value={pathName} onChange={e=>setPathName(e.target.value)}/><Select value={pathPole} onValueChange={setPathPole}><SelectTrigger><SelectValue placeholder="Pôle concerné"/></SelectTrigger><SelectContent>{activePoles.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><Textarea placeholder="Description / objectif" value={pathDesc} onChange={e=>setPathDesc(e.target.value)}/><Textarea rows={6} value={rawSteps} onChange={e=>setRawSteps(e.target.value)}/><p className="text-xs text-muted-foreground">Formation interne : le membre garde son rôle et ses pôles actuels. Le parcours représente uniquement une compétence en cours d'acquisition.</p></div><DialogFooter><Button variant="ghost" onClick={()=>setPathOpen(false)}>Annuler</Button><Button onClick={()=>createPath.mutate()} disabled={createPath.isPending}>Créer</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!assignPath} onOpenChange={o=>{if(!o)setAssignPath(null)}}><DialogContent><DialogHeader><DialogTitle>Attribuer — {assignPath?.name}</DialogTitle></DialogHeader><div className="space-y-3">{assignPath?<div className="rounded-lg bg-muted p-3 text-sm"><b>{KIND_LABEL[assignPath.path_kind]}</b><p className="text-muted-foreground">{assignPath.path_kind==="internal"?"Le statut principal du membre ne sera pas modifié.":"Ce parcours correspond à son intégration dans la COM."}</p></div>:null}<Select value={assignMember} onValueChange={setAssignMember}><SelectTrigger><SelectValue placeholder="Choisir une personne"/></SelectTrigger><SelectContent>{allMembers.filter(m=>m.status==="active").sort((a,b)=>a.full_name.localeCompare(b.full_name,"fr")).map(m=><SelectItem key={m.id} value={m.id}>{m.full_name}</SelectItem>)}</SelectContent></Select></div><DialogFooter><Button variant="ghost" onClick={()=>setAssignPath(null)}>Annuler</Button><Button onClick={()=>assign.mutate()} disabled={assign.isPending}>Attribuer</Button></DialogFooter></DialogContent></Dialog></AppShell>}

function Summary({n,label}:{n:number;label:string}){return <Card><CardContent className="p-4"><p className="text-2xl font-bold text-icc-violet">{n}</p><p className="text-xs font-semibold">{label}</p></CardContent></Card>}
function TrainingCard({mp,path,defs,rows,progress,participations}:{mp:MemberPath;path?:TrainingPath;defs:TrainingStep[];rows:MemberStep[];progress:number;participations:(m:string,p:string)=>number}){return <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge variant={path?.path_kind==="internal"?"secondary":"outline"}>{path?KIND_LABEL[path.path_kind]:"Formation"}</Badge><CardTitle className="mt-2">{path?.name??"Parcours"}</CardTitle></div><b>{progress}%</b></div></CardHeader><CardContent className="space-y-3"><Progress value={progress}/>{defs.map(def=>{const row=rows.find(r=>r.step_id===def.id),auto=def.step_type==="practical"&&path?participations(mp.member_id,path.pole_id)>=def.required_count:false,done=row?.status==="done"||auto;return <div key={def.id} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><div><b className={done?"line-through":""}>{def.title}</b><p className="text-xs text-muted-foreground">{TYPE_LABEL[def.step_type]??def.step_type}{def.step_type==="practical"&&path?` · ${participations(mp.member_id,path.pole_id)}/${def.required_count} programme(s)`:""}</p></div><Badge variant={done?"secondary":"outline"}>{done?"Acquis":"À faire"}</Badge></div></div>})}</CardContent></Card>}
