import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { AlertTriangle, Boxes, FileDown, FileText, Hand, Link2, PackageCheck, Plus, ReceiptText, Settings2, Wrench } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useCurrentRole } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { membersQuery, polesQuery, programsQuery } from "@/lib/icc";

export const Route = createFileRoute("/_authenticated/materiel-com")({ head: () => ({ meta: [{ title: "Matériel COM — COM ICC Le Mans" }] }), component: MaterialCom });
const db = () => supabase as any;
const euro = (n:any) => Number(n||0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
const STATES:any={excellent:"🟢 Excellent",bon:"🟢 Bon",a_surveiller:"🟠 À surveiller",a_reparer:"🛠 À réparer",hors_service:"🔴 Hors service",perdu:"⚫ Perdu"};
const PRIORITY:any={basse:"Basse",normale:"Normale",haute:"Haute",critique:"Critique"};
const HORIZON:any={immediat:"Immédiat",court_terme:"Court terme",moyen_terme:"Moyen terme",long_terme:"Long terme"};
const NEED_STATUS:any={brouillon:"Brouillon",exprime:"Besoin exprimé",a_etudier:"À étudier",devis_demande:"Devis demandé",devis_recu:"Devis reçu",transmis_eglise:"Transmis à l’Église",valide:"Validé",refuse:"Refusé",reporte:"Reporté",commande:"Commandé",recu:"Reçu"};
const REQ_STATUS:any={brouillon:"Brouillon",preparation:"Préparation",transmise:"Transmise",validee:"Validée",refusee:"Refusée",reportee:"Reportée",commandee:"Commandée",recue:"Reçue"};
function perm(uid:string|undefined,a:string){return useQuery({queryKey:["mat-perm",uid,a],enabled:!!uid,queryFn:async()=>{const{data,error}=await db().rpc("material_scope_for_user",{p_user:uid,p_action:a});if(error)throw error;return data as string}})}

function MaterialCom(){
 const {userId,isTechAdmin}=useCurrentRole(),qc=useQueryClient();
 const poles=useQuery(polesQuery),members=useQuery(membersQuery),programs=useQuery(programsQuery);
 const pInv=perm(userId,"gerer_inventaire"),pNeed=perm(userId,"creer_besoin"),pNeeds=perm(userId,"gerer_besoins"),pReq=perm(userId,"gerer_demandes"),pDocs=perm(userId,"voir_documents"),pLoans=perm(userId,"gerer_prets"),pAdmin=perm(userId,"administrer");
 const canInv=isTechAdmin||pInv.data!=="interdit",canCreateNeed=isTechAdmin||pNeed.data!=="interdit",canNeeds=isTechAdmin||pNeeds.data!=="interdit",canReq=isTechAdmin||pReq.data!=="interdit",canDocs=isTechAdmin||pDocs.data!=="interdit",canLoans=isTechAdmin||pLoans.data!=="interdit",canAdmin=isTechAdmin||pAdmin.data!=="interdit";
 const items=useQuery({queryKey:["material-items"],queryFn:async()=>{const{data,error}=await db().from("material_items").select("*").eq("archived",false).order("name");if(error)throw error;return data??[]}});
 const itemPoles=useQuery({queryKey:["material-item-poles"],queryFn:async()=>{const{data,error}=await db().from("material_item_poles").select("*");if(error)throw error;return data??[]}});
 const needs=useQuery({queryKey:["material-needs"],queryFn:async()=>{const{data,error}=await db().from("material_needs").select("*").order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const links=useQuery({queryKey:["material-links"],queryFn:async()=>{const{data,error}=await db().from("material_need_links").select("*").order("created_at");if(error)throw error;return data??[]}});
 const requests=useQuery({queryKey:["material-requests"],queryFn:async()=>{const{data,error}=await db().from("material_requests").select("*").order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const reqNeeds=useQuery({queryKey:["material-request-needs"],queryFn:async()=>{const{data,error}=await db().from("material_request_needs").select("*");if(error)throw error;return data??[]}});
 const incidents=useQuery({queryKey:["material-incidents"],queryFn:async()=>{const{data,error}=await db().from("material_incidents").select("*").order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const loans=useQuery({queryKey:["material-loans"],queryFn:async()=>{const{data,error}=await db().from("material_loans").select("*").order("out_at",{ascending:false});if(error)throw error;return data??[]}});
 const docs=useQuery({queryKey:["material-docs",canDocs],enabled:canDocs,queryFn:async()=>{const{data,error}=await db().from("material_documents").select("*").order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const managers=useQuery({queryKey:["material-managers"],queryFn:async()=>{const{data,error}=await db().from("material_managers").select("*").eq("active",true);if(error)throw error;return data??[]}});
 const poleName=new Map((poles.data??[]).map((p:any)=>[p.id,p.name])), memberName=new Map((members.data?.members??[]).map((m:any)=>[m.id,m.full_name])), itemName=new Map((items.data??[]).map((x:any)=>[x.id,x.name]));
 const refresh=()=>Promise.all(["material-items","material-item-poles","material-needs","material-links","material-requests","material-request-needs","material-incidents","material-loans","material-docs","material-managers"].map(k=>qc.invalidateQueries({queryKey:[k]})));
 const [tab,setTab]=useState("inventaire");
 const stats=useMemo(()=>{const its=items.data??[],ns=needs.data??[],incs=incidents.data??[];return{items:its.reduce((s:any,x:any)=>s+Number(x.quantity||0),0),repair:its.filter((x:any)=>["a_reparer","hors_service"].includes(x.state)).length,needs:ns.filter((x:any)=>!["recu","refuse"].includes(x.status)).length,critical:ns.filter((x:any)=>x.priority==="critique"&&!["recu","refuse"].includes(x.status)).length,budget:ns.filter((x:any)=>!["recu","refuse"].includes(x.status)).reduce((s:any,x:any)=>s+Number(x.estimated_budget||0),0),incidents:incs.filter((x:any)=>x.status!=="resolu").length}},[items.data,needs.data,incidents.data]);

 const [itemOpen,setItemOpen]=useState(false),[editItem,setEditItem]=useState<any>(null),[iname,setIname]=useState(""),[icat,setIcat]=useState("autre"),[ibrand,setIbrand]=useState(""),[imodel,setImodel]=useState(""),[iserial,setIserial]=useState(""),[iqty,setIqty]=useState("1"),[istate,setIstate]=useState("bon"),[iloc,setIloc]=useState(""),[ipole,setIpole]=useState(""),[iresp,setIresp]=useState(""),[iprice,setIprice]=useState(""),[idate,setIdate]=useState(""),[inotes,setInotes]=useState("");
 function openItem(x?:any){setEditItem(x??null);setIname(x?.name??"");setIcat(x?.category??"autre");setIbrand(x?.brand??"");setImodel(x?.model??"");setIserial(x?.serial_number??"");setIqty(String(x?.quantity??1));setIstate(x?.state??"bon");setIloc(x?.location??"");setIpole(x?.primary_pole_id??"");setIresp(x?.responsible_member_id??"");setIprice(x?.purchase_price?String(x.purchase_price):"");setIdate(x?.purchase_date??"");setInotes(x?.notes??"");setItemOpen(true)}
 const saveItem=useMutation({mutationFn:async()=>{if(!iname.trim())throw Error("Nom du matériel obligatoire");const payload={name:iname.trim(),category:icat,brand:ibrand||null,model:imodel||null,serial_number:iserial||null,quantity:Number(iqty)||1,state:istate,location:iloc||null,primary_pole_id:ipole||null,ownership_scope:ipole?"pole":"commun",responsible_member_id:iresp||null,purchase_price:iprice?Number(iprice.replace(",",".")):null,purchase_date:idate||null,notes:inotes||null,created_by:userId};let id=editItem?.id;if(id){const{error}=await db().from("material_items").update(payload).eq("id",id);if(error)throw error}else{const{data,error}=await db().from("material_items").insert(payload).select("id").single();if(error)throw error;id=data.id}if(ipole){await db().from("material_item_poles").upsert({item_id:id,pole_id:ipole},{onConflict:"item_id,pole_id"})}},onSuccess:async()=>{setItemOpen(false);toast.success(editItem?"Matériel mis à jour":"Matériel ajouté");await refresh()},onError:(e:any)=>toast.error(e.message)});

 const [needOpen,setNeedOpen]=useState(false),[editNeed,setEditNeed]=useState<any>(null),[ntitle,setNtitle]=useState(""),[npole,setNpole]=useState(""),[npriority,setNpriority]=useState("normale"),[nhorizon,setNhorizon]=useState("court_terme"),[nqty,setNqty]=useState("1"),[nbudget,setNbudget]=useState(""),[ndesc,setNdesc]=useState(""),[njust,setNjust]=useState(""),[nalt,setNalt]=useState(""),[ndesired,setNdesired]=useState(""),[nprogram,setNprogram]=useState(""),[nurl,setNurl]=useState(""),[nurlLabel,setNurlLabel]=useState("");
 function openNeed(n?:any){setEditNeed(n??null);setNtitle(n?.title??"");setNpole(n?.pole_id??"");setNpriority(n?.priority??"normale");setNhorizon(n?.horizon??"court_terme");setNqty(String(n?.quantity??1));setNbudget(n?.estimated_budget?String(n.estimated_budget):"");setNdesc(n?.description??"");setNjust(n?.justification??"");setNalt(n?.alternative??"");setNdesired(n?.desired_by??"");setNprogram(n?.program_id??"");setNurl("");setNurlLabel("");setNeedOpen(true)}
 const saveNeed=useMutation({mutationFn:async()=>{if(!ntitle.trim()||!npole)throw Error("Titre et pôle obligatoires");const payload={title:ntitle.trim(),pole_id:npole,priority:npriority,horizon:nhorizon,quantity:Number(nqty)||1,estimated_budget:nbudget?Number(nbudget.replace(",",".")):null,description:ndesc||null,justification:njust||null,alternative:nalt||null,desired_by:ndesired||null,program_id:nprogram||null,status:editNeed?.status??"exprime",created_by:userId,created_by_member_id:(members.data?.members??[]).find((m:any)=>m.auth_user_id===userId)?.id??null};let id=editNeed?.id;if(id){const{error}=await db().from("material_needs").update(payload).eq("id",id);if(error)throw error}else{const{data,error}=await db().from("material_needs").insert(payload).select("id").single();if(error)throw error;id=data.id}if(nurl.trim()){const{error}=await db().from("material_need_links").insert({need_id:id,label:nurlLabel||"Lien produit",url:nurl.trim(),created_by:userId});if(error)throw error}},onSuccess:async()=>{setNeedOpen(false);toast.success(editNeed?"Besoin mis à jour":"Besoin matériel enregistré");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const updateNeedStatus=useMutation({mutationFn:async({id,status}:{id:string,status:string})=>{const{error}=await db().from("material_needs").update({status}).eq("id",id);if(error)throw error},onSuccess:refresh,onError:(e:any)=>toast.error(e.message)});

 const [reqOpen,setReqOpen]=useState(false),[rtitle,setRtitle]=useState(""),[rnotes,setRnotes]=useState(""),[selectedNeeds,setSelectedNeeds]=useState<string[]>([]);
 const saveRequest=useMutation({mutationFn:async()=>{if(!rtitle.trim()||!selectedNeeds.length)throw Error("Titre et au moins un besoin obligatoires");const{data,error}=await db().from("material_requests").insert({title:rtitle.trim(),notes:rnotes||null,status:"preparation",created_by:userId}).select("id").single();if(error)throw error;const{error:e2}=await db().from("material_request_needs").insert(selectedNeeds.map(need_id=>({request_id:data.id,need_id})));if(e2)throw e2},onSuccess:async()=>{setReqOpen(false);setRtitle("");setRnotes("");setSelectedNeeds([]);toast.success("Dossier de demande créé");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const updateRequest=useMutation({mutationFn:async({id,status}:{id:string,status:string})=>{const patch:any={status};if(status==="transmise")patch.sent_at=new Date().toISOString();if(["validee","refusee","reportee"].includes(status))patch.decided_at=new Date().toISOString();const{error}=await db().from("material_requests").update(patch).eq("id",id);if(error)throw error},onSuccess:refresh});

 const [incidentOpen,setIncidentOpen]=useState(false),[incItem,setIncItem]=useState(""),[incTitle,setIncTitle]=useState(""),[incDesc,setIncDesc]=useState(""),[incSev,setIncSev]=useState("normale"),[incProg,setIncProg]=useState("");
 const saveIncident=useMutation({mutationFn:async()=>{if(!incItem||!incTitle.trim())throw Error("Matériel et titre obligatoires");const{error}=await db().from("material_incidents").insert({item_id:incItem,title:incTitle.trim(),description:incDesc||null,severity:incSev,program_id:incProg||null,reported_by:userId});if(error)throw error},onSuccess:async()=>{setIncidentOpen(false);toast.success("Incident signalé");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const resolveIncident=useMutation({mutationFn:async(id:string)=>{const{error}=await db().from("material_incidents").update({status:"resolu",resolved_at:new Date().toISOString()}).eq("id",id);if(error)throw error},onSuccess:refresh});

 const [loanOpen,setLoanOpen]=useState(false),[loanItem,setLoanItem]=useState(""),[loanMember,setLoanMember]=useState(""),[loanQty,setLoanQty]=useState("1"),[loanDue,setLoanDue]=useState(""),[loanProg,setLoanProg]=useState("");
 const saveLoan=useMutation({mutationFn:async()=>{if(!loanItem)throw Error("Matériel obligatoire");const{error}=await db().from("material_loans").insert({item_id:loanItem,borrower_member_id:loanMember||null,quantity:Number(loanQty)||1,due_at:loanDue?new Date(loanDue).toISOString():null,program_id:loanProg||null,created_by:userId});if(error)throw error},onSuccess:async()=>{setLoanOpen(false);toast.success("Sortie de matériel enregistrée");await refresh()}});
 const returnLoan=useMutation({mutationFn:async(id:string)=>{const{error}=await db().from("material_loans").update({returned_at:new Date().toISOString()}).eq("id",id);if(error)throw error},onSuccess:refresh});

 const [docOpen,setDocOpen]=useState<any>(null),[docFile,setDocFile]=useState<File|null>(null),[docKind,setDocKind]=useState("devis");
 const uploadDoc=useMutation({mutationFn:async()=>{if(!docOpen||!docFile)throw Error("Choisis un fichier");const path=`${docOpen.type}/${docOpen.id}/${crypto.randomUUID()}-${docFile.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await supabase.storage.from("material-com").upload(path,docFile);if(up.error)throw up.error;const{error}=await db().from("material_documents").insert({entity_type:docOpen.type,entity_id:docOpen.id,file_name:docFile.name,storage_path:path,mime_type:docFile.type,size_bytes:docFile.size,document_kind:docKind,uploaded_by:userId});if(error)throw error},onSuccess:async()=>{setDocOpen(null);setDocFile(null);toast.success("Document ajouté");await refresh()},onError:(e:any)=>toast.error(e.message)});
 async function openDoc(path:string){const{data,error}=await supabase.storage.from("material-com").createSignedUrl(path,120);if(error)return toast.error(error.message);window.open(data.signedUrl,"_blank","noopener,noreferrer")}

 function printRequest(r:any){const ids=(reqNeeds.data??[]).filter((x:any)=>x.request_id===r.id).map((x:any)=>x.need_id);const rows=(needs.data??[]).filter((n:any)=>ids.includes(n.id));const total=rows.reduce((s:any,n:any)=>s+Number(n.estimated_budget||0),0);const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,(c:any)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));const w=window.open("","_blank","noopener,noreferrer");if(!w)return toast.error("Autorise les fenêtres contextuelles pour générer le PDF");w.document.write(`<html><head><title>${esc(r.title)}</title><style>body{font-family:Arial,sans-serif;margin:40px;color:#222}h1{color:#572a86}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #ddd;padding:10px;text-align:left}th{background:#f4eff9}.total{font-size:20px;font-weight:bold;margin-top:20px}.note{margin-top:18px;padding:12px;background:#f7f7f7}@media print{button{display:none}}</style></head><body><h1>${esc(r.title)}</h1><p>Demande de matériel COM · ICC Le Mans</p><p><b>Statut :</b> ${esc(REQ_STATUS[r.status]||r.status)}</p><table><thead><tr><th>Besoin</th><th>Pôle</th><th>Qté</th><th>Priorité</th><th>Estimation</th><th>Justification</th></tr></thead><tbody>${rows.map((n:any)=>`<tr><td>${esc(n.title)}</td><td>${esc(poleName.get(n.pole_id)||"")}</td><td>${n.quantity}</td><td>${esc(PRIORITY[n.priority])}</td><td>${esc(euro(n.estimated_budget))}</td><td>${esc(n.justification||"")}</td></tr>`).join("")}</tbody></table><div class="total">Budget estimatif total : ${esc(euro(total))}</div>${r.notes?`<div class="note"><b>Notes :</b><br>${esc(r.notes)}</div>`:""}<p style="margin-top:40px;font-size:12px;color:#777">Document généré depuis l’application COM ICC Le Mans.</p><button onclick="window.print()">Imprimer / Enregistrer en PDF</button></body></html>`);w.document.close()}

 const activeNeeds=(needs.data??[]).filter((n:any)=>!["recu","refuse"].includes(n.status));
 return <AppShell title="Matériel COM" subtitle="Inventaire, état du parc, besoins, devis, demandes d’acquisition et suivi." actions={<div className="flex gap-2">{canAdmin?<Button asChild size="sm" variant="outline"><Link to="/parametres-materiel"><Settings2 className="size-4"/>Droits & gestionnaires</Link></Button>:null}</div>}>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat n={stats.items} l="Équipements / unités"/><Stat n={stats.repair} l="À réparer / hors service"/><Stat n={stats.needs} l="Besoins ouverts"/><Stat n={stats.critical} l="Besoins critiques"/><Stat n={euro(stats.budget)} l="Budget estimatif ouvert"/></div>
  <div className="mt-4 flex flex-wrap gap-2">{[["inventaire","📦 Inventaire"],["besoins","🧾 Besoins"],["demandes","📑 Demandes & devis"],["suivi","🛠 Suivi / maintenance"]].map(([k,l])=><Button key={k} variant={tab===k?"default":"outline"} onClick={()=>setTab(k)}>{l}</Button>)}</div>

  {tab==="inventaire"?<div className="mt-4 space-y-4"><div className="flex flex-wrap gap-2">{canInv?<Button onClick={()=>openItem()}><Plus className="size-4"/>Ajouter du matériel</Button>:null}<Button variant="outline" onClick={()=>setIncidentOpen(true)}><AlertTriangle className="size-4"/>Signaler un problème</Button>{canLoans?<Button variant="outline" onClick={()=>setLoanOpen(true)}><Hand className="size-4"/>Enregistrer une sortie / prêt</Button>:null}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(items.data??[]).map((x:any)=>{const ps=(itemPoles.data??[]).filter((p:any)=>p.item_id===x.id).map((p:any)=>poleName.get(p.pole_id)).filter(Boolean);return <Card key={x.id}><CardHeader><CardTitle className="flex items-start justify-between gap-3"><span>{x.name}</span><Badge variant="outline">{STATES[x.state]||x.state}</Badge></CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p className="text-muted-foreground">{[x.brand,x.model].filter(Boolean).join(" · ")||x.category}</p><p><b>Quantité :</b> {x.quantity}</p><p><b>Pôle(s) :</b> {ps.join(", ")||poleName.get(x.primary_pole_id)||"Matériel commun COM"}</p><p><b>Rangement :</b> {x.location||"À préciser"}</p><p><b>Responsable :</b> {memberName.get(x.responsible_member_id)||"À préciser"}</p>{x.purchase_price?<p><b>Valeur :</b> {euro(x.purchase_price)}</p>:null}{x.notes?<p className="rounded-lg bg-muted/50 p-2 text-xs">{x.notes}</p>:null}<div className="flex flex-wrap gap-2 pt-1">{canInv?<Button size="sm" variant="outline" onClick={()=>openItem(x)}>Modifier</Button>:null}{canDocs?<Button size="sm" variant="outline" onClick={()=>setDocOpen({type:"item",id:x.id})}><FileText className="size-4"/>Document</Button>:null}</div></CardContent></Card>})}</div>{!(items.data??[]).length?<EmptyState title="Inventaire vide" description="Ajoutez le premier équipement COM."/>:null}</div>:null}

  {tab==="besoins"?<div className="mt-4 space-y-4"><div className="flex flex-wrap gap-2">{canCreateNeed?<Button onClick={()=>openNeed()}><Plus className="size-4"/>Exprimer un besoin matériel</Button>:null}</div>{activeNeeds.length?<div className="space-y-3">{activeNeeds.map((n:any)=>{const nlinks=(links.data??[]).filter((l:any)=>l.need_id===n.id),ndocs=(docs.data??[]).filter((d:any)=>d.entity_type==="need"&&d.entity_id===n.id);return <Card key={n.id}><CardContent className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><Badge>{PRIORITY[n.priority]}</Badge><Badge variant="outline">{HORIZON[n.horizon]}</Badge><Badge variant="secondary">{NEED_STATUS[n.status]}</Badge></div><h3 className="mt-2 text-lg font-black">{n.title}</h3><p className="text-sm text-muted-foreground">{poleName.get(n.pole_id)||"Sans pôle"} · Qté {n.quantity}{n.estimated_budget?` · ${euro(n.estimated_budget)}`:""}</p></div><div className="flex flex-wrap gap-2">{canNeeds?<Button size="sm" variant="outline" onClick={()=>openNeed(n)}>Modifier</Button>:null}{canDocs?<Button size="sm" variant="outline" onClick={()=>setDocOpen({type:"need",id:n.id})}><ReceiptText className="size-4"/>Ajouter devis / fichier</Button>:null}</div></div>{n.description?<p className="mt-3 text-sm">{n.description}</p>:null}{n.justification?<div className="mt-3 rounded-xl bg-violet-50 p-3 text-sm"><b>Pourquoi ce besoin ?</b><p>{n.justification}</p></div>:null}{n.alternative?<p className="mt-2 text-sm"><b>Alternative envisagée :</b> {n.alternative}</p>:null}{nlinks.length?<div className="mt-3 flex flex-wrap gap-2">{nlinks.map((l:any)=><a key={l.id} href={l.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs font-semibold hover:text-icc-violet"><Link2 className="size-3"/>{l.label||"Lien produit"}</a>)}</div>:null}{ndocs.length?<div className="mt-3 flex flex-wrap gap-2">{ndocs.map((d:any)=><Button key={d.id} size="sm" variant="ghost" onClick={()=>openDoc(d.storage_path)}><FileText className="size-4"/>{d.file_name}</Button>)}</div>:null}{canNeeds?<div className="mt-3 flex flex-wrap items-center gap-2"><span className="text-xs font-semibold">Étape :</span><select className="h-9 rounded-md border bg-background px-2 text-xs" value={n.status} onChange={e=>updateNeedStatus.mutate({id:n.id,status:e.target.value})}>{Object.entries(NEED_STATUS).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select></div>:null}</CardContent></Card>})}</div>:<EmptyState title="Aucun besoin matériel ouvert"/>}</div>:null}

  {tab==="demandes"?<div className="mt-4 space-y-4"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm"><b>Budget Église ≠ Caisse fraternelle.</b><p className="mt-1 text-muted-foreground">Les montants ici sont des estimations et demandes d’acquisition adressées aux finances de l’Église. Ils ne modifient jamais la Caisse fraternelle.</p></div>{canReq?<Button onClick={()=>setReqOpen(true)}><Plus className="size-4"/>Créer un dossier de demande</Button>:null}<div className="space-y-3">{(requests.data??[]).map((r:any)=>{const ids=(reqNeeds.data??[]).filter((x:any)=>x.request_id===r.id).map((x:any)=>x.need_id),rows=(needs.data??[]).filter((n:any)=>ids.includes(n.id)),total=rows.reduce((s:any,n:any)=>s+Number(n.estimated_budget||0),0),rDocs=(docs.data??[]).filter((d:any)=>d.entity_type==="request"&&d.entity_id===r.id);return <Card key={r.id}><CardContent className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge>{REQ_STATUS[r.status]||r.status}</Badge><h3 className="mt-2 text-lg font-black">{r.title}</h3><p className="text-sm text-muted-foreground">{rows.length} besoin(s) · Budget estimatif {euro(total)}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>printRequest(r)}><FileDown className="size-4"/>Imprimer / PDF</Button>{canDocs?<Button size="sm" variant="outline" onClick={()=>setDocOpen({type:"request",id:r.id})}><FileText className="size-4"/>Joindre un document</Button>:null}</div></div><div className="mt-3 divide-y rounded-xl border">{rows.map((n:any)=><div key={n.id} className="flex justify-between gap-3 p-3 text-sm"><div><b>{n.title}</b><p className="text-xs text-muted-foreground">{poleName.get(n.pole_id)} · {PRIORITY[n.priority]}</p></div><b>{euro(n.estimated_budget)}</b></div>)}</div>{r.notes?<p className="mt-3 text-sm">{r.notes}</p>:null}{rDocs.length?<div className="mt-3 flex flex-wrap gap-2">{rDocs.map((d:any)=><Button key={d.id} size="sm" variant="ghost" onClick={()=>openDoc(d.storage_path)}><FileText className="size-4"/>{d.file_name}</Button>)}</div>:null}{canReq?<div className="mt-3"><select className="h-9 rounded-md border bg-background px-2 text-xs" value={r.status} onChange={e=>updateRequest.mutate({id:r.id,status:e.target.value})}>{Object.entries(REQ_STATUS).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select></div>:null}</CardContent></Card>})}</div>{!(requests.data??[]).length?<EmptyState title="Aucun dossier de demande" description="Regroupez plusieurs besoins dans une demande claire à transmettre aux finances de l’Église."/>:null}</div>:null}

  {tab==="suivi"?<div className="mt-4 space-y-4"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Wrench className="size-5"/>Incidents & maintenance</CardTitle></CardHeader><CardContent className="space-y-2">{(incidents.data??[]).map((x:any)=><div key={x.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><div><b>{x.title}</b><p className="text-xs text-muted-foreground">{itemName.get(x.item_id)||"Matériel"} · {PRIORITY[x.severity]}</p></div><Badge variant={x.status==="resolu"?"secondary":"destructive"}>{x.status==="resolu"?"Résolu":x.status==="en_cours"?"En cours":"Ouvert"}</Badge></div>{x.description?<p className="mt-2 text-sm">{x.description}</p>:null}{canInv&&x.status!=="resolu"?<Button size="sm" className="mt-2" onClick={()=>resolveIncident.mutate(x.id)}>Marquer résolu</Button>:null}</div>)}{!(incidents.data??[]).length?<EmptyState title="Aucun incident"/>:null}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><PackageCheck className="size-5"/>Sorties / prêts</CardTitle></CardHeader><CardContent className="space-y-2">{(loans.data??[]).map((x:any)=><div key={x.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><div><b>{itemName.get(x.item_id)||"Matériel"}</b><p className="text-xs text-muted-foreground">Qté {x.quantity} · {memberName.get(x.borrower_member_id)||"Sortie COM"}</p></div><Badge variant={x.returned_at?"secondary":"outline"}>{x.returned_at?"Rendu":"En sortie"}</Badge></div>{x.due_at&&!x.returned_at?<p className="mt-1 text-xs">Retour prévu : {new Date(x.due_at).toLocaleString("fr-FR")}</p>:null}{canLoans&&!x.returned_at?<Button size="sm" className="mt-2" onClick={()=>returnLoan.mutate(x.id)}>Enregistrer le retour</Button>:null}</div>)}{!(loans.data??[]).length?<EmptyState title="Aucune sortie de matériel"/>:null}</CardContent></Card></div><Card><CardHeader><CardTitle>Lecture du parc</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-muted/50 p-4"><b>{stats.repair}</b><p className="text-xs text-muted-foreground">équipement(s) à réparer / hors service</p></div><div className="rounded-xl bg-muted/50 p-4"><b>{stats.incidents}</b><p className="text-xs text-muted-foreground">incident(s) ouvert(s)</p></div><div className="rounded-xl bg-muted/50 p-4"><b>{(loans.data??[]).filter((x:any)=>!x.returned_at).length}</b><p className="text-xs text-muted-foreground">sortie(s) en cours</p></div></CardContent></Card></div>:null}

  <Dialog open={itemOpen} onOpenChange={setItemOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{editItem?"Modifier le matériel":"Ajouter du matériel"}</DialogTitle></DialogHeader><F l="Nom *"><Input value={iname} onChange={e=>setIname(e.target.value)}/></F><div className="grid gap-3 sm:grid-cols-2"><F l="Catégorie"><Input value={icat} onChange={e=>setIcat(e.target.value)} placeholder="Caméra, son, câblage…"/></F><F l="État"><select className="h-10 w-full rounded-md border bg-background px-3" value={istate} onChange={e=>setIstate(e.target.value)}>{Object.entries(STATES).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select></F><F l="Marque"><Input value={ibrand} onChange={e=>setIbrand(e.target.value)}/></F><F l="Modèle"><Input value={imodel} onChange={e=>setImodel(e.target.value)}/></F><F l="N° série / référence"><Input value={iserial} onChange={e=>setIserial(e.target.value)}/></F><F l="Quantité"><Input type="number" min={0} value={iqty} onChange={e=>setIqty(e.target.value)}/></F><F l="Pôle principal"><select className="h-10 w-full rounded-md border bg-background px-3" value={ipole} onChange={e=>setIpole(e.target.value)}><option value="">Matériel commun COM</option>{(poles.data??[]).filter((p:any)=>!p.archived).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></F><F l="Lieu de rangement"><Input value={iloc} onChange={e=>setIloc(e.target.value)}/></F><F l="Responsable matériel"><select className="h-10 w-full rounded-md border bg-background px-3" value={iresp} onChange={e=>setIresp(e.target.value)}><option value="">À préciser</option>{(members.data?.members??[]).filter((m:any)=>m.status==="active").map((m:any)=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></F><F l="Valeur / prix d’achat"><Input value={iprice} onChange={e=>setIprice(e.target.value)}/></F><F l="Date d’acquisition"><Input type="date" value={idate} onChange={e=>setIdate(e.target.value)}/></F></div><F l="Notes"><Textarea value={inotes} onChange={e=>setInotes(e.target.value)}/></F><DialogFooter><Button onClick={()=>saveItem.mutate()}>{editItem?"Enregistrer":"Ajouter"}</Button></DialogFooter></DialogContent></Dialog>

  <Dialog open={needOpen} onOpenChange={setNeedOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{editNeed?"Modifier le besoin":"Exprimer un besoin matériel"}</DialogTitle></DialogHeader><F l="Besoin *"><Input value={ntitle} onChange={e=>setNtitle(e.target.value)} placeholder="2 micros HF supplémentaires"/></F><div className="grid gap-3 sm:grid-cols-2"><F l="Pôle *"><select className="h-10 w-full rounded-md border bg-background px-3" value={npole} onChange={e=>setNpole(e.target.value)}><option value="">Choisir</option>{(poles.data??[]).filter((p:any)=>!p.archived).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></F><F l="Priorité"><select className="h-10 w-full rounded-md border bg-background px-3" value={npriority} onChange={e=>setNpriority(e.target.value)}>{Object.entries(PRIORITY).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select></F><F l="Horizon"><select className="h-10 w-full rounded-md border bg-background px-3" value={nhorizon} onChange={e=>setNhorizon(e.target.value)}>{Object.entries(HORIZON).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select></F><F l="Quantité"><Input type="number" min={1} value={nqty} onChange={e=>setNqty(e.target.value)}/></F><F l="Budget estimatif"><Input value={nbudget} onChange={e=>setNbudget(e.target.value)} placeholder="800"/></F><F l="Date souhaitée"><Input type="date" value={ndesired} onChange={e=>setNdesired(e.target.value)}/></F><F l="Programme lié (facultatif)"><select className="h-10 w-full rounded-md border bg-background px-3" value={nprogram} onChange={e=>setNprogram(e.target.value)}><option value="">Aucun</option>{(programs.data??[]).filter((p:any)=>!p.archived).slice(0,100).map((p:any)=><option key={p.id} value={p.id}>{p.title} · {p.start_date}</option>)}</select></F></div><F l="Description"><Textarea value={ndesc} onChange={e=>setNdesc(e.target.value)}/></F><F l="Justification / manque constaté"><Textarea value={njust} onChange={e=>setNjust(e.target.value)} placeholder="Pourquoi est-ce nécessaire ? Quel problème cela résout ?"/></F><F l="Alternative possible"><Textarea value={nalt} onChange={e=>setNalt(e.target.value)} placeholder="Option moins chère, location, matériel équivalent…"/></F><div className="grid gap-3 sm:grid-cols-2"><F l="Lien produit"><Input value={nurl} onChange={e=>setNurl(e.target.value)} placeholder="https://…"/></F><F l="Nom du lien"><Input value={nurlLabel} onChange={e=>setNurlLabel(e.target.value)} placeholder="Thomann · modèle X"/></F></div><DialogFooter><Button onClick={()=>saveNeed.mutate()}>{editNeed?"Enregistrer":"Créer le besoin"}</Button></DialogFooter></DialogContent></Dialog>

  <Dialog open={reqOpen} onOpenChange={setReqOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Créer un dossier de demande</DialogTitle></DialogHeader><F l="Titre"><Input value={rtitle} onChange={e=>setRtitle(e.target.value)} placeholder="Demande matériel COM — Septembre 2026"/></F><F l="Besoins à regrouper"><div className="space-y-2 rounded-xl border p-3">{activeNeeds.map((n:any)=><label key={n.id} className="flex cursor-pointer items-center gap-3 text-sm"><input type="checkbox" checked={selectedNeeds.includes(n.id)} onChange={e=>setSelectedNeeds(v=>e.target.checked?[...v,n.id]:v.filter(id=>id!==n.id))}/><span className="flex-1"><b>{n.title}</b><small className="block text-muted-foreground">{poleName.get(n.pole_id)} · {euro(n.estimated_budget)}</small></span></label>)}</div></F><F l="Note de présentation"><Textarea value={rnotes} onChange={e=>setRnotes(e.target.value)}/></F><DialogFooter><Button onClick={()=>saveRequest.mutate()}>Créer le dossier</Button></DialogFooter></DialogContent></Dialog>

  <Dialog open={incidentOpen} onOpenChange={setIncidentOpen}><DialogContent><DialogHeader><DialogTitle>Signaler un problème matériel</DialogTitle></DialogHeader><F l="Matériel"><select className="h-10 w-full rounded-md border bg-background px-3" value={incItem} onChange={e=>setIncItem(e.target.value)}><option value="">Choisir</option>{(items.data??[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></F><F l="Problème"><Input value={incTitle} onChange={e=>setIncTitle(e.target.value)} placeholder="Le micro grésille"/></F><F l="Gravité"><select className="h-10 w-full rounded-md border bg-background px-3" value={incSev} onChange={e=>setIncSev(e.target.value)}>{Object.entries(PRIORITY).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select></F><F l="Programme concerné"><select className="h-10 w-full rounded-md border bg-background px-3" value={incProg} onChange={e=>setIncProg(e.target.value)}><option value="">Aucun</option>{(programs.data??[]).filter((p:any)=>!p.archived).slice(0,100).map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></F><F l="Détails"><Textarea value={incDesc} onChange={e=>setIncDesc(e.target.value)}/></F><DialogFooter><Button onClick={()=>saveIncident.mutate()}>Signaler</Button></DialogFooter></DialogContent></Dialog>

  <Dialog open={loanOpen} onOpenChange={setLoanOpen}><DialogContent><DialogHeader><DialogTitle>Sortie / prêt de matériel</DialogTitle></DialogHeader><F l="Matériel"><select className="h-10 w-full rounded-md border bg-background px-3" value={loanItem} onChange={e=>setLoanItem(e.target.value)}><option value="">Choisir</option>{(items.data??[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></F><F l="Quantité"><Input type="number" min={1} value={loanQty} onChange={e=>setLoanQty(e.target.value)}/></F><F l="Pris par"><select className="h-10 w-full rounded-md border bg-background px-3" value={loanMember} onChange={e=>setLoanMember(e.target.value)}><option value="">Sortie COM</option>{(members.data?.members??[]).filter((m:any)=>m.status==="active").map((m:any)=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></F><F l="Programme"><select className="h-10 w-full rounded-md border bg-background px-3" value={loanProg} onChange={e=>setLoanProg(e.target.value)}><option value="">Aucun</option>{(programs.data??[]).filter((p:any)=>!p.archived).slice(0,100).map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></F><F l="Retour prévu"><Input type="datetime-local" value={loanDue} onChange={e=>setLoanDue(e.target.value)}/></F><DialogFooter><Button onClick={()=>saveLoan.mutate()}>Enregistrer la sortie</Button></DialogFooter></DialogContent></Dialog>

  <Dialog open={!!docOpen} onOpenChange={o=>!o&&setDocOpen(null)}><DialogContent><DialogHeader><DialogTitle>Ajouter un fichier</DialogTitle></DialogHeader><F l="Type"><select className="h-10 w-full rounded-md border bg-background px-3" value={docKind} onChange={e=>setDocKind(e.target.value)}><option value="devis">Devis</option><option value="facture">Facture</option><option value="photo">Photo</option><option value="fiche_technique">Fiche technique</option><option value="autre">Autre</option></select></F><F l="Fichier"><Input type="file" accept="image/*,.pdf,.docx,.xlsx" onChange={e=>setDocFile(e.target.files?.[0]??null)}/></F><DialogFooter><Button onClick={()=>uploadDoc.mutate()}>Ajouter le fichier</Button></DialogFooter></DialogContent></Dialog>
 </AppShell>
}
function F({l,children}:any){return <div className="space-y-1"><Label>{l}</Label>{children}</div>}
function Stat({n,l}:{n:any;l:string}){return <Card><CardContent className="p-4"><b className="text-2xl text-icc-violet">{n}</b><p className="text-xs text-muted-foreground">{l}</p></CardContent></Card>}
