import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useCurrentRole } from "@/hooks/useAuth";
import { programsQuery, solicitationsQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/mes-demandes")({component:Page});
const today=()=>new Date().toISOString().slice(0,10);
function Page(){
 const {member,isStaff}=useCurrentRole(),programs=useQuery(programsQuery),sols=useQuery(solicitationsQuery),qc=useQueryClient();
 const [nature,setNature]=useState<"replacement"|"reinforcement">("replacement"),[programId,setProgramId]=useState(""),[deadline,setDeadline]=useState(""),[message,setMessage]=useState("");
 const future=useMemo(()=>(programs.data??[]).filter((p:any)=>!p.archived&&!p.deleted&&p.status!=="cancelled"&&p.start_date>=today()),[programs.data]);
 const assignedIds=useMemo(()=>new Set(future.filter((p:any)=>p.assignments?.some((a:any)=>a.memberIds?.includes(member?.id))).map((p:any)=>p.id)),[future,member?.id]);
 const selectable=nature==="replacement"?future.filter((p:any)=>assignedIds.has(p.id)):future;
 const mine=(sols.data??[]).filter((s:any)=>s.requester_member_id===member?.id&&!s.archived).sort((a:any,b:any)=>String(b.created_at??b.event_date).localeCompare(String(a.created_at??a.event_date)));
 const send=useMutation({mutationFn:async()=>{if(!programId)throw Error("Choisis un programme.");const p:any=future.find((x:any)=>x.id===programId);if(!p)throw Error("Programme introuvable.");const d=deadline||p.response_deadline||p.start_date;if(d<today()||d>p.start_date)throw Error("La date limite doit être comprise entre aujourd’hui et la date du programme.");const{data,error}=await (supabase as any).rpc("submit_member_solicitation_request",{p_nature:nature,p_program_id:programId,p_response_deadline:d,p_message:message.trim()||null});if(error)throw Error(error.message);return data},onSuccess:async()=>{toast.success(nature==="replacement"?"Demande de remplacement envoyée à ton/tes référents":"Demande de renfort envoyée à ton/tes référents");setProgramId("");setDeadline("");setMessage("");await qc.invalidateQueries({queryKey:["solicitations"]})},onError:(e:Error)=>toast.error(e.message)});
 return <AppShell title="Mes demandes de remplacement / renfort" subtitle="Un équipier peut signaler directement un besoin. Le ou les référents concernés prennent ensuite le relais pour organiser la solution.">
  <div className="mb-4 rounded-2xl border border-violet-200 bg-violet-50/60 p-4 text-sm"><b className="text-icc-violet">Comment ça fonctionne ?</b><p className="mt-1 text-muted-foreground">« Remplacement » concerne un programme sur lequel tu es déjà affecté(e). « Renfort » permet de signaler qu’un soutien supplémentaire semble nécessaire. La demande est transmise aux référents de ton/tes pôles ; elle ne modifie pas directement le planning.</p>{isStaff?<p className="mt-2"><Link to="/sollicitations" className="font-bold text-icc-violet">Ouvrir la gestion complète des sollicitations →</Link></p>:null}</div>
  <div className="grid gap-4 lg:grid-cols-[420px_1fr]"><Card><CardHeader><CardTitle>Nouvelle demande</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Type de besoin</Label><Select value={nature} onValueChange={(v:any)=>{setNature(v);setProgramId("")}}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="replacement">Je cherche un remplacement</SelectItem><SelectItem value="reinforcement">Je demande du renfort</SelectItem></SelectContent></Select></div><div><Label>Programme concerné</Label><Select value={programId||undefined} onValueChange={v=>{setProgramId(v);const p:any=future.find((x:any)=>x.id===v);setDeadline(p?.response_deadline??p?.start_date??"")}}><SelectTrigger className="mt-1"><SelectValue placeholder={nature==="replacement"?"Mes programmes à venir":"Choisir un programme"}/></SelectTrigger><SelectContent>{selectable.map((p:any)=><SelectItem key={p.id} value={p.id}>{p.title} · {new Date(`${p.start_date}T12:00:00`).toLocaleDateString("fr-FR")}</SelectItem>)}</SelectContent></Select>{nature==="replacement"&&!selectable.length?<p className="mt-1 text-xs text-muted-foreground">Aucun programme futur ne te concerne actuellement.</p>:null}</div><div><Label>Date limite souhaitée</Label><Input className="mt-1" type="date" min={today()} value={deadline} onChange={e=>setDeadline(e.target.value)}/></div><div><Label>Précisions</Label><Textarea className="mt-1" rows={4} placeholder={nature==="replacement"?"Explique brièvement pourquoi tu as besoin d’être remplacé(e)…":"Explique le besoin de renfort…"} value={message} onChange={e=>setMessage(e.target.value)}/></div><Button className="w-full" disabled={send.isPending||!programId} onClick={()=>send.mutate()}>{send.isPending?"Envoi en cours…":"Envoyer la demande"}</Button></CardContent></Card><Card><CardHeader><CardTitle>Mes demandes récentes</CardTitle></CardHeader><CardContent className="space-y-2">{mine.length?mine.slice(0,20).map((s:any)=><div key={s.id} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><b>{s.event_name}</b><span className="text-xs font-bold text-icc-violet">{s.nature==="replacement"?"Remplacement":"Renfort"}</span></div><p className="mt-1 text-xs text-muted-foreground">Statut : {s.status==="pending"?"En attente de prise en charge":s.status}</p>{s.message?<p className="mt-2 text-sm">{s.message}</p>:null}</div>):<p className="text-sm text-muted-foreground">Aucune demande pour le moment.</p>}</CardContent></Card></div>
 </AppShell>
}
