import {createFileRoute} from "@tanstack/react-router";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {toast} from "sonner";
import {AppShell} from "@/components/AppShell";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {supabase} from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/parametres-vie-equipe")({head:()=>({meta:[{title:"Paramètres Vie d’équipe — COM ICC Le Mans"}]}),component:Page});
const db=()=>supabase as any;const ROLES=[['equipier','Équipier'],['referent','Référent'],['direction','Direction']] as const;const ACTIONS=[['consulter','Consulter Vie d’équipe'],['proposer','Faire une proposition'],['participer','Répondre à un événement'],['voter','Voter à un sondage'],['organiser','Organiser / créer un sondage'],['valider','Valider et planifier un événement']] as const;const SCOPES=[['interdit','Interdit'],['moi','Moi'],['mon_pole','Mon pôle'],['tous','Tous']] as const;
function Page(){const qc=useQueryClient();const q=useQuery({queryKey:['team-life-rights'],queryFn:async()=>{const{data,error}=await db().from('access_role_permissions').select('*').eq('module_key','vie_equipe');if(error)throw error;return data??[]}});const save=useMutation({mutationFn:async({role,action,scope}:{role:string;action:string;scope:string})=>{const{error}=await db().from('access_role_permissions').upsert({role_key:role,module_key:'vie_equipe',action_key:action,scope,enabled:scope!=='interdit',updated_at:new Date().toISOString()},{onConflict:'role_key,module_key,action_key'});if(error)throw error},onSuccess:async()=>{toast.success('Droit mis à jour');await qc.invalidateQueries({queryKey:['team-life-rights']})},onError:(e:any)=>toast.error(e.message)});const current=(role:string,action:string)=>(q.data??[]).find((r:any)=>r.role_key===role&&r.action_key===action)?.scope??'interdit';return <AppShell title="Paramètres Vie d’équipe" subtitle="Les droits sont configurables indépendamment des intitulés de fonction."><Card><CardHeader><CardTitle>Droits Vie d’équipe</CardTitle><p className="text-sm text-muted-foreground">Les équipiers peuvent participer sans que cela n’alimente les statistiques opérationnelles. Les niveaux d’organisation/validation restent ajustables ici.</p></CardHeader><CardContent className="space-y-5">{ROLES.map(([role,label])=><div key={role} className="rounded-2xl border p-4"><h3 className="font-black text-icc-violet">{label}</h3><div className="mt-3 space-y-2">{ACTIONS.map(([action,al])=><div key={action} className="grid gap-2 rounded-xl bg-muted/30 p-3 md:grid-cols-[1fr_220px] md:items-center"><b className="text-sm">{al}</b><select className="h-10 rounded-md border bg-background px-3 text-sm" value={current(role,action)} onChange={e=>save.mutate({role,action,scope:e.target.value})}>{SCOPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>)}</div></div>)}</CardContent></Card><div className="mt-4"><Button variant="outline" onClick={()=>history.back()}>Retour</Button></div></AppShell>}
