import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Building2, Home, Save, ShieldCheck, SlidersHorizontal, Users } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { membersQuery, polesQuery, settingsQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/_authenticated/parametres")({ head: () => ({ meta: [{ title: "Paramètres — COM ICC Le Mans" }] }), component: Parametres });
type Verse={ref:string;text:string}; type DirectionStructure="responsable_adjoint"|"responsable_general_grands_groupes";
const DEFAULT_VERSES:Verse[]=[{ref:"Matthieu 6:33",text:"« Cherchez premièrement le royaume et la justice de Dieu; et toutes ces choses vous seront données par-dessus. »"},{ref:"Hébreux 6:10",text:"« Car Dieu n’est pas injuste, pour oublier votre travail et l’amour que vous avez montré pour son nom, ayant rendu et rendant encore des services aux saints. »"}];

function Parametres(){
 const qc=useQueryClient(),settings=useQuery(settingsQuery),members=useQuery(membersQuery),poles=useQuery(polesQuery); const raw=settings.data as any;
 const [homeTitle,setHomeTitle]=useState(""),[brand,setBrand]=useState(""),[subtitle,setSubtitle]=useState(""),[iconUrl,setIconUrl]=useState(""),[coverUrl,setCoverUrl]=useState(""),[coverEnabled,setCoverEnabled]=useState(true),[verses,setVerses]=useState<Verse[]>(DEFAULT_VERSES);
 const [structure,setStructure]=useState<DirectionStructure>("responsable_adjoint"),[responsable,setResponsable]=useState(""),[adjoint,setAdjoint]=useState(""),[commLead,setCommLead]=useState(""),[avLead,setAvLead]=useState("");
 const [referents,setReferents]=useState<Record<string,string>>({});
 useEffect(()=>{const s=settings.data as any;if(!s)return;setHomeTitle(s.home_title??"COM ICC Le Mans");setBrand(s.brand??"LE MANS");setSubtitle(s.subtitle??"Communication • Organisation • Service");setIconUrl(s.icon_url??"");setCoverUrl(s.cover_url??"");setCoverEnabled(s.cover_enabled??true);const st=Array.isArray(s.verses)?s.verses:[];setVerses([0,1].map(i=>({ref:st[i]?.ref??DEFAULT_VERSES[i].ref,text:st[i]?.text??DEFAULT_VERSES[i].text})));setStructure(s.direction_structure??"responsable_adjoint");setResponsable(s.supervisor_member_id??"");setAdjoint(s.adjoint_member_id??"");setCommLead(s.group_leads?.communication??"");setAvLead(s.group_leads?.audiovisuel??"");},[settings.data]);
 useEffect(()=>{if(!members.data)return;const next:Record<string,string>={};for(const l of members.data.links??[])if(l.is_referent)next[l.pole_id]=l.member_id;setReferents(next);},[members.data]);
 const activeMembers=useMemo(()=>(members.data?.members??[]).filter(m=>m.status==="active"),[members.data]); const activePoles=useMemo(()=>(poles.data??[]).filter(p=>!p.archived),[poles.data]);
 const saveIdentity=useMutation({mutationFn:async()=>{const{error}=await supabase.from("app_settings").upsert({id:"main",home_title:homeTitle.trim()||"COM ICC Le Mans",brand:brand.trim()||"LE MANS",subtitle:subtitle.trim()||null,icon_url:iconUrl.trim()||null,cover_url:coverUrl.trim()||null,cover_enabled:coverEnabled,verses,updated_at:new Date().toISOString()});if(error)throw Error(error.message)},onSuccess:()=>{qc.invalidateQueries({queryKey:["app-settings"]});toast.success("Identité et accueil enregistrés")},onError:(e:Error)=>toast.error("Enregistrement impossible",{description:e.message})});
 const saveDirection=useMutation({mutationFn:async()=>{if(!responsable)throw Error("Sélectionnez le responsable de la structure.");const group_leads=structure==="responsable_general_grands_groupes"?{communication:commLead||null,audiovisuel:avLead||null}:{};const{error}=await supabase.from("app_settings").update({direction_structure:structure,supervisor_member_id:responsable||null,adjoint_member_id:structure==="responsable_adjoint"?(adjoint||null):null,grands_groupes_member_id:null,group_leads,updated_at:new Date().toISOString()} as any).eq("id","main");if(error)throw Error(error.message)},onSuccess:()=>{qc.invalidateQueries({queryKey:["app-settings"]});toast.success("Structure et direction enregistrées")},onError:(e:Error)=>toast.error("Enregistrement impossible",{description:e.message})});
 const saveReferents=useMutation({mutationFn:async()=>{for(const p of activePoles){const links=(members.data?.links??[]).filter(l=>l.pole_id===p.id);const current=links.filter(l=>l.is_referent);if(current.length){const{error}=await supabase.from("member_poles").update({is_referent:false}).in("id",current.map(l=>l.id));if(error)throw Error(error.message)}const memberId=referents[p.id];if(!memberId)continue;const existing=links.find(l=>l.member_id===memberId);if(existing){const{error}=await supabase.from("member_poles").update({is_referent:true}).eq("id",existing.id);if(error)throw Error(error.message)}else{const{error}=await supabase.from("member_poles").insert({member_id:memberId,pole_id:p.id,is_referent:true});if(error)throw Error(error.message)}}},onSuccess:()=>{qc.invalidateQueries({queryKey:["members"]});toast.success("Référents enregistrés")},onError:(e:Error)=>toast.error("Enregistrement impossible",{description:e.message})});
 const select=(label:string,value:string,set:(v:string)=>void)=><Field label={label}><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={value} onChange={e=>set(e.target.value)}><option value="">Non défini</option>{activeMembers.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></Field>;
 return <AppShell title="Paramètres" subtitle="Configuration générale de l’espace COM ICC Le Mans"><Tabs defaultValue="identite" className="space-y-5"><TabsList className="h-auto flex-wrap justify-start gap-1 bg-muted/70 p-1.5"><TabsTrigger value="identite" className="gap-2"><Home className="size-4"/>Identité & accueil</TabsTrigger><TabsTrigger value="organisation" className="gap-2"><Users className="size-4"/>Organisation</TabsTrigger><TabsTrigger value="droits" className="gap-2"><ShieldCheck className="size-4"/>Accès & droits</TabsTrigger><TabsTrigger value="menus" className="gap-2"><SlidersHorizontal className="size-4"/>Menus & modules</TabsTrigger><TabsTrigger value="technique" className="gap-2"><Building2 className="size-4"/>Administration technique</TabsTrigger></TabsList>
 <TabsContent value="identite" className="space-y-4"><Card><CardHeader><CardTitle>Identité de l’espace</CardTitle><CardDescription>Ces informations alimentent l’en-tête et l’accueil.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Nom de l’application"><Input value={homeTitle} onChange={e=>setHomeTitle(e.target.value)}/></Field><Field label="Marque / localisation"><Input value={brand} onChange={e=>setBrand(e.target.value)}/></Field><Field label="Sous-titre"><Input value={subtitle} onChange={e=>setSubtitle(e.target.value)}/></Field><Field label="Logo / icône (URL)"><Input value={iconUrl} onChange={e=>setIconUrl(e.target.value)}/></Field></CardContent></Card><Card><CardHeader><CardTitle>Accueil</CardTitle><CardDescription>Couverture et deux versets affichés sur la page d’accueil.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold">Afficher la couverture</p></div><Switch checked={coverEnabled} onCheckedChange={setCoverEnabled}/></div><Field label="Image de couverture (URL)"><Input value={coverUrl} onChange={e=>setCoverUrl(e.target.value)}/></Field><div className="grid gap-4 lg:grid-cols-2">{verses.map((v,i)=><div key={i} className="space-y-3 rounded-xl border p-4"><p className="font-bold text-icc-violet">Verset {i+1}</p><Field label="Référence"><Input value={v.ref} onChange={e=>setVerses(x=>x.map((z,j)=>j===i?{...z,ref:e.target.value}:z))}/></Field><Field label="Texte"><Textarea rows={4} value={v.text} onChange={e=>setVerses(x=>x.map((z,j)=>j===i?{...z,text:e.target.value}:z))}/></Field></div>)}</div><Button onClick={()=>saveIdentity.mutate()} disabled={saveIdentity.isPending}><Save className="size-4"/>Enregistrer Identité & accueil</Button></CardContent></Card></TabsContent>
 <TabsContent value="organisation" className="space-y-4"><Card><CardHeader><CardTitle>Direction</CardTitle><CardDescription>Préparez les changements puis enregistrez-les. Rien n’est appliqué avant validation.</CardDescription></CardHeader><CardContent className="space-y-5"><Field label="Structure de direction"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={structure} onChange={e=>setStructure(e.target.value as DirectionStructure)}><option value="responsable_adjoint">Responsable + Adjoint + Référents</option><option value="responsable_general_grands_groupes">Responsable général + 2 Responsables Grands Groupes + Référents</option></select></Field><div className="grid gap-4 md:grid-cols-2">{select(structure==="responsable_adjoint"?"Responsable":"Responsable général",responsable,setResponsable)}{structure==="responsable_adjoint"?select("Adjoint",adjoint,setAdjoint):<>{select("Responsable Communication / Média",commLead,setCommLead)}{select("Responsable Audiovisuel",avLead,setAvLead)}</>}</div><p className="text-sm text-muted-foreground">Les fonctions de direction sont pilotées ici. Elles ne sont pas des rôles fixes du trombinoscope. Admin technique reste un droit séparé.</p><Button onClick={()=>saveDirection.mutate()} disabled={saveDirection.isPending}><Save className="size-4"/>{saveDirection.isPending?"Enregistrement…":"Enregistrer la structure & direction"}</Button></CardContent></Card>
 <Card><CardHeader><CardTitle>Référents par pôle</CardTitle><CardDescription>Préparez tous les changements de référents puis validez-les ensemble.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2">{activePoles.map(p=><div key={p.id} className="rounded-xl border p-4"><Label className="mb-2 block font-bold">{p.name}</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={referents[p.id]??""} onChange={e=>setReferents(r=>({...r,[p.id]:e.target.value}))}><option value="">Aucun référent</option>{activeMembers.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></div>)}</div><Button onClick={()=>saveReferents.mutate()} disabled={saveReferents.isPending}><Save className="size-4"/>{saveReferents.isPending?"Enregistrement…":"Enregistrer les référents"}</Button></CardContent></Card></TabsContent>
 <TabsContent value="droits"><ComingSoon title="Accès & droits" text="La matrice Moi / Mon pôle / Tous / Interdit sera consolidée ici."/></TabsContent><TabsContent value="menus"><ComingSoon title="Menus & modules" text="Une seule configuration canonique de visibilité et d’organisation des modules sera installée ici."/></TabsContent><TabsContent value="technique"><ComingSoon title="Administration technique" text="Cet espace sera réservé aux administrateurs techniques."/></TabsContent></Tabs></AppShell>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function ComingSoon({title,text}:{title:string;text:string}){return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{text}</CardDescription></CardHeader><CardContent><p className="text-sm text-muted-foreground">Cette section sera activée après validation de sa logique.</p></CardContent></Card>}
