import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { Crown, Save, ShieldCheck, UserRoundCog } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { membersQuery } from "@/lib/icc";

export const Route=createFileRoute("/_authenticated/parametres-materiel")({head:()=>({meta:[{title:"Paramètres Matériel — COM ICC Le Mans"}]}),component:Page});
const db=()=>supabase as any;
const ROLES=[["equipier","Équipier"],["referent","Référent"],["direction","Direction"]] as const;
const SCOPES=[["interdit","Interdit"],["moi","Moi"],["mon_pole","Mon pôle"],["tous","Tous"]] as const;
const ACTIONS=[["consulter","Consulter le parc et les besoins"],["signaler_incident","Signaler un incident matériel"],["creer_besoin","Exprimer un besoin matériel"],["gerer_inventaire","Créer et modifier l’inventaire"],["gerer_besoins","Gérer les besoins et leur avancement"],["gerer_demandes","Créer et suivre les demandes aux finances de l’Église"],["voir_documents","Voir et joindre devis / fichiers"],["gerer_prets","Gérer les sorties et retours de matériel"],["administrer","Administrer le module et ses gestionnaires"]] as const;
type Role=typeof ROLES[number][0];type Scope=typeof SCOPES[number][0];type Row={id?:string;role_key:Role;module_key:string;action_key:string;scope:Scope;enabled:boolean};
function Page(){const qc=useQueryClient(),members=useQuery(membersQuery);const rows=useQuery({queryKey:["material-rights"],queryFn:async()=>{const{data,error}=await db().from("access_role_permissions").select("*").eq("module_key","materiel_com");if(error)throw error;return(data??[]) as Row[]}}),managers=useQuery({queryKey:["material-managers-settings"],queryFn:async()=>{const{data,error}=await db().from("material_managers").select("*").order("granted_at");if(error)throw error;return data??[]}});const[role,setRole]=useState<Role>("equipier"),[draft,setDraft]=useState<Record<string,Row>>({}),[memberId,setMemberId]=useState("");useEffect(()=>{const n:Record<string,Row>={};for(const r of rows.data??[])n[`${r.role_key}|${r.action_key}`]=r;setDraft(n)},[rows.data]);const active=useMemo(()=>(members.data?.members??[]).filter((m:any)=>m.status==="active"&&!m.archived),[members.data]);const ids=new Set((managers.data??[]).filter((x:any)=>x.active).map((x:any)=>x.member_id));const name=(id:string)=>active.find((m:any)=>m.id===id)?.full_name??"Membre";function get(a:string):Row{return draft[`${role}|${a}`]??{role_key:role,module_key:"materiel_com",action_key:a,scope:"interdit",enabled:false}}function set(a:string,s:Scope){const r=get(a);setDraft(d=>({...d,[`${role}|${a}`]:{...r,scope:s,enabled:s!=="interdit"}}))}const save=useMutation({mutationFn:async()=>{const{error}=await db().from("access_role_permissions").upsert(Object.values(draft).map(({id,...r})=>({...r,module_key:"materiel_com",updated_at:new Date().toISOString()})),{onConflict:"role_key,module_key,action_key"});if(error)throw error},onSuccess:async()=>{toast.success("Droits Matériel enregistrés");await qc.invalidateQueries({queryKey:["material-rights"]})},onError:(e:any)=>toast.error(e.message)});const add=useMutation({mutationFn:async()=>{if(!memberId)throw Error("Choisis un membre");const{data:{user}}=await supabase.auth.getUser();const{error}=await db().from("material_managers").upsert({member_id:memberId,active:true,granted_by:user?.id??null,granted_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"member_id"});if(error)throw error},onSuccess:async()=>{setMemberId("");toast.success("Gestionnaire matériel ajouté");await qc.invalidateQueries({queryKey:["material-managers-settings"]})},onError:(e:any)=>toast.error(e.message)});const remove=useMutation({mutationFn:async(id:string)=>{const{error}=await db().from("material_managers").update({active:false,updated_at:new Date().toISOString()}).eq("member_id",id);if(error)throw error},onSuccess:async()=>{toast.success("Gestionnaire retiré");await qc.invalidateQueries({queryKey:["material-managers-settings"]})}});
return <AppShell title="Paramètres Matériel" subtitle="Rôle de base + responsabilité complémentaire de gestionnaire matériel."><Card><CardHeader><CardTitle className="flex items-center gap-2"><Crown className="size-5"/>Accès de secours</CardTitle><CardDescription>L’Admin technique conserve volontairement l’accès total au module Matériel COM, indépendamment de son rôle métier.</CardDescription></CardHeader><CardContent><Badge>Admin technique · accès total permanent</Badge></CardContent></Card><Card className="mt-4"><CardHeader><CardTitle className="flex items-center gap-2"><UserRoundCog className="size-5"/>Gestionnaires matériel</CardTitle><CardDescription>Une personne peut rester Équipier ou Référent tout en recevant la gestion complète du parc matériel.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 md:grid-cols-[1fr_auto]"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Choisir un membre</option>{active.filter((m:any)=>!ids.has(m.id)).map((m:any)=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><Button onClick={()=>add.mutate()} disabled={!memberId}>+ Ajouter comme gestionnaire</Button></div>{(managers.data??[]).filter((x:any)=>x.active).map((x:any)=><div key={x.member_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>{name(x.member_id)}</b><p className="text-xs text-muted-foreground">Inventaire, besoins, devis, demandes, fichiers, incidents, prêts et suivi.</p></div><Button size="sm" variant="outline" onClick={()=>remove.mutate(x.member_id)}>Retirer la gestion</Button></div>)}</CardContent></Card><Card className="mt-4"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5"/>Droits par profil</CardTitle><CardDescription>Les gestionnaires matériel et l’Admin technique s’ajoutent à ces droits sans modifier le rôle principal de la personne.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{ROLES.map(([k,l])=><Button key={k} variant={role===k?"default":"outline"} onClick={()=>setRole(k)}>{l}</Button>)}</div>{ACTIONS.map(([a,l])=><div key={a} className="grid gap-2 rounded-xl bg-muted/30 p-3 md:grid-cols-[1fr_220px] md:items-center"><div><p className="font-semibold">{l}</p>{["gerer_inventaire","gerer_demandes","voir_documents","administrer"].includes(a)?<p className="text-xs text-muted-foreground">Permission sensible.</p>:null}</div><select className="h-10 rounded-md border bg-background px-3" value={get(a).scope} onChange={e=>set(a,e.target.value as Scope)}>{SCOPES.map(([s,l2])=><option key={s} value={s}>{l2}</option>)}</select></div>)}<Button onClick={()=>save.mutate()} disabled={save.isPending}><Save className="size-4"/>Enregistrer les droits Matériel</Button></CardContent></Card></AppShell>}
