import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { ChevronRight, Layers3, Merge, Plus, RotateCcw, Save, Settings2, Users } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { membersQuery, polesQuery, settingsQuery } from "@/lib/icc";
import { useAccessRights } from "@/hooks/useAccessRights";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Skeleton } from "@/components/ui/skeleton"; import { Textarea } from "@/components/ui/textarea";
export const Route=createFileRoute("/_authenticated/poles")({head:()=>({meta:[{title:"Pôles — COM ICC Le Mans"}]}),component:Poles}); type Person={id:string;name:string;referent:boolean};
function Poles(){const qc=useQueryClient(),access=useAccessRights();const poles=useQuery(polesQuery),members=useQuery(membersQuery),settings=useQuery(settingsQuery);const merges=useQuery({queryKey:["pole-merges"],queryFn:async()=>{const{data,error}=await (supabase as any).from("pole_merges").select("*").order("created_at",{ascending:false}).limit(20);if(error)throw error;return data??[]}});const[view,setView]=useState<"all"|"groups">("all"),[creating,setCreating]=useState(false),[manage,setManage]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[target,setTarget]=useState(""),[newName,setNewName]=useState(""),[newDescription,setNewDescription]=useState(""),[newGroup,setNewGroup]=useState("");const active=useMemo(()=>(poles.data??[]).filter(p=>!p.archived).sort((a,b)=>a.name.localeCompare(b.name,"fr",{sensitivity:"base"})),[poles.data]);const byPole=useMemo(()=>{const mb=new Map((members.data?.members??[]).filter(m=>m.status==="active").map(m=>[m.id,m]));const map=new Map<string,Person[]>();for(const l of members.data?.links??[]){const m=mb.get(l.member_id);if(!m)continue;map.set(l.pole_id,[...(map.get(l.pole_id)??[]),{id:m.id,name:m.full_name,referent:l.is_referent}])}for(const[id,list]of map)map.set(id,list.sort((a,b)=>Number(b.referent)-Number(a.referent)||a.name.localeCompare(b.name,"fr")));return map},[members.data]);const groupsActive=(settings.data as any)?.direction_structure==="responsable_general_grands_groupes";const canStructure=access.scope("poles","gerer_structure")==="tous";const grouped=useMemo(()=>{const map=new Map<string,typeof active>();for(const p of active){const key=p.pole_group?.trim()||"Non rattaché à un grand groupe";map.set(key,[...(map.get(key)??[]),p])}return[...map.entries()].sort(([a],[b])=>a==="Non rattaché à un grand groupe"?1:b==="Non rattaché à un grand groupe"?-1:a.localeCompare(b,"fr"))},[active]);
 const createPole=useMutation({mutationFn:async()=>{if(!newName.trim())throw Error("Le nom du pôle est obligatoire.");const{error}=await supabase.from("poles").insert({name:newName.trim(),description:newDescription.trim()||null,pole_group:groupsActive?(newGroup||null):null,sort_order:(active.length+1)*10,archived:false});if(error)throw error},onSuccess:async()=>{await qc.invalidateQueries({queryKey:["poles"]});setCreating(false);setNewName("");setNewDescription("");setNewGroup("");toast.success("Pôle créé")},onError:(e:any)=>toast.error("Création impossible",{description:e.message})});
 const merge=useMutation({mutationFn:async()=>{const sources=[...selected].filter(x=>x!==target);if(!target)throw Error("Choisis le pôle de destination.");if(!sources.length)throw Error("Sélectionne au moins un pôle à fusionner.");const{error}=await (supabase as any).rpc("merge_poles_future",{p_target:target,p_sources:sources});if(error)throw error},onSuccess:async()=>{toast.success("Fusion effectuée pour l’organisation actuelle et les programmes à venir. L’historique passé reste inchangé.");setSelected(new Set());setTarget("");setManage(false);await Promise.all([qc.invalidateQueries({queryKey:["poles"]}),qc.invalidateQueries({queryKey:["members"]}),qc.invalidateQueries({queryKey:["programs"]}),qc.invalidateQueries({queryKey:["pole-merges"]})])},onError:(e:any)=>toast.error("Fusion impossible",{description:e.message})});
 const undo=useMutation({mutationFn:async(id:string)=>{const{error}=await (supabase as any).rpc("undo_pole_merge",{p_merge:id});if(error)throw error},onSuccess:async()=>{toast.success("Fusion annulée. Les rattachements futurs ont été restaurés ; l’historique passé n’a pas été réécrit.");await Promise.all([qc.invalidateQueries({queryKey:["poles"]}),qc.invalidateQueries({queryKey:["programs"]}),qc.invalidateQueries({queryKey:["pole-merges"]})])},onError:(e:any)=>toast.error("Retour en arrière impossible",{description:e.message})});
 if(poles.isLoading||members.isLoading||settings.isLoading||access.loading)return <AppShell title="Pôles"><Skeleton className="h-80 rounded-xl"/></AppShell>;const cards=(list:typeof active)=><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{list.map(p=><PoleCard key={p.id} pole={p} people={byPole.get(p.id)??[]} showGroup={groupsActive} manage={manage} selected={selected.has(p.id)} toggle={()=>setSelected(prev=>{const n=new Set(prev);n.has(p.id)?n.delete(p.id):n.add(p.id);return n})}/>)}</div>;
 return <AppShell title="Pôles" subtitle="Organisation du service Communication"><div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-card p-4"><div><p className="font-semibold">{active.length} pôle{active.length>1?"s":""} actif{active.length>1?"s":""}</p><p className="text-sm text-muted-foreground">Tous les pôles, classés par ordre alphabétique.</p></div><div className="flex flex-wrap gap-2">{groupsActive?<><Button variant={view==="all"?"default":"outline"} size="sm" onClick={()=>setView("all")}><Users className="size-4"/>Tous les pôles</Button><Button variant={view==="groups"?"default":"outline"} size="sm" onClick={()=>setView("groups")}><Layers3 className="size-4"/>Par grand groupe</Button></>:null}{canStructure?<><Button size="sm" variant={manage?"default":"outline"} onClick={()=>{setManage(v=>!v);setSelected(new Set());setTarget("")}}><Settings2 className="size-4"/>Gérer les pôles</Button><Button size="sm" onClick={()=>setCreating(v=>!v)}><Plus className="size-4"/>Nouveau pôle</Button></>:null}</div></div>
 {manage&&canStructure?<Card><CardHeader><CardTitle>Fusionner des pôles</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">La fusion modifie l’organisation actuelle, les membres et uniquement les programmes/sollicitations à venir. Les programmes passés gardent leurs anciens pôles pour préserver la traçabilité. Une fusion peut être annulée.</p><div className="grid gap-3 md:grid-cols-[1fr_auto]"><div><Label>Pôle de destination</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choisir le pôle conservé…</option>{active.filter(p=>!selected.has(p.id)||p.id===target).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><Button className="self-end" onClick={()=>merge.mutate()} disabled={merge.isPending||!target||selected.size===0}><Merge className="size-4"/>Fusionner la sélection</Button></div><p className="text-xs text-muted-foreground">Coche sur les cartes les pôles sources à absorber. Le pôle de destination reste actif ; les sources sont archivées.</p></CardContent></Card>:null}
 {creating?<Card><CardHeader><CardTitle>Nouveau pôle</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Nom"><Input value={newName} onChange={e=>setNewName(e.target.value)}/></Field>{groupsActive?<Field label="Grand groupe"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={newGroup} onChange={e=>setNewGroup(e.target.value)}><option value="">Non rattaché</option><option>Communication / Média</option><option>Audiovisuel</option></select></Field>:null}<div className="md:col-span-2"><Field label="Description"><Textarea value={newDescription} onChange={e=>setNewDescription(e.target.value)}/></Field></div><div className="flex gap-2 md:col-span-2"><Button onClick={()=>createPole.mutate()} disabled={createPole.isPending}><Save className="size-4"/>Créer le pôle</Button><Button variant="outline" onClick={()=>setCreating(false)}>Annuler</Button></div></CardContent></Card>:null}
 {active.length===0?<EmptyState title="Aucun pôle actif"/>:view==="groups"&&groupsActive?<div className="space-y-10">{grouped.map(([group,list])=><section key={group} className="space-y-4"><div className="border-b-2 border-primary/20 pb-3"><div className="flex items-center gap-2"><Layers3 className="size-5 text-primary"/><h2 className="font-display text-xl font-bold">{group}</h2><Badge variant="secondary">{list.length} pôle{list.length>1?"s":""}</Badge></div></div>{cards(list)}</section>)}</div>:cards(active)}
 {canStructure&&(merges.data??[]).length?<Card><CardHeader><CardTitle>Historique des fusions</CardTitle></CardHeader><CardContent className="space-y-2">{(merges.data??[]).map((m:any)=><div key={m.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>Fusion du {new Date(m.created_at).toLocaleString("fr-FR")}</b><p className="text-xs text-muted-foreground">{m.source_pole_ids.length} pôle(s) fusionné(s) · historique antérieur conservé</p></div>{m.undone_at?<Badge variant="outline">Annulée</Badge>:<Button size="sm" variant="outline" onClick={()=>{if(confirm("Annuler cette fusion pour les rattachements futurs ?"))undo.mutate(m.id)}}><RotateCcw className="size-4"/>Annuler la fusion</Button>}</div>)}</CardContent></Card>:null}
 </div></AppShell>}
function PoleCard({pole,people,showGroup,manage,selected,toggle}:{pole:any;people:Person[];showGroup:boolean;manage:boolean;selected:boolean;toggle:()=>void}){const ref=people.find(p=>p.referent),others=people.filter(p=>!p.referent);return <Card className={`transition-shadow hover:shadow-md ${selected?"ring-2 ring-primary":""}`}><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><div className="flex items-start gap-2">{manage?<input type="checkbox" className="mt-1 size-4" checked={selected} onChange={toggle}/>:null}<div><CardTitle className="text-lg">{pole.name}</CardTitle>{showGroup&&pole.pole_group?<p className="mt-1 text-xs font-semibold uppercase tracking-wide text-primary">{pole.pole_group}</p>:null}</div></div><Badge variant="secondary">{people.length} membre{people.length>1?"s":""}</Badge></div></CardHeader><CardContent className="space-y-4">{pole.description?<p className="text-sm text-muted-foreground">{pole.description}</p>:null}<div className="space-y-2 rounded-xl bg-muted/35 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Équipe</p>{ref?<div className="font-bold">{ref.name} <span className="text-xs font-semibold text-primary">· Référent</span></div>:<p className="text-sm text-muted-foreground">Aucun référent défini</p>}{others.length?<div className="space-y-1 border-t pt-2">{others.map(p=><p key={p.id} className="text-sm">{p.name}</p>)}</div>:null}</div><Link to="/pole/$id" params={{id:pole.id}} className="block"><Button variant="outline" className="w-full">Voir / modifier la fiche<ChevronRight className="size-4"/></Button></Link></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
