import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Archive, CalendarDays, Pencil, Save, Users } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { membersQuery,polesQuery,programsQuery,settingsQuery,formatDate } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea";
export const Route=createFileRoute("/_authenticated/pole/$id")({component:PoleDetail});
function PoleDetail(){const{id}=Route.useParams();const qc=useQueryClient(),nav=useNavigate();const poles=useQuery(polesQuery),members=useQuery(membersQuery),programs=useQuery(programsQuery),settings=useQuery(settingsQuery);const pole=(poles.data??[]).find(p=>p.id===id);const [edit,setEdit]=useState(false),[name,setName]=useState(""),[description,setDescription]=useState(""),[group,setGroup]=useState("");
 const people=useMemo(()=>{const byId=new Map((members.data?.members??[]).map(m=>[m.id,m]));return(members.data?.links??[]).filter(l=>l.pole_id===id).map(l=>({member:byId.get(l.member_id),referent:l.is_referent})).filter(x=>x.member&&x.member.status==="active").sort((a,b)=>Number(b.referent)-Number(a.referent)||(a.member?.full_name??"").localeCompare(b.member?.full_name??"","fr"))},[members.data,id]);
 const upcoming=useMemo(()=>{const today=new Date().toISOString().slice(0,10);return(programs.data??[]).filter(p=>p.start_date>=today&&p.assignments.some(a=>a.pole_id===id)).slice(0,8)},[programs.data,id]);
 const groupsActive=(settings.data as any)?.direction_structure==="responsable_general_grands_groupes";
 const begin=()=>{if(!pole)return;setName(pole.name);setDescription(pole.description??"");setGroup(pole.pole_group??"");setEdit(true)};
 const save=useMutation({mutationFn:async()=>{if(!pole)return;const{error}=await supabase.from("poles").update({name:name.trim()||pole.name,description:description.trim()||null,pole_group:groupsActive?(group.trim()||null):pole.pole_group,updated_at:new Date().toISOString()}).eq("id",pole.id);if(error)throw error},onSuccess:async()=>{await qc.invalidateQueries({queryKey:["poles"]});setEdit(false);toast.success("Pôle enregistré")},onError:(e:any)=>toast.error(e.message)});
 const archive=useMutation({mutationFn:async()=>{if(!pole)return;const{error}=await supabase.from("poles").update({archived:true,updated_at:new Date().toISOString()}).eq("id",pole.id);if(error)throw error},onSuccess:async()=>{await qc.invalidateQueries({queryKey:["poles"]});toast.success("Pôle archivé");nav({to:"/poles"})}});
 if(!pole)return <AppShell title="Pôle"><EmptyState title="Pôle introuvable"/></AppShell>;
 return <AppShell title={pole.name} subtitle="Fiche du pôle"><div className="space-y-5"><Link to="/poles"><Button variant="ghost"><ArrowLeft className="size-4"/>Retour aux pôles</Button></Link><div className="grid gap-5 lg:grid-cols-[1fr_1.2fr]"><Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{pole.name}</CardTitle>{groupsActive&&pole.pole_group?<Badge className="mt-2" variant="secondary">{pole.pole_group}</Badge>:null}</div><Button variant="outline" size="sm" onClick={begin}><Pencil className="size-4"/>Modifier</Button></div></CardHeader><CardContent className="space-y-4">{edit?<><Field label="Nom"><Input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Description"><Textarea value={description} onChange={e=>setDescription(e.target.value)}/></Field>{groupsActive?<Field label="Grand groupe"><Input value={group} onChange={e=>setGroup(e.target.value)} placeholder="Communication / Média ou Audiovisuel"/></Field>:null}<div className="flex gap-2"><Button onClick={()=>save.mutate()}><Save className="size-4"/>Enregistrer</Button><Button variant="outline" onClick={()=>setEdit(false)}>Annuler</Button></div></>:<p className="text-sm text-muted-foreground">{pole.description||"Aucune description renseignée."}</p>}<div className="border-t pt-4"><Button variant="outline" className="text-destructive" onClick={()=>{if(confirm("Archiver ce pôle ? Son historique sera conservé."))archive.mutate()}}><Archive className="size-4"/>Archiver le pôle</Button></div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="size-5"/>Équipe · {people.length}</CardTitle></CardHeader><CardContent>{people.length?<div className="divide-y">{people.map(({member,referent})=><div key={member!.id} className="flex items-center justify-between py-3"><div className={referent?"font-bold":""}>{member!.full_name}{referent?<span className="ml-2 text-xs text-primary">Référent</span>:null}</div><Badge variant="outline">{(member as any).member_status==="en_formation"?"En formation":"Équipier"}</Badge></div>)}</div>:<p className="text-sm text-muted-foreground">Aucun membre actif dans ce pôle.</p>}<p className="mt-4 text-xs text-muted-foreground">Le référent officiel est géré dans Paramètres → Organisation afin de conserver une seule source de vérité.</p></CardContent></Card></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="size-5"/>Programmes à venir</CardTitle></CardHeader><CardContent>{upcoming.length?<div className="grid gap-3 md:grid-cols-2">{upcoming.map(p=><Link key={p.id} to="/programme/$id" params={{id:p.id}} className="rounded-xl border p-4 hover:bg-muted/40"><p className="font-semibold">{p.title}</p><p className="text-sm text-muted-foreground">{formatDate(p.start_date)}</p></Link>)}</div>:<p className="text-sm text-muted-foreground">Aucun programme à venir affecté à ce pôle.</p>}</CardContent></Card></div></AppShell>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
