import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { useCurrentRole } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { detectConflicts } from "@/lib/conflicts";
import { attendanceQuery,availabilityQuery,formatDate,formatDateTime,internalNotesQuery,logAction,membersQuery,polesQuery,PRESENCE_LABEL,programDocumentsQuery,programsQuery,recurrenceLabel,solicitationsQuery,STATUS_LABEL,timelineQuery,tasksQuery,TASK_STATUS_LABEL,type ResponseStatus,type Task } from "@/lib/icc";
import { Badge } from "@/components/ui/badge";import { Button } from "@/components/ui/button";import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";import { Input } from "@/components/ui/input";import { Textarea } from "@/components/ui/textarea";import { Skeleton } from "@/components/ui/skeleton";import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
export const Route=createFileRoute("/_authenticated/programme/$id")({head:()=>({meta:[{title:"Fiche programme — COM ICC Le Mans"},{name:"description",content:"Fiche programme complète : équipe, tâches, documents et historique."}]}),component:ProgramSheet});
const RESPONSES:ResponseStatus[]=["available","partial","unavailable"];const RESPONSE_TEXT:Record<string,string>={available:"Accepté",partial:"Accepté partiellement",unavailable:"Refusé",pending:"En attente"};const responseLabel=(s:string|null|undefined)=>s?RESPONSE_TEXT[s]??s:"En attente";
function ProgramSheet(){const{id}=Route.useParams();const{member,isStaff}=useCurrentRole();const qc=useQueryClient();const programs=useQuery(programsQuery),poles=useQuery(polesQuery),members=useQuery(membersQuery),availability=useQuery(availabilityQuery),solicitations=useQuery(solicitationsQuery),documents=useQuery(programDocumentsQuery),notes=useQuery(internalNotesQuery),attendance=useQuery(attendanceQuery),timeline=useQuery(timelineQuery("program",id)),tasks=useQuery(tasksQuery);const responses=useQuery({queryKey:["program-responses",id],queryFn:async()=>{const{data,error}=await supabase.from("program_member_responses").select("*").eq("program_id",id);if(error)throw error;return data??[]}});const program=(programs.data??[]).find(p=>p.id===id);const poleName=new Map((poles.data??[]).map(p=>[p.id,p.name]));const memberName=new Map((members.data?.members??[]).map(m=>[m.id,m.full_name]));const programTasks=(tasks.data??[]).filter(t=>t.program_id===id);const assignedIds=[...new Set((program?.assignments??[]).flatMap(a=>a.memberIds))];const responseOf=(mid:string)=>(responses.data??[]).find(r=>r.member_id===mid);const conflicts=programs.data&&availability.data&&members.data?detectConflicts(programs.data,members.data.members,availability.data).filter(c=>c.programId===id):[];
const[editor,setEditor]=useState<ResponseStatus|null>(null),[responseNote,setResponseNote]=useState("");const respond=useMutation({mutationFn:async({status,note}:{status:ResponseStatus;note?:string})=>{if(!member?.id)throw new Error("Compte non lié à un équipier.");const clean=note?.trim()||null;const{error}=await supabase.from("program_member_responses").upsert({id:`${id}__${member.id}`,program_id:id,member_id:member.id,status,reserve:status==="partial"?clean:null,reason:status==="unavailable"?clean:null},{onConflict:"program_id,member_id"});if(error)throw error;await logAction({action:"reponse_affectation",entity:"program",entityId:id,detail:responseLabel(status),actorName:member.full_name})},onSuccess:()=>{setEditor(null);setResponseNote("");qc.invalidateQueries({queryKey:["program-responses",id]});qc.invalidateQueries({queryKey:["programs"]});toast.success("Réponse enregistrée")}});
const toggleTask=useMutation({mutationFn:async(t:Task)=>{const status=t.status==="done"?"todo":"done";const{error}=await supabase.from("tasks").update({status}).eq("id",t.id);if(error)throw error;await logAction({action:"tache_statut",entity:"program",entityId:id,detail:`${t.title} → ${TASK_STATUS_LABEL[status]}`,actorName:member?.full_name})},onSuccess:()=>{qc.invalidateQueries({queryKey:["tasks"]});qc.invalidateQueries({queryKey:["timeline","program",id]})}});
const[taskTitle,setTaskTitle]=useState("");const addTask=useMutation({mutationFn:async()=>{if(!taskTitle.trim())return;const{error}=await supabase.from("tasks").insert({title:taskTitle.trim(),program_id:id,status:"todo",priority:"normale"});if(error)throw error},onSuccess:()=>{setTaskTitle("");qc.invalidateQueries({queryKey:["tasks"]});toast.success("Tâche ajoutée")}});
if(programs.isLoading)return <AppShell title="Fiche programme"><Skeleton className="h-40"/></AppShell>;if(!program)return <AppShell title="Fiche programme"><EmptyState title="Programme introuvable"/></AppShell>;const mine=member?.id?responseOf(member.id):null;return <AppShell title={program.title} subtitle={`${formatDate(program.start_date)}${program.location?` · ${program.location}`:""}`} actions={<><Button size="sm" variant="outline" onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/programme/${id}`)}>🔗 Copier le lien</Button><Button size="sm" variant="outline" onClick={()=>window.print()}>🖨️ Feuille de service</Button></>}><div className="mb-4 flex gap-2"><Badge>{STATUS_LABEL[program.status]??program.status}</Badge>{program.archived?<Badge variant="destructive">Archivé</Badge>:null}</div><Tabs defaultValue="infos"><TabsList className="mb-4 flex-wrap"><TabsTrigger value="infos">Informations</TabsTrigger><TabsTrigger value="taches">Tâches / checklist</TabsTrigger><TabsTrigger value="equipe">Équipe du jour</TabsTrigger><TabsTrigger value="documents">Documents & notes</TabsTrigger><TabsTrigger value="timeline">Timeline</TabsTrigger></TabsList>
<TabsContent value="infos" className="space-y-4"><Card><CardHeader><CardTitle>Informations générales</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Info label="Date" value={formatDate(program.start_date)}/><Info label="Horaires" value={`${program.start_time??"—"} → ${program.end_time??"—"}`}/><Info label="Lieu" value={program.location??"—"}/><Info label="Public" value={program.audience??"—"}/><Info label="Récurrence" value={recurrenceLabel(program.recurrence)}/><Info label="Pôles mobilisés" value={program.assignments.map(a=>poleName.get(a.pole_id)??"?").join(", ")||"—"}/>{program.description?<Info label="Description" value={program.description}/>:null}</CardContent></Card>{member?.id&&assignedIds.includes(member.id)?<Card><CardHeader><CardTitle>Ma réponse à l'affectation</CardTitle></CardHeader><CardContent className="space-y-2"><div className="flex gap-2">{RESPONSES.map(s=><Button key={s} size="sm" variant={mine?.status===s?"default":"outline"} onClick={()=>s==="available"?respond.mutate({status:s}):setEditor(s)}>{s==="available"?"Accepter":s==="partial"?"Accepter partiellement":"Refuser"}</Button>)}</div>{editor?<><Textarea value={responseNote} onChange={e=>setResponseNote(e.target.value)}/><Button size="sm" onClick={()=>respond.mutate({status:editor,note:responseNote})}>Enregistrer</Button></>:null}</CardContent></Card>:null}{conflicts.length?<Card><CardHeader><CardTitle>Conflits et alertes</CardTitle></CardHeader><CardContent>{conflicts.map((c,i)=><p key={i}>{c.message}</p>)}</CardContent></Card>:null}</TabsContent>
<TabsContent value="taches"><Card><CardHeader><CardTitle>Tâches / checklist du programme</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Cette liste est la même que dans Tâches, À faire et Pilotage : une seule source de vérité.</p>{programTasks.length===0?<EmptyState title="Aucune tâche"/>:<div className="space-y-2">{programTasks.map(t=><button key={t.id} onClick={()=>toggleTask.mutate(t)} className="flex w-full items-start gap-3 rounded-lg border p-3 text-left"><span className="text-lg">{t.status==="done"?"☑":"☐"}</span><span><b className={t.status==="done"?"line-through":""}>{t.title}</b><span className="block text-xs text-muted-foreground">{t.assignee_member_id?memberName.get(t.assignee_member_id)??"Assignée":"Non assignée"}{t.due_date?` · ${formatDate(t.due_date)}`:""}</span></span></button>)}</div>}{isStaff?<div className="flex gap-2"><Input placeholder="Ajouter une tâche…" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")addTask.mutate()}}/><Button onClick={()=>addTask.mutate()}>Ajouter</Button></div>:null}<Button asChild variant="outline"><Link to="/taches">Ouvrir la vue Tâches</Link></Button></CardContent></Card></TabsContent>
<TabsContent value="equipe"><Card><CardHeader><CardTitle>Équipe du jour</CardTitle></CardHeader><CardContent className="space-y-3">{program.assignments.map(a=><div key={a.id} className="rounded-lg border p-3"><b>{poleName.get(a.pole_id)??"Pôle"}</b><p className="text-sm text-muted-foreground">{a.tasks}</p>{a.memberIds.map(mid=><p key={mid} className="text-sm">{memberName.get(mid)??mid} · {responseLabel(responseOf(mid)?.status)}</p>)}</div>)}</CardContent></Card></TabsContent>
<TabsContent value="documents"><Card><CardHeader><CardTitle>Documents & notes</CardTitle></CardHeader><CardContent className="space-y-3">{(documents.data??[]).filter(d=>d.program_id===id).map(d=><a key={d.id} href={d.url} className="block font-semibold text-icc-violet underline">{d.title}</a>)}{(notes.data??[]).filter(n=>n.entity==="program"&&n.entity_id===id).map(n=><div key={n.id} className="rounded-lg bg-muted p-3 text-sm">{n.body}<p className="text-xs text-muted-foreground">{n.author_name} · {formatDateTime(n.created_at)}</p></div>)}</CardContent></Card></TabsContent>
<TabsContent value="timeline"><Card><CardHeader><CardTitle>Histoire du programme</CardTitle></CardHeader><CardContent>{(timeline.data??[]).map(e=><p key={e.id} className="mb-2 text-sm"><b>{e.action}</b>{e.detail?` — ${e.detail}`:""}<span className="block text-xs text-muted-foreground">{e.actor_name??"Système"} · {formatDateTime(e.occurred_at)}</span></p>)}</CardContent></Card></TabsContent></Tabs></AppShell>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs font-semibold uppercase text-muted-foreground">{label}</p><p className="text-sm">{value}</p></div>}
