import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { PackageCheck } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { polesQuery } from "@/lib/icc";
export const Route=createFileRoute("/_authenticated/reception-materiel")({head:()=>({meta:[{title:"Réception matériel — COM ICC Le Mans"}]}),component:Page});
const db=()=>supabase as any;const euro=(n:any)=>Number(n||0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
function Page(){const qc=useQueryClient(),poles=useQuery(polesQuery),needs=useQuery({queryKey:["material-receivable-needs"],queryFn:async()=>{const{data,error}=await db().from("material_needs").select("*").in("status",["valide","commande"]).is("converted_item_id",null).order("created_at");if(error)throw error;return data??[]}});const poleName=new Map((poles.data??[]).map((p:any)=>[p.id,p.name]));const[target,setTarget]=useStateCompat<any>(null),[cat,setCat]=useStateCompat("autre"),[location,setLocation]=useStateCompat(""),[brand,setBrand]=useStateCompat(""),[model,setModel]=useStateCompat("");const receive=useMutation({mutationFn:async()=>{if(!target)throw Error("Besoin introuvable");const{data,error}=await db().rpc("material_receive_need",{p_need_id:target.id,p_category:cat,p_location:location||null,p_brand:brand||null,p_model:model||null});if(error)throw error;return data},onSuccess:async()=>{setTarget(null);toast.success("Matériel reçu et ajouté automatiquement à l’inventaire");await qc.invalidateQueries({queryKey:["material-receivable-needs"]});await qc.invalidateQueries({queryKey:["material-items"]});await qc.invalidateQueries({queryKey:["material-needs"]})},onError:(e:any)=>toast.error(e.message)});return <AppShell title="Réception matériel" subtitle="Transformer un besoin validé ou commandé en matériel réellement reçu, sans ressaisie."><div className="space-y-3">{(needs.data??[]).map((n:any)=><Card key={n.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><b>{n.title}</b><p className="text-sm text-muted-foreground">{poleName.get(n.pole_id)||"COM"} · Qté {n.quantity} · estimation {euro(n.estimated_budget)} · {n.status==="commande"?"Commandé":"Validé"}</p></div><Button onClick={()=>{setTarget(n);setCat("autre");setLocation("");setBrand("");setModel("")}}><PackageCheck className="size-4"/>Réceptionner</Button></CardContent></Card>)}{!(needs.data??[]).length?<EmptyState title="Aucun matériel à réceptionner" description="Les besoins validés ou commandés apparaîtront ici."/>:null}</div><Dialog open={!!target} onOpenChange={o=>!o&&setTarget(null)}><DialogContent><DialogHeader><DialogTitle>Réceptionner · {target?.title}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Le besoin passera à « Reçu » et une fiche d’inventaire sera créée automatiquement. Vous pourrez ensuite la compléter dans Matériel COM.</p><F l="Catégorie"><Input value={cat} onChange={e=>setCat(e.target.value)} placeholder="Son, vidéo, câblage…"/></F><F l="Marque"><Input value={brand} onChange={e=>setBrand(e.target.value)}/></F><F l="Modèle"><Input value={model} onChange={e=>setModel(e.target.value)}/></F><F l="Lieu de rangement"><Input value={location} onChange={e=>setLocation(e.target.value)}/></F><DialogFooter><Button onClick={()=>receive.mutate()} disabled={receive.isPending}>Confirmer la réception</Button></DialogFooter></DialogContent></Dialog></AppShell>}
import { useState } from "react";const useStateCompat=useState;function F({l,children}:any){return <div className="space-y-1"><Label>{l}</Label>{children}</div>}
