import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarClock, Save } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState } from "@/components/AppShell";
import { useCurrentRole } from "@/hooks/useAuth";
import { formatDate, logAction, programsQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea";
export const Route=createFileRoute("/_authenticated/reporter-programme/$id")({component:ReporterProgramme});
function ReporterProgramme(){const{id}=Route.useParams();const nav=useNavigate(),qc=useQueryClient();const{member,isStaff,isAdmin}=useCurrentRole();const programs=useQuery(programsQuery);const program=(programs.data??[]).find(p=>p.id===id);const p:any=program;const [known,setKnown]=useState<boolean>(p?.postponed_new_date_known??true),[newStart,setNewStart]=useState(p?.postponed_new_start_date??""),[newEnd,setNewEnd]=useState(p?.postponed_new_end_date??""),[reason,setReason]=useState(p?.postponed_reason??"");
 const save=useMutation({mutationFn:async()=>{if(!program)throw Error("Programme introuvable.");if(!isStaff&&!isAdmin)throw Error("Vous n’avez pas le droit de reporter ce programme.");if(known&&!newStart)throw Error("Renseigne la nouvelle date prévue, ou indique qu’elle n’est pas encore connue.");const already=program.status==="postponed";const originalStart=p.postponed_original_start_date??program.start_date,originalEnd=p.postponed_original_end_date??program.end_date;const payload:any={status:"postponed",postponed_original_start_date:originalStart,postponed_original_end_date:originalEnd,postponed_new_date_known:known,postponed_new_start_date:known?newStart:null,postponed_new_end_date:known?(newEnd||newStart):null,postponed_reason:reason.trim()||null,postponed_at:new Date().toISOString()};if(known){payload.start_date=newStart;payload.end_date=newEnd||newStart;}const{error}=await (supabase as any).from("programs").update(payload).eq("id",id);if(error)throw error;const detail=already?`Nouvelle date ${known?`renseignée/modifiée : ${newStart}${newEnd&&newEnd!==newStart?` → ${newEnd}`:""}`:"toujours à renseigner"}`:`Programme reporté · ancienne date : ${originalStart}${known?` · nouvelle date prévue : ${newStart}${newEnd&&newEnd!==newStart?` → ${newEnd}`:""}`:" · nouvelle date à renseigner ultérieurement"}${reason.trim()?` · motif : ${reason.trim()}`:""}`;await logAction({action:already?"programme_nouvelle_date":"programme_reporte",entity:"program",entityId:id,detail,actorName:member?.full_name})},onSuccess:async()=>{toast.success("Report enregistré et ajouté à l’historique");await qc.invalidateQueries({queryKey:["programs"]});await qc.invalidateQueries({queryKey:["timeline","program",id]});nav({to:"/programme/$id",params:{id}})},onError:(e:any)=>toast.error("Enregistrement impossible",{description:e.message})});
 if(programs.isLoading)return <AppShell title="Reporter un programme"><p>Chargement…</p></AppShell>;if(!program)return <AppShell title="Reporter un programme"><EmptyState title="Programme introuvable"/></AppShell>;
 return <AppShell title={program.status==="postponed"?"Nouvelle date du programme":"Reporter le programme"} subtitle={program.title}><div className="max-w-2xl space-y-5"><Link to="/programme/$id" params={{id}}><Button variant="ghost"><ArrowLeft className="size-4"/>Retour à la fiche</Button></Link><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="size-5"/>{program.status==="postponed"?"Mise à jour du report":"Report du programme"}</CardTitle></CardHeader><CardContent className="space-y-5"><div className="rounded-xl bg-muted/40 p-4 text-sm"><b>Date de référence avant report :</b> {formatDate(p.postponed_original_start_date??program.start_date)}<p className="mt-1 text-muted-foreground">Cette date reste conservée dans l’historique même lorsque la nouvelle date devient la date active du programme.</p></div><div><Label>La nouvelle date est-elle connue ?</Label><div className="mt-2 flex flex-wrap gap-2"><Button type="button" variant={known?"default":"outline"} onClick={()=>setKnown(true)}>Oui, elle est connue</Button><Button type="button" variant={!known?"default":"outline"} onClick={()=>setKnown(false)}>Non, à renseigner plus tard</Button></div></div>{known?<div className="grid gap-3 sm:grid-cols-2"><div><Label>Nouvelle date prévue *</Label><Input className="mt-2" type="date" value={newStart} onChange={e=>setNewStart(e.target.value)}/></div><div><Label>Date de fin prévue</Label><Input className="mt-2" type="date" min={newStart||undefined} value={newEnd} onChange={e=>setNewEnd(e.target.value)}/></div></div>:<div className="rounded-xl border border-dashed p-4 text-sm"><b>Nouvelle date prévue : à renseigner ultérieurement</b><p className="mt-1 text-muted-foreground">Le programme restera dans « À venir » avec le statut Reporté jusqu’à ce qu’une nouvelle date soit indiquée.</p></div>}<div><Label>Motif du report (optionnel)</Label><Textarea className="mt-2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex. indisponibilité de salle, contrainte logistique…"/></div><Button onClick={()=>save.mutate()} disabled={save.isPending}><Save className="size-4"/>{save.isPending?"Enregistrement…":"Enregistrer le report"}</Button></CardContent></Card></div></AppShell>}
