import {createFileRoute} from "@tanstack/react-router";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useMemo,useState} from "react";
import {CalendarHeart,Check,ClipboardList,Plus,Users} from "lucide-react";
import {toast} from "sonner";
import {AppShell,EmptyState} from "@/components/AppShell";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Textarea} from "@/components/ui/textarea";
import {Badge} from "@/components/ui/badge";
import {useCurrentRole} from "@/hooks/useAuth";
import {supabase} from "@/integrations/supabase/client";
import {logAction,membersQuery,polesQuery} from "@/lib/icc";

export const Route=createFileRoute("/_authenticated/vie-equipe")({head:()=>({meta:[{title:"Vie d’équipe — COM ICC Le Mans"}]}),component:VieEquipe});
const db=()=>supabase as any;
const RESP:any={yes:"Je participe ❤️",maybe:"Peut-être",no:"Je ne pourrai pas"};
const KIND:any={communion_fraternelle:"Communion fraternelle",sortie:"Sortie",pique_nique:"Pique-nique",repas:"Repas",autre:"Autre"};
function fmt(v?:string|null){return v?new Date(v).toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short"}):"Date à définir"}
function usePerm(userId:string|undefined,action:string){return useQuery({queryKey:["team-life-perm",userId,action],enabled:!!userId,queryFn:async()=>{const{data,error}=await db().rpc("access_scope_for_user",{p_user:userId,p_module:"vie_equipe",p_action:action});if(error)throw error;return data as string}})}

function VieEquipe(){
 const{member,userId,isTechAdmin}=useCurrentRole();const qc=useQueryClient();const poles=useQuery(polesQuery);const members=useQuery(membersQuery);
 const events=useQuery({queryKey:["team-life-events"],queryFn:async()=>{const{data,error}=await db().from("team_life_events").select("*").order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const parts=useQuery({queryKey:["team-life-parts"],queryFn:async()=>{const{data,error}=await db().from("team_life_participations").select("*");if(error)throw error;return data??[]}});
 const polls=useQuery({queryKey:["team-life-polls"],queryFn:async()=>{const{data,error}=await db().from("team_life_polls").select("*");if(error)throw error;return data??[]}});
 const options=useQuery({queryKey:["team-life-poll-options"],queryFn:async()=>{const{data,error}=await db().from("team_life_poll_options").select("*").order("sort_order");if(error)throw error;return data??[]}});
 const votes=useQuery({queryKey:["team-life-poll-votes"],queryFn:async()=>{const{data,error}=await db().from("team_life_poll_votes").select("*");if(error)throw error;return data??[]}});
 const finance=useQuery({queryKey:["team-life-finance"],queryFn:async()=>{const{data,error}=await db().from("team_finance_expenses").select("id,related_team_event_id,amount,status");if(error)throw error;return data??[]}});
 const pOrganise=usePerm(userId,"organiser"),pValidate=usePerm(userId,"valider");const canOrganise=isTechAdmin||pOrganise.data!=="interdit",canValidate=isTechAdmin||pValidate.data!=="interdit";
 const refresh=()=>Promise.all(["team-life-events","team-life-parts","team-life-polls","team-life-poll-options","team-life-poll-votes","team-life-finance"].map(k=>qc.invalidateQueries({queryKey:[k]})));
 const [open,setOpen]=useState(false),[title,setTitle]=useState(""),[desc,setDesc]=useState(""),[kind,setKind]=useState("communion_fraternelle"),[audience,setAudience]=useState("team"),[poleIds,setPoleIds]=useState<string[]>([]);
 const create=useMutation({mutationFn:async()=>{if(!title.trim())throw Error("Titre obligatoire");const{error}=await db().from("team_life_events").insert({title:title.trim(),description:desc.trim()||null,event_kind:kind,audience_kind:audience,audience_pole_ids:audience==="poles"?poleIds:[],status:"proposal"});if(error)throw error;await logAction({action:"proposition_vie_equipe",entity:"team_life",detail:title.trim(),actorName:member?.full_name})},onSuccess:async()=>{toast.success("Proposition publiée");setOpen(false);setTitle("");setDesc("");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const respond=useMutation({mutationFn:async({eventId,response}:{eventId:string,response:string})=>{if(!member?.id)throw Error("Compte non relié");const{error}=await db().from("team_life_participations").upsert({event_id:eventId,member_id:member.id,response,responded_at:new Date().toISOString()},{onConflict:"event_id,member_id"});if(error)throw error},onSuccess:refresh,onError:(e:any)=>toast.error(e.message)});
 const [pollEvent,setPollEvent]=useState<any>(null),[question,setQuestion]=useState("Quelle option préférez-vous ?"),[optionLines,setOptionLines]=useState("");
 const createPoll=useMutation({mutationFn:async()=>{const labels=optionLines.split("\n").map(x=>x.trim()).filter(Boolean);if(labels.length<2)throw Error("Ajoute au moins 2 options");const{data:p,error}=await db().from("team_life_polls").insert({event_id:pollEvent.id,question,status:"open"}).select("id").single();if(error)throw error;const{error:o}=await db().from("team_life_poll_options").insert(labels.map((label,i)=>({poll_id:p.id,label,sort_order:i})));if(o)throw o;await db().from("team_life_events").update({status:"polling",updated_at:new Date().toISOString()}).eq("id",pollEvent.id)},onSuccess:async()=>{toast.success("Sondage lancé");setPollEvent(null);setOptionLines("");await refresh()},onError:(e:any)=>toast.error(e.message)});
 const vote=useMutation({mutationFn:async({pollId,optionId}:{pollId:string;optionId:string})=>{if(!member?.id)throw Error("Compte non relié");const poll:any=(polls.data??[]).find((p:any)=>p.id===pollId);if(!poll?.allow_multiple)await db().from("team_life_poll_votes").delete().eq("poll_id",pollId).eq("member_id",member.id);const mine=(votes.data??[]).find((v:any)=>v.poll_id===pollId&&v.option_id===optionId&&v.member_id===member.id);if(mine){const{error}=await db().from("team_life_poll_votes").delete().eq("id",mine.id);if(error)throw error}else{const{error}=await db().from("team_life_poll_votes").insert({poll_id:pollId,option_id:optionId,member_id:member.id});if(error)throw error}},onSuccess:refresh,onError:(e:any)=>toast.error(e.message)});
 const [schedule,setSchedule]=useState<any>(null),[start,setStart]=useState(""),[end,setEnd]=useState(""),[location,setLocation]=useState(""),[budget,setBudget]=useState("");
 const validateEvent=useMutation({mutationFn:async()=>{if(!start)throw Error("Date de début obligatoire");const{data:{user}}=await supabase.auth.getUser();const{error}=await db().from("team_life_events").update({status:"scheduled",starts_at:new Date(start).toISOString(),ends_at:end?new Date(end).toISOString():null,location:location.trim()||null,budget_planned:budget?Number(budget.replace(",",".")):null,approved_by:user!.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",schedule.id);if(error)throw error;await logAction({action:"evenement_vie_equipe_valide",entity:"team_life",entityId:schedule.id,detail:schedule.title,actorName:member?.full_name})},onSuccess:async()=>{toast.success("Événement validé et planifié");setSchedule(null);await refresh()},onError:(e:any)=>toast.error(e.message)});
 const visible=events.data??[];const upcoming=visible.filter((e:any)=>e.status==="scheduled"&&e.starts_at&&new Date(e.starts_at)>=new Date()).sort((a:any,b:any)=>a.starts_at.localeCompare(b.starts_at));
 const memberName=useMemo(()=>new Map((members.data?.members??[]).map((m:any)=>[m.id,m.full_name])),[members.data]);
 return <AppShell title="Vie d’équipe" subtitle="Anniversaires, propositions, sondages et communions fraternelles — hors statistiques opérationnelles." actions={<Button size="sm" onClick={()=>setOpen(true)}><Plus className="size-4"/>Faire une proposition</Button>}>
  <div className="grid gap-3 sm:grid-cols-3"><Mini icon={<CalendarHeart/>} n={upcoming.length} label="Événement(s) à venir"/><Mini icon={<ClipboardList/>} n={visible.filter((e:any)=>e.status==="proposal"||e.status==="polling").length} label="Proposition(s) / sondage(s)"/><Mini icon={<Users/>} n={(parts.data??[]).filter((p:any)=>p.response==="yes").length} label="Participations positives déclarées"/></div>
  <div className="mt-4 space-y-4">{visible.length?visible.map((e:any)=>{const ep=(parts.data??[]).filter((p:any)=>p.event_id===e.id);const my=ep.find((p:any)=>p.member_id===member?.id);const poll=(polls.data??[]).find((p:any)=>p.event_id===e.id);const opts=(options.data??[]).filter((o:any)=>o.poll_id===poll?.id);const spent=(finance.data??[]).filter((x:any)=>x.related_team_event_id===e.id&&x.status==="approved").reduce((s:number,x:any)=>s+Number(x.amount),0);return <Card key={e.id}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><Badge>{KIND[e.event_kind]??e.event_kind}</Badge><Badge variant="outline">{e.status==="proposal"?"Proposition":e.status==="polling"?"Sondage en cours":e.status==="scheduled"?"Planifié":e.status}</Badge></div><CardTitle className="mt-2">{e.title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{e.description}</p></div><div className="text-right text-sm"><b>{fmt(e.starts_at)}</b>{e.location?<p>{e.location}</p>:null}</div></div></CardHeader><CardContent className="space-y-4">
    {e.status==="scheduled"?<><div className="grid gap-2 sm:grid-cols-3"><Stat label="Je participe" n={ep.filter((p:any)=>p.response==="yes").length}/><Stat label="Peut-être" n={ep.filter((p:any)=>p.response==="maybe").length}/><Stat label="Ne pourra pas" n={ep.filter((p:any)=>p.response==="no").length}/></div><div className="flex flex-wrap gap-2">{Object.entries(RESP).map(([k,l]:any)=><Button key={k} size="sm" variant={my?.response===k?"default":"outline"} onClick={()=>respond.mutate({eventId:e.id,response:k})}>{l}</Button>)}</div><p className="text-xs text-muted-foreground">Ces réponses servent uniquement à l’organisation et ne sont jamais utilisées dans les statistiques de présence, fiabilité ou évaluation.</p></>:null}
    {poll?<div className="rounded-xl border p-3"><b>{poll.question}</b><div className="mt-3 space-y-2">{opts.map((o:any)=>{const count=(votes.data??[]).filter((v:any)=>v.option_id===o.id).length;const mine=(votes.data??[]).some((v:any)=>v.option_id===o.id&&v.member_id===member?.id);return <button key={o.id} onClick={()=>vote.mutate({pollId:poll.id,optionId:o.id})} className={`flex w-full items-center justify-between rounded-lg border p-3 text-left ${mine?"border-icc-violet bg-muted":""}`}><span>{mine?<Check className="mr-2 inline size-4"/>:null}{o.label}</span><b>{count} vote(s)</b></button>})}</div></div>:null}
    {(canOrganise||e.created_by===userId)&&!poll&&e.status!=="scheduled"?<Button size="sm" variant="outline" onClick={()=>setPollEvent(e)}>Lancer un sondage</Button>:null}
    {canValidate&&e.status!=="scheduled"?<Button size="sm" onClick={()=>setSchedule(e)}>Valider / fixer la date</Button>:null}
    {e.status==="scheduled"&&(e.budget_planned||spent)?<div className="rounded-xl bg-muted/40 p-3 text-sm"><b>Budget de l’événement</b><p>Prévu : {Number(e.budget_planned??0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"})} · Dépenses validées : {spent.toLocaleString("fr-FR",{style:"currency",currency:"EUR"})}</p></div>:null}
  </CardContent></Card>}):<EmptyState title="Aucune proposition pour le moment" description="La vie d’équipe se construira ici : sorties, pique-niques, repas, sondages et communions fraternelles."/>}</div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Faire une proposition</DialogTitle></DialogHeader><div className="space-y-3"><Field l="Titre"><Input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field l="Type"><select className="h-10 w-full rounded-md border bg-background px-3" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(KIND).map(([k,l]:any)=><option key={k} value={k}>{l}</option>)}</select></Field><Field l="Description"><Textarea value={desc} onChange={e=>setDesc(e.target.value)}/></Field><Field l="Audience"><select className="h-10 w-full rounded-md border bg-background px-3" value={audience} onChange={e=>setAudience(e.target.value)}><option value="team">Toute l’équipe</option><option value="poles">Un ou plusieurs pôles</option></select></Field>{audience==="poles"?<div className="grid gap-2 sm:grid-cols-2">{(poles.data??[]).filter((p:any)=>!p.archived&&!p.deleted).map((p:any)=><label key={p.id} className="flex gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" checked={poleIds.includes(p.id)} onChange={ev=>setPoleIds(x=>ev.target.checked?[...x,p.id]:x.filter(id=>id!==p.id))}/>{p.name}</label>)}</div>:null}</div><DialogFooter><Button onClick={()=>create.mutate()}>Publier la proposition</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!pollEvent} onOpenChange={o=>!o&&setPollEvent(null)}><DialogContent><DialogHeader><DialogTitle>Lancer un sondage</DialogTitle></DialogHeader><Field l="Question"><Input value={question} onChange={e=>setQuestion(e.target.value)}/></Field><Field l="Options (une par ligne)"><Textarea rows={6} value={optionLines} onChange={e=>setOptionLines(e.target.value)} placeholder={'Samedi 12 septembre\nDimanche 13 septembre\nSamedi 19 septembre'}/></Field><DialogFooter><Button onClick={()=>createPoll.mutate()}>Lancer le sondage</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!schedule} onOpenChange={o=>!o&&setSchedule(null)}><DialogContent><DialogHeader><DialogTitle>Valider et planifier</DialogTitle></DialogHeader><div className="space-y-3"><Field l="Début"><Input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field l="Fin (facultatif)"><Input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field l="Lieu"><Input value={location} onChange={e=>setLocation(e.target.value)}/></Field><Field l="Budget prévu (€)"><Input inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)}/></Field></div><DialogFooter><Button onClick={()=>validateEvent.mutate()}>Valider l’événement</Button></DialogFooter></DialogContent></Dialog>
 </AppShell>
}
function Mini({icon,n,label}:{icon:any;n:number;label:string}){return <Card><CardContent className="p-4"><span className="text-icc-violet">{icon}</span><b className="mt-1 block text-2xl text-icc-violet">{n}</b><small>{label}</small></CardContent></Card>}
function Stat({label,n}:{label:string;n:number}){return <div className="rounded-lg bg-muted/40 p-2 text-center"><b>{n}</b><p className="text-xs text-muted-foreground">{label}</p></div>}
function Field({l,children}:{l:string;children:any}){return <div className="space-y-1"><Label>{l}</Label>{children}</div>}
