-- Matériel COM : inventaire, besoins, incidents, demandes/devis et historique.
-- Migration appliquée sur le projet Supabase de production le 2026-08-28.
-- Les lectures sont ouvertes aux utilisateurs authentifiés ; les écritures sensibles sont réservées au staff/admin technique.
-- Les besoins peuvent être créés par tout membre et modifiés par leur auteur ou le staff.

create table if not exists public.com_equipment (id uuid primary key default gen_random_uuid(), name text not null, category text, brand text, model text, serial_number text, quantity integer not null default 1, condition text not null default 'bon', location text, primary_pole_id uuid references public.poles(id) on delete set null, shared_pole_ids uuid[] not null default '{}', responsible_member_id text references public.members(id) on delete set null, acquired_on date, purchase_price numeric(12,2), notes text, photo_url text, archived boolean not null default false, created_by uuid default auth.uid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.com_equipment_needs (id uuid primary key default gen_random_uuid(), title text not null, description text, pole_id uuid references public.poles(id) on delete set null, category text, quantity integer not null default 1, priority text not null default 'normale', horizon text not null default 'court_terme', status text not null default 'brouillon', estimated_budget numeric(12,2), alternative_budget numeric(12,2), justification text, links jsonb not null default '[]', attachments jsonb not null default '[]', created_by uuid default auth.uid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.com_equipment_incidents (id uuid primary key default gen_random_uuid(), equipment_id uuid not null references public.com_equipment(id) on delete cascade, description text not null, status text not null default 'signale', reported_by uuid default auth.uid(), reported_at timestamptz not null default now(), resolved_at timestamptz);
create table if not exists public.com_equipment_requests (id uuid primary key default gen_random_uuid(), title text not null, status text not null default 'preparation', notes text, submitted_on date, total_estimated numeric(12,2), created_by uuid default auth.uid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.com_equipment_request_items (request_id uuid references public.com_equipment_requests(id) on delete cascade, need_id uuid references public.com_equipment_needs(id) on delete cascade, primary key(request_id,need_id));
create table if not exists public.com_equipment_history (id uuid primary key default gen_random_uuid(), equipment_id uuid references public.com_equipment(id) on delete cascade, action text not null, detail text, actor_id uuid default auth.uid(), created_at timestamptz not null default now());
