alter table public.material_loans alter column item_id drop not null;
alter table public.material_loans add column if not exists movement_type text not null default 'com_pret';
alter table public.material_loans add column if not exists item_name text;
alter table public.material_loans add column if not exists lender_member_id text;
alter table public.material_loans add column if not exists lender_name text;
alter table public.material_loans add column if not exists borrower_name text;
alter table public.material_loans add column if not exists contact_phone text;
alter table public.material_loans add column if not exists contact_email text;
alter table public.material_loans add column if not exists organization text;
alter table public.material_loans add column if not exists rental_price numeric;
alter table public.material_loans add column if not exists deposit_amount numeric;
alter table public.material_loans add column if not exists extra_cost numeric;
alter table public.material_loans add column if not exists contract_reference text;
alter table public.material_loans add column if not exists received_condition text;
alter table public.material_loans add column if not exists return_condition text;
alter table public.material_loans add column if not exists return_note text;
alter table public.material_loans add column if not exists cancelled_at timestamptz;
alter table public.material_loans drop constraint if exists material_loans_movement_type_check;
alter table public.material_loans add constraint material_loans_movement_type_check check (movement_type in ('com_pret','pret_a_com','location'));
update public.material_loans set movement_type='com_pret' where movement_type is null;
create index if not exists material_loans_due_active_idx on public.material_loans(due_at) where returned_at is null and cancelled_at is null;
