import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Database, Download, HardDrive, RefreshCw, ShieldCheck, UserPlus, XCircle } from "lucide-react";
import { toast } from "sonner";
import { useCurrentRole } from "@/hooks/useAuth";
import { membersQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type TechAdmin={member_id:string;full_name:string;auth_user_id:string};
type Status={database:string;auth:string;storage:string;checked_at:string;storage_used_bytes:number;storage_capacity_bytes:number|null;storage_remaining_bytes:number|null;storage_percent:number|null;file_count:number;member_count:number;program_count:number;solicitation_count:number};
type Diagnostic={key:string;label:string;count:number};
const SUPABASE_PROJECT={name:"Comicclemans",ref:"fticxzuzjgeypvqrfrwk",url:"https://fticxzuzjgeypvqrfrwk.supabase.co",region:"Europe (eu-west-1)",postgres:"PostgreSQL 17.6",plan:"Free",storageBytes:1024**3};
const bytes=(n:number|null|undefined)=>{if(n==null)return "Non défini";if(n<1024)return `${n} o`;if(n<1024**2)return `${(n/1024).toFixed(1)} Ko`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} Mo`;return `${(n/1024**3).toFixed(2)} Go`;};
function downloadJson(name:string,data:any){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export function TechnicalAdminPanel({settings}:{settings:any}){
 const {isTechAdmin}=useCurrentRole(); const qc=useQueryClient(); const members=useQuery(membersQuery); const [newAdmin,setNewAdmin]=useState(""); const [diagnostics,setDiagnostics]=useState<Diagnostic[]|null>(null);
 const admins=useQuery({queryKey:["technical-admins"],enabled:isTechAdmin,queryFn:async()=>{const{data,error}=await (supabase as any).rpc("technical_admins");if(error)throw error;return data as TechAdmin[]}});
 const status=useQuery({queryKey:["technical-status"],enabled:isTechAdmin,queryFn:async()=>{const{data,error}=await (supabase as any).rpc("technical_system_status");if(error)throw error;return data as Status},refetchInterval:60000});
 const activeMembers=useMemo(()=>(members.data?.members??[]).filter((m:any)=>m.status==="active"&&m.auth_user_id),[members.data]);
 const availableAdmins=activeMembers.filter((m:any)=>!(admins.data??[]).some(a=>a.member_id===m.id));
 const manage=useMutation({mutationFn:async({memberId,enabled}:{memberId:string;enabled:boolean})=>{const{error}=await (supabase as any).rpc("set_technical_admin",{p_member_id:memberId,p_enabled:enabled});if(error)throw error},onSuccess:async()=>{toast.success("Habilitation Admin technique mise à jour");setNewAdmin("");await qc.invalidateQueries({queryKey:["technical-admins"]});await qc.invalidateQueries({queryKey:["current-role"]})},onError:(e:any)=>toast.error("Modification impossible",{description:e.message})});
 const runDiagnostics=useMutation({mutationFn:async()=>{const{data,error}=await (supabase as any).rpc("technical_diagnostics");if(error)throw error;return data},onSuccess:(data:any)=>{setDiagnostics(data?.checks??[]);toast.success("Diagnostic terminé")},onError:(e:any)=>toast.error("Diagnostic impossible",{description:e.message})});
 const refreshStatus=async()=>{const result=await status.refetch();if(result.error){toast.error("Actualisation impossible",{description:(result.error as any)?.message});return}toast.success("État du système actualisé")};
 const doExport=async(kind:"configuration"|"data")=>{try{const fn=kind==="configuration"?"technical_export_configuration":"technical_export_data";const{data,error}=await (supabase as any).rpc(fn);if(error)throw error;downloadJson(`icc-${kind}-${new Date().toISOString().slice(0,10)}.json`,data);toast.success(kind==="configuration"?"Configuration exportée":"Données exportées")}catch(e:any){toast.error("Export impossible",{description:e.message})}};
 if(!isTechAdmin)return <Card><CardHeader><CardTitle>Administration technique</CardTitle><CardDescription>Cette zone est réservée aux administrateurs techniques habilités.</CardDescription></CardHeader></Card>;
 const s=status.data; const capacity=s?.storage_capacity_bytes??SUPABASE_PROJECT.storageBytes; const remaining=s?.storage_remaining_bytes??(s?.storage_used_bytes!=null?Math.max(capacity-s.storage_used_bytes,0):null); const percent=s?.storage_percent??(s?.storage_used_bytes!=null?Math.round((s.storage_used_bytes/capacity)*10000)/100:null); const alertLevel=percent!=null?percent>=90?"critical":percent>=80?"warning":"ok":"unknown";
 return <div className="space-y-4">
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5"/>Administrateurs techniques</CardTitle><CardDescription>Habilitation transversale indépendante du rôle métier. Elle ne transforme jamais un Équipier ou un Référent en membre de la Direction.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2">{(admins.data??[]).map(a=><div key={a.member_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>{a.full_name}</b><p className="text-xs text-muted-foreground">Admin technique actif</p></div><Button variant="outline" size="sm" onClick={()=>manage.mutate({memberId:a.member_id,enabled:false})} disabled={manage.isPending}><XCircle className="size-4"/>Retirer</Button></div>)}</div><div className="grid gap-2 md:grid-cols-[1fr_auto]"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={newAdmin} onChange={e=>setNewAdmin(e.target.value)}><option value="">Ajouter un administrateur technique…</option>{availableAdmins.map((m:any)=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><Button onClick={()=>newAdmin&&manage.mutate({memberId:newAdmin,enabled:true})} disabled={!newAdmin||manage.isPending}><UserPlus className="size-4"/>Ajouter</Button></div><p className="text-xs text-muted-foreground">Seuls les membres possédant déjà un compte applicatif peuvent recevoir cette habilitation. Le dernier Admin technique ne peut pas être retiré.</p></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="size-5"/>Infrastructure Supabase</CardTitle><CardDescription>Informations techniques du projet connecté. Aucune clé secrète n’est affichée dans l’application.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Info label="Projet" value={SUPABASE_PROJECT.name}/><Info label="Project ID / référence" value={SUPABASE_PROJECT.ref}/><Info label="Forfait" value={SUPABASE_PROJECT.plan}/><Info label="URL API" value={SUPABASE_PROJECT.url}/><Info label="Région" value={SUPABASE_PROJECT.region}/><Info label="Base" value={SUPABASE_PROJECT.postgres}/></div><p className="mt-3 text-xs text-muted-foreground">Les clés privées et service-role ne doivent jamais être exposées dans une interface navigateur. Les informations ci-dessus servent uniquement au diagnostic et à l’identification du projet.</p></CardContent></Card>
  <Card><CardHeader><CardTitle>État du système</CardTitle><CardDescription>Contrôle rapide des services et des volumes métier.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><State label="Base Supabase" ok={s?.database==="ok"}/><State label="Authentification" ok={s?.auth==="ok"}/><State label="Stockage fichiers" ok={s?.storage==="ok"}/><div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">Dernière vérification</p><b className="text-sm">{s?.checked_at?new Date(s.checked_at).toLocaleString("fr-FR"):"…"}</b></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Membres actifs" value={s?.member_count}/><Metric label="Programmes actifs" value={s?.program_count}/><Metric label="Sollicitations actives" value={s?.solicitation_count}/><Metric label="Fichiers stockés" value={s?.file_count}/></div><Button variant="outline" onClick={refreshStatus} disabled={status.isFetching}><RefreshCw className={`size-4 ${status.isFetching?"animate-spin":""}`}/>{status.isFetching?"Actualisation…":"Actualiser"}</Button></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><HardDrive className="size-5"/>Stockage & fichiers</CardTitle><CardDescription>Capacité de référence liée au forfait Supabase actuellement utilisé : Free = 1 Go de stockage fichiers. Cette valeur sert au suivi et ne modifie pas le forfait.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Metric label="Espace utilisé" value={bytes(s?.storage_used_bytes)}/><Metric label="Capacité totale — Free" value={bytes(capacity)}/><Metric label="Espace restant" value={bytes(remaining)}/></div>{percent!=null?<div className="rounded-xl border p-3"><div className="flex items-center justify-between gap-3"><b>{percent}% utilisé</b><Badge variant={alertLevel==="critical"?"destructive":"outline"}>{alertLevel==="critical"?"Critique":alertLevel==="warning"?"Attention":"Normal"}</Badge></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-foreground" style={{width:`${Math.min(percent,100)}%`}}/></div>{alertLevel!=="ok"?<p className="mt-2 text-xs text-muted-foreground">{alertLevel==="critical"?"Le stockage dépasse 90 % de la capacité Free.":"Le stockage dépasse 80 % de la capacité Free."}</p>:null}</div>:null}<p className="text-xs text-muted-foreground">Le forfait actuel est identifié comme <b>Free</b>. Si le projet passe plus tard sur Pro ou Team, il faudra mettre à jour cette référence pour conserver un calcul exact de l’espace restant.</p></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="size-5"/>Diagnostic d’intégrité</CardTitle><CardDescription>Recherche les incohérences importantes sans rien supprimer ni corriger automatiquement.</CardDescription></CardHeader><CardContent className="space-y-4"><Button onClick={()=>runDiagnostics.mutate()} disabled={runDiagnostics.isPending}><RefreshCw className="size-4"/>{runDiagnostics.isPending?"Analyse…":"Lancer un diagnostic"}</Button>{diagnostics?<div className="space-y-2">{diagnostics.map(d=><div key={d.key} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="flex items-center gap-2">{d.count===0?<CheckCircle2 className="size-4"/>:<AlertTriangle className="size-4"/>}<span className="text-sm font-semibold">{d.label}</span></div><Badge variant={d.count===0?"outline":"destructive"}>{d.count===0?"OK":`${d.count} anomalie(s)`}</Badge></div>)}</div>:null}</CardContent></Card>
  <Card><CardHeader><CardTitle>Sauvegarde / export technique</CardTitle><CardDescription>Copies JSON destinées à la maintenance. Ces exports ne remplacent pas les exports métier de l’application.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>doExport("configuration")}><Download className="size-4"/>Exporter la configuration</Button><Button variant="outline" onClick={()=>doExport("data")}><Download className="size-4"/>Exporter les données principales</Button></CardContent></Card>
 </div>;
}
function State({label,ok}:{label:string;ok:boolean}){return <div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-1 flex items-center gap-2 text-sm font-bold">{ok?<CheckCircle2 className="size-4"/>:<AlertTriangle className="size-4"/>}{ok?"Opérationnel":"À vérifier"}</div></div>}
function Metric({label,value}:{label:string;value:any}){return <div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">{label}</p><b className="text-lg">{value??"…"}</b></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">{label}</p><b className="break-all text-sm">{value}</b></div>}
