import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Database, Download, HardDrive, RefreshCw, ShieldCheck, UserPlus, XCircle } from "lucide-react";
import { toast } from "sonner";
import { useCurrentRole } from "@/hooks/useAuth";
import { membersQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type TechAdmin={member_id:string;full_name:string;auth_user_id:string};
type Status={database:string;auth:string;storage:string;checked_at:string;storage_used_bytes:number;storage_capacity_bytes:number|null;storage_remaining_bytes:number|null;storage_percent:number|null;file_count:number;member_count:number;program_count:number;solicitation_count:number};
type Diagnostic={key:string;label:string;count:number};
const bytes=(n:number|null|undefined)=>{if(n==null)return "Non défini";if(n<1024)return `${n} o`;if(n<1024**2)return `${(n/1024).toFixed(1)} Ko`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} Mo`;return `${(n/1024**3).toFixed(2)} Go`;};
function downloadJson(name:string,data:any){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export function TechnicalAdminPanel({settings}:{settings:any}){
 const {isTechAdmin}=useCurrentRole(); const qc=useQueryClient(); const members=useQuery(membersQuery); const [newAdmin,setNewAdmin]=useState(""); const [capacityGb,setCapacityGb]=useState(settings?.storage_capacity_bytes?String(Number(settings.storage_capacity_bytes)/(1024**3)):""); const [diagnostics,setDiagnostics]=useState<Diagnostic[]|null>(null);
 const admins=useQuery({queryKey:["technical-admins"],enabled:isTechAdmin,queryFn:async()=>{const{data,error}=await (supabase as any).rpc("technical_admins");if(error)throw error;return data as TechAdmin[]}});
 const status=useQuery({queryKey:["technical-status"],enabled:isTechAdmin,queryFn:async()=>{const{data,error}=await (supabase as any).rpc("technical_system_status");if(error)throw error;return data as Status},refetchInterval:60000});
 const activeMembers=useMemo(()=>(members.data?.members??[]).filter((m:any)=>m.status==="active"&&m.auth_user_id),[members.data]);
 const availableAdmins=activeMembers.filter((m:any)=>!(admins.data??[]).some(a=>a.member_id===m.id));
 const manage=useMutation({mutationFn:async({memberId,enabled}:{memberId:string;enabled:boolean})=>{const{error}=await (supabase as any).rpc("set_technical_admin",{p_member_id:memberId,p_enabled:enabled});if(error)throw error},onSuccess:async()=>{toast.success("Habilitation Admin technique mise à jour");setNewAdmin("");await qc.invalidateQueries({queryKey:["technical-admins"]});await qc.invalidateQueries({queryKey:["current-role"]})},onError:(e:any)=>toast.error("Modification impossible",{description:e.message})});
 const saveCapacity=useMutation({mutationFn:async()=>{const gb=Number(capacityGb.replace(",","."));if(!Number.isFinite(gb)||gb<=0)throw Error("Renseigne une capacité totale valide en Go.");const value=Math.round(gb*1024**3);const{error}=await supabase.from("app_settings").update({storage_capacity_bytes:value,updated_at:new Date().toISOString()} as any).eq("id","main");if(error)throw error},onSuccess:async()=>{toast.success("Capacité de stockage enregistrée");await qc.invalidateQueries({queryKey:["app-settings"]});await status.refetch()},onError:(e:any)=>toast.error("Enregistrement impossible",{description:e.message})});
 const runDiagnostics=useMutation({mutationFn:async()=>{const{data,error}=await (supabase as any).rpc("technical_diagnostics");if(error)throw error;return data},onSuccess:(data:any)=>{setDiagnostics(data?.checks??[]);toast.success("Diagnostic terminé")},onError:(e:any)=>toast.error("Diagnostic impossible",{description:e.message})});
 const doExport=async(kind:"configuration"|"data")=>{try{const fn=kind==="configuration"?"technical_export_configuration":"technical_export_data";const{data,error}=await (supabase as any).rpc(fn);if(error)throw error;downloadJson(`icc-${kind}-${new Date().toISOString().slice(0,10)}.json`,data);toast.success(kind==="configuration"?"Configuration exportée":"Données exportées")}catch(e:any){toast.error("Export impossible",{description:e.message})}};
 if(!isTechAdmin)return <Card><CardHeader><CardTitle>Administration technique</CardTitle><CardDescription>Cette zone est réservée aux administrateurs techniques habilités.</CardDescription></CardHeader></Card>;
 const s=status.data; const alertLevel=s?.storage_percent!=null?s.storage_percent>=90?"critical":s.storage_percent>=80?"warning":"ok":"unknown";
 return <div className="space-y-4">
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5"/>Administrateurs techniques</CardTitle><CardDescription>Habilitation transversale indépendante du rôle métier. Elle ne transforme jamais un Équipier ou un Référent en membre de la Direction.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2">{(admins.data??[]).map(a=><div key={a.member_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>{a.full_name}</b><p className="text-xs text-muted-foreground">Admin technique actif</p></div><Button variant="outline" size="sm" onClick={()=>manage.mutate({memberId:a.member_id,enabled:false})} disabled={manage.isPending}><XCircle className="size-4"/>Retirer</Button></div>)}</div><div className="grid gap-2 md:grid-cols-[1fr_auto]"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={newAdmin} onChange={e=>setNewAdmin(e.target.value)}><option value="">Ajouter un administrateur technique…</option>{availableAdmins.map((m:any)=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><Button onClick={()=>newAdmin&&manage.mutate({memberId:newAdmin,enabled:true})} disabled={!newAdmin||manage.isPending}><UserPlus className="size-4"/>Ajouter</Button></div><p className="text-xs text-muted-foreground">Seuls les membres possédant déjà un compte applicatif peuvent recevoir cette habilitation. Le dernier Admin technique ne peut pas être retiré.</p></CardContent></Card>
  <Card><CardHeader><CardTitle>État du système</CardTitle><CardDescription>Contrôle rapide des services et des volumes métier.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><State label="Base Supabase" ok={s?.database==="ok"}/><State label="Authentification" ok={s?.auth==="ok"}/><State label="Stockage fichiers" ok={s?.storage==="ok"}/><div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">Dernière vérification</p><b className="text-sm">{s?.checked_at?new Date(s.checked_at).toLocaleString("fr-FR"):"…"}</b></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Membres" value={s?.member_count}/><Metric label="Programmes" value={s?.program_count}/><Metric label="Sollicitations" value={s?.solicitation_count}/><Metric label="Fichiers" value={s?.file_count}/></div><Button variant="outline" onClick={()=>status.refetch()}><RefreshCw className="size-4"/>Actualiser</Button></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><HardDrive className="size-5"/>Stockage & fichiers</CardTitle><CardDescription>L’espace utilisé est calculé depuis les fichiers réellement stockés. La capacité totale du plan Supabase n’est pas exposée automatiquement à l’application : renseigne-la une seule fois pour calculer exactement l’espace restant.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Metric label="Espace utilisé" value={bytes(s?.storage_used_bytes)}/><Metric label="Capacité totale" value={bytes(s?.storage_capacity_bytes)}/><Metric label="Espace restant" value={bytes(s?.storage_remaining_bytes)}/></div>{s?.storage_percent!=null?<div className="rounded-xl border p-3"><div className="flex items-center justify-between gap-3"><b>{s.storage_percent}% utilisé</b><Badge variant={alertLevel==="critical"?"destructive":"outline"}>{alertLevel==="critical"?"Critique":alertLevel==="warning"?"Attention":"Normal"}</Badge></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-foreground" style={{width:`${Math.min(s.storage_percent,100)}%`}}/></div>{alertLevel!=="ok"?<p className="mt-2 text-xs text-muted-foreground">{alertLevel==="critical"?"Le stockage dépasse 90 % de la capacité configurée.":"Le stockage dépasse 80 % de la capacité configurée."}</p>:null}</div>:null}<div className="grid gap-2 md:grid-cols-[1fr_auto] md:items-end"><div><Label>Capacité totale de ton plan Supabase (Go)</Label><Input className="mt-2" inputMode="decimal" value={capacityGb} onChange={e=>setCapacityGb(e.target.value)} placeholder="Ex. 1 ou 100"/></div><Button onClick={()=>saveCapacity.mutate()} disabled={saveCapacity.isPending}>Enregistrer la capacité</Button></div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="size-5"/>Diagnostic d’intégrité</CardTitle><CardDescription>Recherche les incohérences importantes sans rien supprimer ni corriger automatiquement.</CardDescription></CardHeader><CardContent className="space-y-4"><Button onClick={()=>runDiagnostics.mutate()} disabled={runDiagnostics.isPending}><RefreshCw className="size-4"/>{runDiagnostics.isPending?"Analyse…":"Lancer un diagnostic"}</Button>{diagnostics?<div className="space-y-2">{diagnostics.map(d=><div key={d.key} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="flex items-center gap-2">{d.count===0?<CheckCircle2 className="size-4"/>:<AlertTriangle className="size-4"/>}<span className="text-sm font-semibold">{d.label}</span></div><Badge variant={d.count===0?"outline":"destructive"}>{d.count===0?"OK":`${d.count} anomalie(s)`}</Badge></div>)}</div>:null}</CardContent></Card>
  <Card><CardHeader><CardTitle>Sauvegarde / export technique</CardTitle><CardDescription>Copies JSON destinées à la maintenance. Ces exports ne remplacent pas les exports métier de l’application.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>doExport("configuration")}><Download className="size-4"/>Exporter la configuration</Button><Button variant="outline" onClick={()=>doExport("data")}><Download className="size-4"/>Exporter les données principales</Button></CardContent></Card>
 </div>;
}
function State({label,ok}:{label:string;ok:boolean}){return <div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-1 flex items-center gap-2 text-sm font-bold">{ok?<CheckCircle2 className="size-4"/>:<AlertTriangle className="size-4"/>}{ok?"Opérationnel":"À vérifier"}</div></div>}
function Metric({label,value}:{label:string;value:any}){return <div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">{label}</p><b className="text-lg">{value??"…"}</b></div>}
